---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: El recurso compartido de auditoría contiene el archivo audit.log activo y cualquier archivo de registro de auditoría comprimido.  Puede acceder a los archivos de registro de auditoría directamente desde la línea de comando del nodo de administración. 
---
= Archivo de registro de auditoría de acceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La parte de auditoría contiene los activos `audit.log` archivo y cualquier archivo de registro de auditoría comprimido.  Puede acceder a los archivos de registro de auditoría directamente desde la línea de comando del nodo de administración.

.Antes de empezar
* Tieneslink:../admin/admin-group-permissions.html["permisos de acceso específicos"] .
* Debes tener el `Passwords.txt` archivo.
* Debes conocer la dirección IP de un nodo de administración.


.Pasos
. Inicie sesión en un nodo de administración:
+
.. Introduzca el siguiente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .



. Vaya al directorio que contiene los archivos de registro de auditoría:
+
`cd /var/local/log`

. Ver el archivo de registro de auditoría actual o guardado, según sea necesario.

