---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: Los mensajes de auditoría intercambiados dentro del sistema StorageGRID incluyen información estándar común a todos los mensajes y contenido específico que describe el evento o la actividad que se informa. 
---
= Formato del mensaje de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría intercambiados dentro del sistema StorageGRID incluyen información estándar común a todos los mensajes y contenido específico que describe el evento o la actividad que se informa.

Si la información resumida proporcionada por ellink:using-audit-explain-tool.html["auditoría-explicación"] ylink:using-audit-sum-tool.html["suma de auditoría"] Si las herramientas son insuficientes, consulte esta sección para comprender el formato general de todos los mensajes de auditoría.

El siguiente es un ejemplo de mensaje de auditoría tal como podría aparecer en el archivo de registro de auditoría:

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Cada mensaje de auditoría contiene una cadena de elementos de atributos.  La cadena completa está entre corchetes.(`[ ]` ), y cada elemento de atributo en la cadena tiene las siguientes características:

* Entre paréntesis `[ ]`
* Introducido por la cadena `AUDT` , lo que indica un mensaje de auditoría
* Sin delimitadores (sin comas ni espacios) antes ni después
* Terminado por un carácter de avance de línea `\n`


Cada elemento incluye un código de atributo, un tipo de dato y un valor que se informan en este formato:

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
La cantidad de elementos de atributo en el mensaje depende del tipo de evento del mensaje.  Los elementos de atributo no se enumeran en ningún orden particular.

La siguiente lista describe los elementos de atributo:

* `ATTR`es un código de cuatro caracteres para el atributo que se informa.  Hay algunos atributos que son comunes a todos los mensajes de auditoría y otros que son específicos del evento.
* `type`es un identificador de cuatro caracteres del tipo de datos de programación del valor, como UI64, FC32, etc.  El tipo está entre paréntesis. `( )` .
* `value`es el contenido del atributo, normalmente un valor numérico o de texto.  Los valores siempre siguen a dos puntos(`:` ).  Los valores del tipo de datos CSTR están rodeados por comillas dobles " ".

