---
permalink: audit/bror-bucket-read-only-request.html 
sidebar: sidebar 
keywords: bror, bucket read only request, empty bucket, audit message, 
summary: El servicio LDR genera este mensaje de auditoría cuando un depósito entra o sale del modo de solo lectura.  Por ejemplo, un depósito entra en modo de solo lectura mientras se está vaciando. 
---
= BROR: Solicitud de solo lectura de depósito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servicio LDR genera este mensaje de auditoría cuando un depósito entra o sale del modo de solo lectura.  Por ejemplo, un depósito entra en modo de solo lectura mientras se eliminan todos los objetos.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
BKHD
 a| 
UUID del depósito
 a| 
El identificador del depósito.



 a| 
Brov
 a| 
Valor de solicitud de solo lectura del depósito
 a| 
Si el depósito se está convirtiendo en de solo lectura o está abandonando el estado de solo lectura (1 = solo lectura, 0 = no de solo lectura).



 a| 
Hermanos
 a| 
Razón de solo lectura del bucket
 a| 
El motivo por el cual el depósito se convierte en de solo lectura o abandona ese estado.  Por ejemplo, emptyBucket.



 a| 
S3AI
 a| 
ID de cuenta de inquilino de S3
 a| 
El ID de la cuenta del inquilino que envió la solicitud.  Un valor vacío indica acceso anónimo.



 a| 
S3BK
 a| 
Cubo S3
 a| 
El nombre del depósito S3.

|===