---
permalink: audit/ebdl-empty-bucket-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, EBDL, Empty Bucket Delete 
summary: 'El escáner ILM eliminó un objeto en un depósito que está eliminando todos los objetos (realizando una operación de depósito vacío).' 
---
= EBDL: Eliminar depósito vacío
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El escáner ILM eliminó un objeto en un depósito que está eliminando todos los objetos (realizando una operación de depósito vacío).

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
CSIZ
 a| 
Tamaño del objeto
 a| 
El tamaño del objeto en bytes.



 a| 
CAMINO
 a| 
Cubo/clave S3
 a| 
El nombre del depósito S3 y el nombre de la clave S3.



 a| 
SEGC
 a| 
UUID del contenedor
 a| 
UUID del contenedor del objeto segmentado.  Este valor solo está disponible si el objeto está segmentado.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto dentro del sistema StorageGRID .



 a| 
RSLT
 a| 
Resultado de la operación de eliminación
 a| 
El resultado de un evento, proceso o transacción.  Si no es relevante para un mensaje, se utiliza NONE en lugar de SUCS para que el mensaje no se filtre accidentalmente.

|===