---
permalink: audit/gnrg-gnds-registration.html 
sidebar: sidebar 
keywords: storagegrid, audi, message, GNRG, GNDS Registration 
summary: El servicio CMN genera este mensaje de auditoría cuando un servicio ha actualizado o registrado información sobre sí mismo en el sistema StorageGRID . 
---
= GNRG: Registro GNDS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servicio CMN genera este mensaje de auditoría cuando un servicio ha actualizado o registrado información sobre sí mismo en el sistema StorageGRID .

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
RSLT
 a| 
Resultado
 a| 
El resultado de la solicitud de actualización:

* SUCS: Exitoso
* SUNV: Servicio no disponible
* GERR: Otro fracaso




 a| 
GNID
 a| 
Nodo ID
 a| 
El ID del nodo del servicio que inició la solicitud de actualización.



 a| 
GNTP
 a| 
Tipo de dispositivo
 a| 
El tipo de dispositivo del nodo de la red (por ejemplo, BLDR para un servicio LDR).



 a| 
GNDV
 a| 
Versión del modelo del dispositivo
 a| 
La cadena que identifica la versión del modelo del dispositivo del nodo de la red en el paquete DMDL.



 a| 
GNGP
 a| 
Grupo
 a| 
El grupo al que pertenece el nodo de la red (en el contexto de los costos de enlace y la clasificación de consultas de servicio).



 a| 
GNIA
 a| 
Dirección IP
 a| 
La dirección IP del nodo de la red.

|===
Este mensaje se genera cada vez que un nodo de la cuadrícula actualiza su entrada en el paquete de nodos de la cuadrícula.
