---
permalink: audit/gtst-grid-task-started.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTST, Grid Task Started 
summary: Este mensaje de auditoría indica que el servicio CMN ha comenzado a procesar la tarea de cuadrícula especificada.  El mensaje de auditoría sigue inmediatamente al mensaje de Tarea de cuadrícula enviada para las tareas de cuadrícula iniciadas por el servicio interno de Envío de tareas de cuadrícula y seleccionadas para activación automática.  Para las tareas de cuadrícula enviadas a la tabla Pendientes, este mensaje se genera cuando el usuario inicia la tarea de cuadrícula. 
---
= GTST: Tarea de cuadrícula iniciada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje de auditoría indica que el servicio CMN ha comenzado a procesar la tarea de cuadrícula especificada.  El mensaje de auditoría sigue inmediatamente al mensaje de Tarea de cuadrícula enviada para las tareas de cuadrícula iniciadas por el servicio interno de Envío de tareas de cuadrícula y seleccionadas para activación automática.  Para las tareas de cuadrícula enviadas a la tabla Pendientes, este mensaje se genera cuando el usuario inicia la tarea de cuadrícula.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
TSID
 a| 
ID de tarea
 a| 
Este campo identifica de forma única una tarea de cuadrícula generada y permite administrar la tarea durante su ciclo de vida.

*Nota:* El ID de tarea se asigna en el momento en que se genera una tarea de cuadrícula, no en el momento en que se envía.  Es posible que una tarea de cuadrícula determinada se envíe varias veces y, en este caso, el campo ID de tarea no es suficiente para vincular de forma única los mensajes de auditoría Enviado, Iniciado y Finalizado.



 a| 
RSLT
 a| 
Resultado
 a| 
El resultado.  Este campo solo tiene un valor:

* SUCS: La tarea de cuadrícula se inició exitosamente.


|===