---
permalink: audit/ilm-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, ILM, IDEL, LKCU, ORLM 
summary: Los mensajes de auditoría que pertenecen a la categoría de auditoría ILM se utilizan para eventos relacionados con las operaciones del ciclo de vida de la información. 
---
= Mensajes de auditoría de ILM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría que pertenecen a la categoría de auditoría ILM se utilizan para eventos relacionados con las operaciones de gestión del ciclo de vida de la información (ILM).

[cols="1a,3a,1a"]
|===
| Código | Título y descripción del mensaje | Ver 


 a| 
IDEL
 a| 
Eliminación iniciada por ILM: este mensaje de auditoría se genera cuando ILM inicia el proceso de eliminación de un objeto.
 a| 
link:idel-ilm-initiated-delete.html["IDEL: Eliminación iniciada por ILM"]



 a| 
LKCU
 a| 
Limpieza de objetos sobrescritos.  Este mensaje de auditoría se genera cuando un objeto sobrescrito se elimina automáticamente para liberar espacio de almacenamiento.
 a| 
link:lkcu-overwritten-object-cleanup.html["LKCU: Limpieza de objetos sobrescritos"]



 a| 
ORLM
 a| 
Reglas de objeto cumplidas: este mensaje de auditoría se genera cuando los datos del objeto se almacenan según lo especificado por las reglas de ILM.
 a| 
link:orlm-object-rules-met.html["ORLM: Se cumplen las reglas de objeto"]

|===