---
permalink: audit/index.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: Estas instrucciones contienen información sobre la estructura y el contenido de los mensajes de auditoría y los registros de auditoría de StorageGRID .  Puede utilizar esta información para leer y analizar el registro de auditoría de la actividad del sistema. 
---
= Mensajes y registros de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas instrucciones contienen información sobre la estructura y el contenido de los mensajes de auditoría y los registros de auditoría de StorageGRID .  Puede utilizar esta información para leer y analizar el registro de auditoría de la actividad del sistema.

Estas instrucciones están dirigidas a los administradores responsables de producir informes de actividad y uso del sistema que requieren el análisis de los mensajes de auditoría del sistema StorageGRID .

Para utilizar el archivo de registro de texto, debe tener acceso al recurso compartido de auditoría configurado en el nodo de administración.

Para obtener información sobre cómo configurar los niveles de mensajes de auditoría y utilizar un servidor syslog externo, consultelink:../monitor/configure-audit-messages.html["Configurar mensajes de auditoría y destinos de registro"] .
