---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM: Limpieza de objetos filtrados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje se genera cuando se ha limpiado o eliminado un fragmento filtrado.  Un fragmento puede ser parte de un objeto replicado o de un objeto codificado para borrado.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
CLOC
 a| 
Ubicación del fragmento
 a| 
La ruta del archivo del fragmento filtrado que se eliminó.



 a| 
CTYP
 a| 
Tipo de trozo
 a| 
Tipo de fragmento:

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
LTYP
 a| 
Tipo de fuga
 a| 
Los cinco tipos de fugas que se pueden detectar:

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
CTIM
 a| 
Tiempo de creación de fragmentos
 a| 
Hora en que se creó el fragmento filtrado.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto al que pertenece el fragmento.



 a| 
CBD
 a| 
Identificador de bloque de contenido
 a| 
CBID del objeto al que pertenece el fragmento filtrado.



 a| 
CSIZ
 a| 
Tamaño del contenido
 a| 
El tamaño del fragmento en bytes.

|===