---
permalink: audit/olst-system-detected-lost-object.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, OLST, System Detected Lost Object 
summary: Este mensaje se genera cuando el servicio DDS no puede localizar ninguna copia de un objeto dentro del sistema StorageGRID . 
---
= OLST: El sistema detectó un objeto perdido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje se genera cuando el servicio DDS no puede localizar ninguna copia de un objeto dentro del sistema StorageGRID .

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
CBD
 a| 
Identificador de bloque de contenido
 a| 
El CBID del objeto perdido.



 a| 
NOID
 a| 
Nodo ID
 a| 
Si está disponible, la última ubicación conocida, directa o cercana, del objeto perdido.  Es posible tener solo el ID de nodo sin un ID de volumen si la información del volumen no está disponible.



 a| 
CAMINO
 a| 
Cubo/clave S3
 a| 
Si está disponible, el nombre del depósito S3 y el nombre de la clave S3.



 a| 
RSLT
 a| 
Resultado
 a| 
Este campo tiene el valor NINGUNO.  RSLT es un campo de mensaje obligatorio, pero no es relevante para este mensaje.  Se utiliza NONE en lugar de SUCS para que este mensaje no se filtre.



 a| 
UUID
 a| 
Identificación universalmente única
 a| 
El identificador del objeto perdido dentro del sistema StorageGRID .



 a| 
VOLI
 a| 
ID de volumen
 a| 
Si está disponible, el ID de volumen del nodo de almacenamiento de la última ubicación conocida del objeto perdido.

|===