---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: Este mensaje indica que un usuario inició un trabajo de selección S3. 
---
= S3SL: Solicitud de selección de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje registra una finalización después de que se haya devuelto una solicitud S3 Select al cliente.  El mensaje S3SL puede incluir detalles del mensaje de error y del código de error.  Es posible que la solicitud no haya tenido éxito.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
BYSC
 a| 
Bytes escaneados
 a| 
Número de bytes escaneados (recibidos) desde los nodos de almacenamiento.

Es probable que BYSC y BYPR sean diferentes si el objeto está comprimido.  Si el objeto está comprimido, BYSC tendrá el recuento de bytes comprimidos y BYPR serán los bytes después de la descompresión.



 a| 
BYPR
 a| 
Bytes procesados
 a| 
Número de bytes procesados.  Indica cuántos bytes de "Bytes escaneados" fueron realmente procesados o procesados por un trabajo S3 Select.



 a| 
BYRT
 a| 
Bytes devueltos
 a| 
Número de bytes que un trabajo S3 Select devolvió al cliente.



 a| 
REPR
 a| 
Registros procesados
 a| 
Número de registros o filas que un trabajo S3 Select recibió de los nodos de almacenamiento.



 a| 
RERT
 a| 
Registros devueltos
 a| 
Número de registros o filas que un trabajo S3 Select devolvió al cliente.



 a| 
JOFI
 a| 
Trabajo terminado
 a| 
Indica si el trabajo S3 Select finalizó el procesamiento o no.  Si esto es falso, entonces el trabajo no pudo finalizar y los campos de error probablemente contendrán datos.  Es posible que el cliente haya recibido resultados parciales o ningún resultado.



 a| 
REID
 a| 
ID de solicitud
 a| 
Identificador de la solicitud S3 Select.



 a| 
EXTRA
 a| 
Tiempo de ejecución
 a| 
El tiempo, en segundos, que tardó el trabajo de selección S3 en completarse.



 a| 
ERMG
 a| 
Mensaje de error
 a| 
Mensaje de error que generó el trabajo S3 Select.



 a| 
TERRENO
 a| 
Tipo de error
 a| 
Tipo de error que generó el trabajo S3 Select.



 a| 
ANTE TODO
 a| 
Seguimiento de errores
 a| 
Seguimiento de pila de errores que generó el trabajo S3 Select.



 a| 
S3BK
 a| 
Cubo S3
 a| 
El nombre del depósito S3.



 a| 
S3AK
 a| 
ID de clave de acceso S3 (remitente de la solicitud)
 a| 
El ID de la clave de acceso S3 del usuario que envió la solicitud.



 a| 
S3AI
 a| 
ID de cuenta de inquilino de S3 (remitente de la solicitud)
 a| 
El ID de la cuenta de inquilino del usuario que envió la solicitud.



 a| 
S3KY
 a| 
Clave S3
 a| 
El nombre de la clave S3, sin incluir el nombre del depósito.

|===