---
permalink: audit/sadd-security-audit-disable.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SADD, Security Audit Disable 
summary: 'Este mensaje indica que el servicio de origen (ID de nodo) ha desactivado el registro de mensajes de auditoría; los mensajes de auditoría ya no se recopilan ni se envían.' 
---
= SADD: Desactivación de auditoría de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje indica que el servicio de origen (ID de nodo) ha desactivado el registro de mensajes de auditoría; los mensajes de auditoría ya no se recopilan ni se envían.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
AETM
 a| 
Habilitar método
 a| 
El método utilizado para deshabilitar la auditoría.



 a| 
AEUN
 a| 
Nombre de usuario
 a| 
El nombre de usuario que ejecutó el comando para deshabilitar el registro de auditoría.



 a| 
RSLT
 a| 
Resultado
 a| 
Este campo tiene el valor NINGUNO.  RSLT es un campo de mensaje obligatorio, pero no es relevante para este mensaje.  Se utiliza NONE en lugar de SUCS para que este mensaje no se filtre.

|===
El mensaje implica que el registro estaba habilitado anteriormente, pero ahora se ha deshabilitado.  Normalmente esto se usa solo durante la ingesta masiva para mejorar el rendimiento del sistema.  Luego de la actividad masiva, se restablece la auditoría (SADE) y la capacidad de deshabilitarla se bloquea de forma permanente.
