---
permalink: audit/scmt-object-store-commit.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SCMT, Object Store Commit 
summary: 'El contenido de la red no se pone a disposición ni se reconoce como almacenado hasta que se haya confirmado (lo que significa que se ha almacenado de forma persistente).  El contenido almacenado de forma persistente se ha escrito completamente en el disco y ha pasado las comprobaciones de integridad relacionadas.  Este mensaje se emite cuando un bloque de contenido se envía al almacenamiento.' 
---
= SCMT: Confirmación del almacén de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El contenido de la red no se pone a disposición ni se reconoce como almacenado hasta que se haya confirmado (lo que significa que se ha almacenado de forma persistente).  El contenido almacenado de forma persistente se ha escrito completamente en el disco y ha pasado las comprobaciones de integridad relacionadas.  Este mensaje se emite cuando un bloque de contenido se envía al almacenamiento.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
CBD
 a| 
Identificador de bloque de contenido
 a| 
El identificador único del bloque de contenido destinado al almacenamiento permanente.



 a| 
RSLT
 a| 
Código de resultado
 a| 
Estado en el momento en que el objeto se almacenó en el disco:

SUCS: Objeto almacenado exitosamente.

|===
Este mensaje significa que un bloque de contenido determinado se ha almacenado y verificado por completo y ahora se puede solicitar.  Se puede utilizar para rastrear el flujo de datos dentro del sistema.
