---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: Cuando un cliente S3 emite una transacción DELETE, se realiza una solicitud para eliminar el objeto o depósito especificado.  El servidor emite este mensaje si la transacción es exitosa. 
---
= SDEL: S3 ELIMINAR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un cliente S3 emite una transacción DELETE, se realiza una solicitud para eliminar el objeto o depósito especificado, o para eliminar un subrecurso de depósito/objeto.  El servidor emite este mensaje si la transacción es exitosa.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
CBD
 a| 
Identificador de bloque de contenido
 a| 
El identificador único del bloque de contenido solicitado.  Si se desconoce el CBID, este campo se establece en 0.  Las operaciones en depósitos no incluyen este campo.



 a| 
CNCH
 a| 
Encabezado de control de consistencia
 a| 
El valor del encabezado de solicitud HTTP Consistency-Control, si está presente en la solicitud.



 a| 
CNID
 a| 
Identificador de conexión
 a| 
El identificador único del sistema para la conexión TCP/IP.



 a| 
CSIZ
 a| 
Tamaño del contenido
 a| 
El tamaño del objeto eliminado en bytes.  Las operaciones en depósitos no incluyen este campo.



 a| 
DMRK
 a| 
Eliminar ID de versión del marcador
 a| 
El ID de la versión del marcador de eliminación creado al eliminar un objeto de un depósito versionado.  Las operaciones en depósitos no incluyen este campo.



 a| 
GFID
 a| 
ID de conexión de la federación de red
 a| 
El ID de conexión de la conexión de federación de red asociada con una solicitud de eliminación de replicación entre redes.  Sólo se incluye en los registros de auditoría de la red de destino.



 a| 
GFSA
 a| 
ID de cuenta de origen de Grid Federation
 a| 
El ID de cuenta del inquilino en la red de origen para una solicitud de eliminación de replicación entre redes.  Sólo se incluye en los registros de auditoría de la red de destino.



 a| 
HTRH
 a| 
Encabezado de solicitud HTTP
 a| 
Lista de nombres y valores de encabezado de solicitud HTTP registrados según se seleccionaron durante la configuración.

 `X-Forwarded-For`se incluye automáticamente si está presente en la solicitud y si el `X-Forwarded-For` El valor es diferente de la dirección IP del remitente de la solicitud (campo de auditoría SAIP).

`x-amz-bypass-governance-retention`Se incluye automáticamente si está presente en la solicitud.



 a| 
MTME
 a| 
Hora de última modificación
 a| 
La marca de tiempo de Unix, en microsegundos, que indica cuándo se modificó el objeto por última vez.



 a| 
RSLT
 a| 
Código de resultado
 a| 
Resultado de la transacción DELETE.  El resultado siempre es:

SUCS: Exitoso



 a| 
S3AI
 a| 
ID de cuenta de inquilino de S3 (remitente de la solicitud)
 a| 
El ID de la cuenta de inquilino del usuario que envió la solicitud.  Un valor vacío indica acceso anónimo.



 a| 
S3AK
 a| 
ID de clave de acceso S3 (remitente de la solicitud)
 a| 
El ID de clave de acceso S3 en formato hash para el usuario que envió la solicitud.  Un valor vacío indica acceso anónimo.



 a| 
S3BK
 a| 
Cubo S3
 a| 
El nombre del depósito S3.



 a| 
S3KY
 a| 
Clave S3
 a| 
El nombre de la clave S3, sin incluir el nombre del depósito.  Las operaciones en depósitos no incluyen este campo.



 a| 
S3SR
 a| 
Subrecurso S3
 a| 
El subrecurso del objeto o depósito en el que se opera, si corresponde.



 a| 
SACC
 a| 
Nombre de la cuenta del inquilino de S3 (remitente de la solicitud)
 a| 
El nombre de la cuenta de inquilino del usuario que envió la solicitud.  Vacío para solicitudes anónimas.



 a| 
SAIP
 a| 
Dirección IP (remitente de la solicitud)
 a| 
La dirección IP de la aplicación cliente que realizó la solicitud.



 a| 
SBAC
 a| 
Nombre de la cuenta del inquilino de S3 (propietario del depósito)
 a| 
El nombre de la cuenta del inquilino del propietario del depósito.  Se utiliza para identificar acceso entre cuentas o anónimo.



 a| 
SBAI
 a| 
ID de cuenta de inquilino de S3 (propietario del depósito)
 a| 
El ID de la cuenta de inquilino del propietario del depósito de destino.  Se utiliza para identificar acceso entre cuentas o anónimo.



 a| 
SGRP
 a| 
Sitio (Grupo)
 a| 
Si está presente, el objeto se eliminó en el sitio especificado, que no es el sitio donde se ingirió el objeto.



 a| 
SUSR
 a| 
URN de usuario S3 (remitente de la solicitud)
 a| 
El ID de la cuenta del inquilino y el nombre de usuario del usuario que realiza la solicitud.  El usuario puede ser un usuario local o un usuario LDAP. Por ejemplo:  `urn:sgws:identity::03393893651506583485:root`

Vacío para solicitudes anónimas.



 a| 
TIEMPO
 a| 
Tiempo
 a| 
Tiempo total de procesamiento de la solicitud en microsegundos.



 a| 
TLIP
 a| 
Dirección IP del balanceador de carga confiable
 a| 
Si la solicitud fue enrutada por un balanceador de carga de capa 7 confiable, la dirección IP del balanceador de carga.



 a| 
UUDM
 a| 
Identificador único universal para un marcador de eliminación
 a| 
El identificador de un marcador de eliminación.  Los mensajes del registro de auditoría especifican UUDM o UUID, donde UUDM indica un marcador de eliminación creado como resultado de una solicitud de eliminación de objeto y UUID indica un objeto.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto dentro del sistema StorageGRID .



 a| 
VSID
 a| 
ID de versión
 a| 
El ID de la versión de la versión específica de un objeto que se eliminó.  Las operaciones en depósitos y objetos en depósitos no versionados no incluyen este campo.

|===