---
permalink: audit/system-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, LLST, OLST, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST 
summary: 'Los mensajes de auditoría que pertenecen a la categoría de auditoría del sistema se utilizan para eventos relacionados con el sistema de auditoría en sí, estados de los nodos de la red, actividad de tareas de todo el sistema (tareas de la red) y operaciones de respaldo de servicio.' 
---
= Mensajes de auditoría del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría que pertenecen a la categoría de auditoría del sistema se utilizan para eventos relacionados con el sistema de auditoría en sí, estados de los nodos de la red, actividad de tareas de todo el sistema (tareas de la red) y operaciones de respaldo de servicio.

[cols="1a,2a,1a"]
|===
| Código | Título y descripción del mensaje | Ver 


 a| 
ECMC
 a| 
Fragmento de datos codificado por borrado faltante: indica que se ha detectado un fragmento de datos codificado por borrado faltante.
 a| 
link:ecmc-missing-erasure-coded-data-fragment.html["ECMC: Fragmento de datos con código de borrado faltante"]



 a| 
ECOC
 a| 
Fragmento de datos codificado por borrado corrupto: indica que se ha detectado un fragmento de datos codificado por borrado corrupto.
 a| 
link:ecoc-corrupt-erasure-coded-data-fragment.html["ECOC: Fragmento de datos corruptos codificados por borrado"]



 a| 
ETAF
 a| 
Error de autenticación de seguridad: falló un intento de conexión mediante Seguridad de la capa de transporte (TLS).
 a| 
link:etaf-security-authentication-failed.html["ETAF: Falló la autenticación de seguridad"]



 a| 
GNRG
 a| 
Registro GNDS: Un servicio actualiza o registra información sobre sí mismo en el sistema StorageGRID .
 a| 
link:gnrg-gnds-registration.html["GNRG: Registro GNDS"]



 a| 
GNUR
 a| 
Anulación del registro de GNDS: un servicio se ha anulado su registro en el sistema StorageGRID .
 a| 
link:gnur-gnds-unregistration.html["GNUR: Anulación del registro de GNDS"]



 a| 
GTED
 a| 
Tarea de cuadrícula finalizada: el servicio CMN terminó de procesar la tarea de cuadrícula.
 a| 
link:gted-grid-task-ended.html["GTED: Tarea de cuadrícula finalizada"]



 a| 
GTST
 a| 
Tarea de cuadrícula iniciada: el servicio CMN comenzó a procesar la tarea de cuadrícula.
 a| 
link:gtst-grid-task-started.html["GTST: Tarea de cuadrícula iniciada"]



 a| 
GTSU
 a| 
Tarea de cuadrícula enviada: se envió una tarea de cuadrícula al servicio CMN.
 a| 
link:gtsu-grid-task-submitted.html["GTSU: Tarea de cuadrícula enviada"]



 a| 
LLST
 a| 
Ubicación perdida: este mensaje de auditoría se genera cuando se pierde una ubicación.
 a| 
link:llst-location-lost.html["LLST: Ubicación perdida"]



 a| 
OLST
 a| 
Objeto perdido: un objeto solicitado no se puede ubicar dentro del sistema StorageGRID .
 a| 
link:olst-system-detected-lost-object.html["OLST: El sistema detectó un objeto perdido"]



 a| 
Tristeza
 a| 
Deshabilitar auditoría de seguridad: se desactivó el registro de mensajes de auditoría.
 a| 
link:sadd-security-audit-disable.html["SADD: Desactivación de auditoría de seguridad"]



 a| 
SADE
 a| 
Habilitar auditoría de seguridad: se ha restaurado el registro de mensajes de auditoría.
 a| 
link:sade-security-audit-enable.html["SADE: Habilitación de auditoría de seguridad"]



 a| 
SVRF
 a| 
Error de verificación del almacén de objetos: un bloque de contenido no pasó las verificaciones de verificación.
 a| 
link:svrf-object-store-verify-fail.html["SVRF: Error en la verificación del almacén de objetos"]



 a| 
Unidad de Registro de Víctimas de Violencia Doméstica
 a| 
Verificación de almacén de objetos desconocido: se detectaron datos de objetos inesperados en el almacén de objetos.
 a| 
link:svru-object-store-verify-unknown.html["SVRU: Verificación de almacén de objetos desconocida"]



 a| 
Distrito Escolar Unificado de Syracuse
 a| 
Parada de nodo: se solicitó un apagado.
 a| 
link:sysd-node-stop.html["SYSD: Parada de nodo"]



 a| 
SISTEMA
 a| 
Detención de nodo: un servicio inició una detención elegante.
 a| 
link:syst-node-stopping.html["SYST: Nodo deteniéndose"]



 a| 
SYSU
 a| 
Inicio de nodo: se inició un servicio; la naturaleza del apagado anterior se indica en el mensaje.
 a| 
link:sysu-node-start.html["SYSU: Inicio del nodo"]

|===