---
permalink: audit/sysu-node-start.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYSU, Node Start 
summary: 'Cuando se reinicia un servicio, se genera este mensaje para indicar si el apagado anterior fue limpio (ordenado) o desordenado (inesperado).' 
---
= SYSU: Inicio del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se reinicia un servicio, se genera este mensaje para indicar si el apagado anterior fue limpio (ordenado) o desordenado (inesperado).

[cols="1a,1a,4a"]
|===
| Código | Campo | Descripción 


 a| 
RSLT
 a| 
Apagado limpio
 a| 
La naturaleza del cierre:

SUCS: El sistema se apagó limpiamente.

DSDN: El sistema no se apagó limpiamente.

VRGN: El sistema se inició por primera vez después de la instalación (o reinstalación) del servidor.

|===
El mensaje no indica si se inició el servidor host, solo el servicio de informes.  Este mensaje se puede utilizar para:

* Detectar discontinuidad en el registro de auditoría.
* Determinar si un servicio está fallando durante la operación (ya que la naturaleza distribuida del sistema StorageGRID puede enmascarar estas fallas).  El Administrador de servidor reinicia automáticamente un servicio fallido.

