---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 11.9 utiliza la versión 4 de la API de administración de inquilinos. La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 aún son compatibles. 
---
= Cambios en la API de administración de inquilinos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9 utiliza la versión 4 de la API de administración de inquilinos. La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 aún son compatibles.


NOTE: Puede seguir usando versiones obsoletas de la API de administración de inquilinos con StorageGRID 11.9; sin embargo, la compatibilidad con estas versiones de la API se eliminará en una futura versión de StorageGRID. Después de actualizar a StorageGRID 11.9, puede desactivar las API obsoletas mediante el uso de `PUT /grid/config/management` API.

Para obtener más información, visitelink:../tenant/understanding-tenant-management-api.html["Comprenda la API de administración de inquilinos"] .



== Nueva API para el límite de capacidad del bucket

Puedes utilizar el `/org/containers/{bucketName}/quota-object-bytes` API con operaciones GET/PUT para obtener y establecer el límite de capacidad de almacenamiento para un depósito.
