---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Conozca cómo se verá afectado su sistema StorageGRID durante la actualización. 
---
= Cómo se ve afectado su sistema durante la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca cómo se verá afectado su sistema StorageGRID durante la actualización.



== Las actualizaciones de StorageGRID no son disruptivas

El sistema StorageGRID puede ingerir y recuperar datos de las aplicaciones cliente durante todo el proceso de actualización.  Si aprueba que todos los nodos del mismo tipo se actualicen (por ejemplo, nodos de almacenamiento), los nodos se desactivan uno a la vez, por lo que no hay ningún momento en el que todos los nodos de la red o todos los nodos de la red de un determinado tipo no estén disponibles.

Para permitir la disponibilidad continua, asegúrese de que su política ILM contenga reglas que especifiquen el almacenamiento de múltiples copias de cada objeto.  También debe asegurarse de que todos los clientes S3 externos estén configurados para enviar solicitudes a uno de los siguientes:

* Una dirección IP virtual de grupo de alta disponibilidad (HA)
* Un balanceador de carga de terceros de alta disponibilidad
* Múltiples nodos de puerta de enlace para cada cliente
* Múltiples nodos de almacenamiento para cada cliente




== Las aplicaciones cliente podrían experimentar interrupciones a corto plazo

El sistema StorageGRID puede ingerir y recuperar datos de las aplicaciones cliente durante todo el proceso de actualización; sin embargo, las conexiones de los clientes a los nodos de puerta de enlace o nodos de almacenamiento individuales pueden interrumpirse temporalmente si la actualización necesita reiniciar los servicios en esos nodos.  La conectividad se restablecerá una vez que se complete el proceso de actualización y se reanuden los servicios en los nodos individuales.

Es posible que sea necesario programar un tiempo de inactividad para aplicar una actualización si la pérdida de conectividad por un período breve no es aceptable.  Puede utilizar la aprobación selectiva para programar cuándo se actualizan determinados nodos.


NOTE: Puede utilizar varias puertas de enlace y grupos de alta disponibilidad (HA) para proporcionar conmutación por error automática durante el proceso de actualización. Vea las instrucciones paralink:../admin/configure-high-availability-group.html["configuración de grupos de alta disponibilidad"] .



== El firmware del dispositivo se ha actualizado

Durante la actualización de StorageGRID 11.9:

* Todos los nodos del dispositivo StorageGRID se actualizan automáticamente a la versión 3.9 del firmware del instalador del dispositivo StorageGRID .
* Los dispositivos SG6060 y SGF6024 se actualizan automáticamente a la versión de firmware BIOS 3B08.EX y a la versión de firmware BMC 4.00.07.
* Los dispositivos SG100 y SG1000 se actualizan automáticamente a la versión de firmware BIOS 3B13.EC y a la versión de firmware BMC 4.74.07.
* Los dispositivos SGF6112, SG6160, SG110 y SG1100 se actualizan automáticamente a la versión de firmware 3.16.07 de BMC .




== Las políticas de ILM se manejan de manera diferente según su estado

* La política activa seguirá siendo la misma después de la actualización.
* Al actualizar, solo se conservan las últimas 10 políticas históricas.
* Si hay una política propuesta, se eliminará durante la actualización.




== Es posible que se activen alertas

Se pueden activar alertas cuando los servicios se inician y se detienen y cuando el sistema StorageGRID está funcionando como un entorno de versión mixta (algunos nodos de la red ejecutan una versión anterior, mientras que otros se han actualizado a una versión posterior).  Es posible que se activen otras alertas después de completarse la actualización.

Por ejemplo, es posible que vea la alerta *No se puede comunicar con el nodo* cuando se detienen los servicios, o es posible que vea la alerta *Error de comunicación de Cassandra* cuando algunos nodos se han actualizado a StorageGRID 11.9 pero otros nodos aún ejecutan StorageGRID 11.8. En general, estas alertas desaparecerán cuando se complete la actualización.

La alerta *Ubicación ILM inalcanzable* podría activarse cuando los nodos de almacenamiento se detienen durante la actualización a StorageGRID 11.9. Esta alerta podría persistir durante 1 día después de que se complete la actualización.

Una vez completada la actualización, puede revisar las alertas relacionadas con la actualización seleccionando *Alertas resueltas recientemente* o *Alertas actuales* en el panel de Grid Manager.



== Se generan muchas notificaciones SNMP

Tenga en cuenta que se puede generar una gran cantidad de notificaciones SNMP cuando los nodos de la red se detienen y reinician durante la actualización.  Para evitar notificaciones excesivas, desmarque la casilla de verificación *Habilitar notificaciones del agente SNMP* (*CONFIGURACIÓN* > *Monitoreo* > *Agente SNMP*) para deshabilitar las notificaciones SNMP antes de comenzar la actualización.  Luego, vuelva a habilitar las notificaciones una vez completada la actualización.



== Los cambios de configuración están restringidos


NOTE: Esta lista se aplica específicamente a las actualizaciones de StorageGRID 11.8 a StorageGRID 11.9. Si está actualizando a otra versión de StorageGRID , consulte la lista de cambios restringidos en las instrucciones de actualización para esa versión.

Hasta que se complete la tarea *Habilitar nueva función*:

* No realice ningún cambio en la configuración de la cuadrícula.
* No habilite ni deshabilite ninguna función nueva.
* No actualice la configuración de ILM.  De lo contrario, podría experimentar un comportamiento ILM inconsistente e inesperado.
* No aplique una revisión ni recupere un nodo de la cuadrícula.
+

NOTE: Comuníquese con el soporte técnico si necesita recuperar un nodo durante la actualización.

* No debe administrar grupos de alta disponibilidad, interfaces VLAN ni puntos finales del equilibrador de carga mientras actualiza a StorageGRID 11.9.
* No elimine ningún grupo de alta disponibilidad hasta que se complete la actualización a StorageGRID 11.9. Las direcciones IP virtuales en otros grupos de HA podrían volverse inaccesibles.


Hasta que se complete la tarea *Pasos finales de actualización*:

* No realice un procedimiento de expansión.
* No realice un procedimiento de desmantelamiento.




== No puedes ver los detalles de los depósitos ni administrarlos desde el Administrador de inquilinos

Durante la actualización a StorageGRID 11.9 (es decir, mientras el sistema funciona como un entorno de versión mixta), no puede ver los detalles de los depósitos ni administrarlos mediante el Administrador de inquilinos.  Uno de los siguientes errores aparece en la página Depósitos del Administrador de inquilinos:

* No puedes usar esta API mientras estás actualizando a 11.9.
* No puedes ver los detalles de las versiones del depósito en el Administrador de inquilinos mientras actualizas a 11.9.


Este error se resolverá una vez que se complete la actualización a 11.9.

.Solución alternativa
Mientras la actualización 11.9 está en progreso, use las siguientes herramientas para ver los detalles de los depósitos o administrarlos, en lugar de usar el Administrador de inquilinos:

* Para realizar operaciones S3 estándar en un bucket, utilice ellink:../s3/operations-on-buckets.html["API REST de S3"] o ellink:../tenant/understanding-tenant-management-api.html["API de gestión de inquilinos"] .
* Para realizar operaciones personalizadas de StorageGRID en un depósito (por ejemplo, ver y modificar la consistencia del depósito, habilitar o deshabilitar actualizaciones del último tiempo de acceso o configurar la integración de búsqueda), utilice la API de administración de inquilinos.

