---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: Algunas características y capacidades fueron eliminadas o quedaron obsoletas en esta versión.  Revise estos elementos para comprender si necesita actualizar las aplicaciones cliente o modificar su configuración antes de actualizar. 
---
= Funciones y capacidades eliminadas o en desuso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunas características y capacidades fueron eliminadas o quedaron obsoletas en esta versión.  Revise estos elementos para comprender si necesita actualizar las aplicaciones cliente o modificar su configuración antes de actualizar.



== Definiciones

Obsoleto:: Esta función *no debería* utilizarse en nuevos entornos de producción.  Los entornos de producción existentes pueden seguir utilizando la función.
Fin de la vida:: Última versión enviada que admite la función.  En algunos casos, es posible que se elimine la documentación de la función en esta etapa.
Remoto:: Primera versión que *no* admite la función.




== Fin del soporte de funciones de StorageGRID

Las funciones obsoletas se eliminarán en N+2 versiones principales.  Por ejemplo, si una característica queda obsoleta en la versión N (por ejemplo, 6.3), la última versión donde existirá dicha característica será N+1 (por ejemplo, 6.4).  La versión N+2 (por ejemplo, 6.5) es el primer lanzamiento cuando la función no existe en el producto.

Ver el https://mysupport.netapp.com/site/info/version-support["Página de soporte de versiones de software"^] Para obtener información adicional.


NOTE: En determinadas situaciones, NetApp podría finalizar el soporte para funciones específicas antes de lo indicado.

[cols="2a,1a,1a,1a,3a"]
|===
| Característica | Obsoleto | Fin de la vida | Remoto | Enlaces a documentación anterior 


 a| 
Alarmas heredadas (no alertas)
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["Referencia de alarmas (StorageGRID 11.8)"^]



 a| 
Compatibilidad con nodos de archivo
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["Consideraciones para el desmantelamiento de nodos de archivo (StorageGRID 11.8)"^]

*Nota*: Antes de comenzar la actualización, debes:

. Desactivar todos los nodos de archivo. Ver https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["Desmantelamiento de nodos de red (sitio de documentación de StorageGRID 11.8)"^] .
. Eliminar todas las referencias de nodo de archivo de los grupos de almacenamiento y las políticas de ILM. Ver https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["Base de conocimientos de NetApp : Guía de resolución de la actualización del software StorageGRID 11.9"^] .




 a| 
Exportación de auditoría a través de CIFS/Samba
 a| 
11,1
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Servicio CLB
 a| 
11,4
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Motor de contenedores Docker
 a| 
11,8
 a| 
11,9
 a| 
Por determinar
 a| 
La compatibilidad con Docker como motor de contenedores para implementaciones de solo software está obsoleta. Docker será reemplazado por otro motor de contenedores en una versión futura. Consulte lalink:../ubuntu/software-requirements.html#docker-versions-tested["Lista de versiones de Docker compatibles actualmente"] .



 a| 
Exportación de auditoría de NFS
 a| 
11,8
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["Configurar el acceso del cliente de auditoría para NFS (StorageGRID 11.8)"^]



 a| 
Compatibilidad con la API de Swift
 a| 
11,7
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["Utilice la API REST de Swift (StorageGRID 11.8)"^]



 a| 
RHEL 8.8
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9.0
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9.2
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 18,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 20,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Debian 11
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 

|===
Consulte también:

* link:../upgrade/changes-to-grid-management-api.html["Cambios en la API de administración de la red"]
* link:../upgrade/changes-to-tenant-management-api.html["Cambios en la API de administración de inquilinos"]

