---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Antes de comenzar la actualización, verifique que la versión anterior de StorageGRID esté instalada con la última revisión disponible aplicada. 
---
= Verifique la versión instalada de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de comenzar la actualización, verifique que la versión anterior de StorageGRID esté instalada con la última revisión disponible aplicada.

.Acerca de esta tarea
Antes de actualizar a StorageGRID 11.9, su red debe tener instalado StorageGRID 11.8.  Si actualmente está utilizando una versión anterior de StorageGRID, debe instalar todos los archivos de actualización anteriores junto con sus últimas revisiones (muy recomendado) hasta que la versión actual de su red sea StorageGRID 11.8._x.y_.

Una posible ruta de actualización se muestra en la<<example-upgrade-path,ejemplo>> .


CAUTION: NetApp recomienda encarecidamente que aplique la última revisión para cada versión de StorageGRID antes de actualizar a la siguiente versión y que también aplique la última revisión para cada nueva versión que instale. En algunos casos, es necesario aplicar una revisión para evitar el riesgo de pérdida de datos. Ver https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp : StorageGRID"^] y las notas de la versión de cada revisión para obtener más información.

.Pasos
. Sign in en Grid Manager usando unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
. Desde la parte superior del Administrador de cuadrícula, seleccione *Ayuda* > *Acerca de*.
. Verifique que la *Versión* sea 11.8._x.y_.
+
En el número de versión StorageGRID 11.8._x.y_:

+
** La *versión principal* tiene un valor _x_ de 0 (11.8.0).
** Una *hotfix*, si se ha aplicado, tiene un valor _y_ (por ejemplo, 11.8.0.1).


. Si *Versión* no es 11.8._x.y_, vaya a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp : StorageGRID"^] para descargar los archivos de cada versión anterior, incluida la última revisión para cada versión.
. Obtén las instrucciones de actualización para cada versión que hayas descargado.  Luego, realice el procedimiento de actualización de software para esa versión y aplique la última revisión para esa versión (muy recomendado).
+
Ver ellink:../maintain/storagegrid-hotfix-procedure.html["Procedimiento de revisión de StorageGRID"] .





== [[example-upgrade-path]]Ejemplo: Actualizar a StorageGRID 11.9 desde la versión 11.6

El siguiente ejemplo muestra los pasos para actualizar de la versión 11.6 de StorageGRID a la versión 11.8 como preparación para una actualización de StorageGRID 11.9.

Descargue e instale el software en la siguiente secuencia para preparar su sistema para la actualización:

. Actualice a la versión principal de StorageGRID 11.6.0.
. Aplique la última revisión StorageGRID 11.6.0._y_.
. Actualice a la versión principal de StorageGRID 11.7.0.
. Aplique la última revisión StorageGRID 11.7.0._y_.
. Actualice a la versión principal de StorageGRID 11.8.0.
. Aplique la última revisión StorageGRID 11.8.0._y_.

