---
permalink: ubuntu/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure Docker storage volume 
summary: Antes de instalar Docker, es posible que deba formatear el volumen de almacenamiento de Docker y montarlo en /var/lib/docker. 
---
= Configurar el volumen de almacenamiento del motor de contenedores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el motor de contenedor (Docker o Podman), es posible que deba formatear el volumen de almacenamiento y montarlo.


NOTE: La compatibilidad con Docker como motor de contenedores para implementaciones de solo software está obsoleta. Docker será reemplazado por otro motor de contenedores en una versión futura.

.Acerca de esta tarea
Puede omitir estos pasos si planea usar almacenamiento local para el volumen de almacenamiento de Docker y tiene suficiente espacio disponible en la partición del host que contiene `/var/lib` .

.Pasos
. Cree un sistema de archivos en el volumen de almacenamiento de Docker:
+
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
. Monte el volumen de almacenamiento de Docker:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
. Agregue una entrada para docker-storage-volume-device a /etc/fstab.
+
Este paso garantiza que el volumen de almacenamiento se volverá a montar automáticamente después de que el host se reinicie.


