---
permalink: ubuntu/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example node configuration files 
summary: Puede utilizar los archivos de configuración de nodo de ejemplo para ayudar a configurar los archivos de configuración de nodo para su sistema StorageGRID .  Los ejemplos muestran archivos de configuración de nodos para todos los tipos de nodos de la red. 
---
= Archivos de configuración de nodos de ejemplo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar los archivos de configuración de nodo de ejemplo para ayudar a configurar los archivos de configuración de nodo para su sistema StorageGRID .  Los ejemplos muestran archivos de configuración de nodos para todos los tipos de nodos de la red.

Para la mayoría de los nodos, puede agregar información de direccionamiento de red de administrador y cliente (IP, máscara, puerta de enlace, etc.) cuando configura la red mediante el Administrador de red o la API de instalación.  La excepción es el nodo de administración principal.  Si desea navegar hasta la IP de la red de administración del nodo de administración principal para completar la configuración de la red (porque la red de red no está enrutada, por ejemplo), debe configurar la conexión de la red de administración para el nodo de administración principal en su archivo de configuración de nodo.  Esto se muestra en el ejemplo.


NOTE: En los ejemplos, el objetivo Red de cliente se ha configurado como una práctica recomendada, aunque la Red de cliente está deshabilitada de forma predeterminada.



== Ejemplo de nodo de administración principal

*Nombre de archivo de ejemplo*: `/etc/storagegrid/nodes/dc1-adm1.conf`

*Contenido del archivo de ejemplo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Ejemplo de nodo de almacenamiento

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-sn1.conf`

*Contenido del archivo de ejemplo:*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Ejemplo de nodo de puerta de enlace

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-gw1.conf`

*Contenido del archivo de ejemplo:*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Ejemplo de un nodo de administración no principal

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-adm2.conf`

*Contenido del archivo de ejemplo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----