---
permalink: ubuntu/example-etc-network-interfaces.html 
sidebar: sidebar 
keywords: example etc network interfaces 
summary: El archivo /etc/network/interfaces incluye tres secciones, que definen las interfaces físicas, la interfaz de enlace y las interfaces VLAN.  Puede combinar las tres secciones de ejemplo en un solo archivo, que agregará cuatro interfaces físicas de Linux en un solo enlace LACP y luego establecerá tres interfaces VLAN que sustentan el enlace para su uso como interfaces de red de cliente, administrador y red de StorageGRID . 
---
= Ejemplo /etc/network/interfaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El `/etc/network/interfaces` El archivo incluye tres secciones, que definen las interfaces físicas, la interfaz de enlace y las interfaces VLAN.  Puede combinar las tres secciones de ejemplo en un solo archivo, que agregará cuatro interfaces físicas de Linux en un solo enlace LACP y luego establecerá tres interfaces VLAN que sustentan el enlace para su uso como interfaces de red de cliente, administrador y red de StorageGRID .



== Interfaces físicas

Tenga en cuenta que los conmutadores en los otros extremos de los enlaces también deben tratar los cuatro puertos como un único canal troncal o puerto LACP y deben pasar al menos las tres VLAN referenciadas con etiquetas.

[listing]
----
# loopback interface
auto lo
iface lo inet loopback

# ens160 interface
auto ens160
iface ens160 inet manual
    bond-master bond0
    bond-primary en160

# ens192 interface
auto ens192
iface ens192 inet manual
    bond-master bond0

# ens224 interface
auto ens224
iface ens224 inet manual
    bond-master bond0

# ens256 interface
auto ens256
iface ens256 inet manual
    bond-master bond0
----


== Interfaz de enlace

[listing]
----
# bond0 interface
auto bond0
iface bond0 inet manual
    bond-mode 4
    bond-miimon 100
    bond-slaves ens160 ens192 end224 ens256
----


== Interfaces VLAN

[listing]
----
# 1001 vlan
auto bond0.1001
iface bond0.1001 inet manual
vlan-raw-device bond0

# 1002 vlan
auto bond0.1002
iface bond0.1002 inet manual
vlan-raw-device bond0

# 1003 vlan
auto bond0.1003
iface bond0.1003 inet manual
vlan-raw-device bond0
----