---
permalink: harden/other-hardening-guidelines.html 
sidebar: sidebar 
keywords: Hardening guidelines, security 
summary: Además de seguir las pautas de fortalecimiento para las redes y los nodos de StorageGRID , debe seguir las pautas de fortalecimiento para otras áreas del sistema StorageGRID . 
---
= Otras pautas de endurecimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Además de seguir las pautas de fortalecimiento para las redes y los nodos de StorageGRID , debe seguir las pautas de fortalecimiento para otras áreas del sistema StorageGRID .



== Contraseña de instalación temporal

Para proteger el sistema StorageGRID durante la instalación, configure una contraseña en la página de contraseña del instalador temporal en la interfaz de usuario de instalación de StorageGRID o en la API de instalación.  Cuando se configura, esta contraseña se aplica a todos los métodos para instalar StorageGRID, incluida la interfaz de usuario, la API de instalación y `configure-storagegrid.py` guion.

Para obtener más información, consulte:

* link:../rhel/index.html["Instalar StorageGRID en Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Instalar StorageGRID en Ubuntu o Debian"]
* link:../vmware/index.html["Instalar StorageGRID en VMware"]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["Instalar el dispositivo StorageGRID"^]




== Registros y mensajes de auditoría

Proteja siempre los registros de StorageGRID y la salida de mensajes de auditoría de manera segura.  Los registros y mensajes de auditoría de StorageGRID proporcionan información invaluable desde el punto de vista de soporte y disponibilidad del sistema.  Además, la información y los detalles contenidos en los registros de StorageGRID y en los mensajes de auditoría resultantes generalmente son de naturaleza confidencial.

Configure StorageGRID para enviar eventos de seguridad a un servidor syslog externo.  Si utiliza la exportación de syslog, seleccione TLS y RELP/TLS para los protocolos de transporte.

Ver ellink:../monitor/logs-files-reference.html["Referencia de archivos de registro"] para obtener más información sobre los registros de StorageGRID .  Verlink:../audit/audit-messages-main.html["Mensajes de auditoría"] para obtener más información sobre los mensajes de auditoría de StorageGRID .



== AutoSupport de NetApp

La función AutoSupport de StorageGRID le permite monitorear de manera proactiva el estado de su sistema y enviar paquetes automáticamente al sitio de soporte de NetApp , al equipo de soporte interno de su organización o a un socio de soporte.  De forma predeterminada, el envío de paquetes de AutoSupport a NetApp está habilitado cuando StorageGRID se configura por primera vez.

La función AutoSupport se puede desactivar.  Sin embargo, NetApp recomienda habilitarlo porque AutoSupport ayuda a acelerar la identificación y resolución de problemas en caso de que surja un problema en su sistema StorageGRID .

AutoSupport admite HTTPS, HTTP y SMTP como protocolos de transporte.  Debido a la naturaleza sensible de los paquetes de AutoSupport , NetApp recomienda enfáticamente utilizar HTTPS como protocolo de transporte predeterminado para enviar paquetes de AutoSupport a NetApp.



== Intercambio de recursos entre orígenes (CORS)

Puede configurar el uso compartido de recursos de origen cruzado (CORS) para un bucket S3 si desea que ese bucket y los objetos que contiene sean accesibles para las aplicaciones web en otros dominios.  En general, no habilite CORS a menos que sea necesario.  Si se requiere CORS, limítelo a orígenes confiables.

Vea los pasos paralink:../tenant/configuring-cross-origin-resource-sharing-cors.html["Configuración del uso compartido de recursos entre orígenes (CORS)"] .



== Dispositivos de seguridad externos

Una solución de fortalecimiento completa debe abordar los mecanismos de seguridad fuera de StorageGRID.  El uso de dispositivos de infraestructura adicionales para filtrar y limitar el acceso a StorageGRID es una forma eficaz de establecer y mantener una postura de seguridad estricta.  Estos dispositivos de seguridad externos incluyen firewalls, sistemas de prevención de intrusiones (IPS) y otros dispositivos de seguridad.

Se recomienda un balanceador de carga de terceros para el tráfico de clientes que no son confiables.  El equilibrio de carga de terceros ofrece más control y capas adicionales de protección contra ataques.



== Mitigación de ransomware

Ayude a proteger los datos de sus objetos de los ataques de ransomware siguiendo las recomendaciones en https://www.netapp.com/media/69498-tr-4921.pdf["Defensa contra ransomware con StorageGRID"^] .
