---
permalink: network/admin-network-requirements.html 
sidebar: sidebar 
keywords: admin network requirements, guidelines for admin network, aesl 
summary: La red de administración es opcional.  Si planea configurar una red de administración, siga estos requisitos y pautas. 
---
= Requisitos de la red de administración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La red de administración es opcional.  Si planea configurar una red de administración, siga estos requisitos y pautas.

Los usos típicos de la red de administración incluyen conexiones de gestión, AutoSupport, KMS y conexiones a servidores críticos como NTP, DNS y LDAP si estas conexiones no se proporcionan a través de la red Grid o la red del cliente.


NOTE: La red de administración y AESL pueden ser únicos para cada nodo, siempre que se pueda acceder a los servicios de red y clientes deseados.


NOTE: Debe definir al menos una subred en la red de administración para habilitar conexiones entrantes desde subredes externas.  Las rutas estáticas se generan automáticamente en cada nodo para cada subred en el AESL.
