---
permalink: network/grid-network-requirements.html 
sidebar: sidebar 
keywords: grid network requirements 
summary: Siga estos requisitos y pautas para la red Grid. 
---
= Requisitos de la red Grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos requisitos y pautas para la red Grid.

* En el momento de la implementación, cada nodo de la red debe estar conectado a la red de la red y debe poder comunicarse con el nodo de administración principal mediante la configuración de red que especifique al implementar el nodo.
* Durante las operaciones normales de la red, cada nodo de la red debe poder comunicarse con todos los demás nodos de la red a través de la red.
+

NOTE: La red Grid debe ser directamente enrutable entre cada nodo.  No se admite la traducción de direcciones de red (NAT) entre nodos.

* Si la red de cuadrícula consta de varias subredes, agréguelas a la Lista de subredes de la red de cuadrícula (GNSL).  Se crean rutas estáticas en todos los nodos para cada subred en GNSL.

