---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications, port 
summary: 'El firewall interno de StorageGRID solo permite conexiones entrantes a puertos específicos en la red Grid, con excepción de los puertos 22, 80, 123 y 443 (consulte la información sobre comunicaciones externas).  También se aceptan conexiones en los puertos definidos por los puntos finales del balanceador de carga.' 
---
= Comunicaciones internas de los nodos de la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El firewall interno de StorageGRID permite conexiones entrantes a puertos específicos en la red Grid.  También se aceptan conexiones en los puertos definidos por los puntos finales del balanceador de carga.


NOTE: NetApp recomienda que habilite el tráfico del Protocolo de mensajes de control de Internet (ICMP) entre los nodos de la red.  Permitir el tráfico ICMP puede mejorar el rendimiento de la conmutación por error cuando no se puede acceder a un nodo de la red.

Además de ICMP y los puertos enumerados en la tabla, StorageGRID utiliza el Protocolo de redundancia de enrutador virtual (VRRP).  VRRP es un protocolo de Internet que utiliza el protocolo IP número 112.  StorageGRID utiliza VRRP únicamente en modo de unidifusión.  VRRP solo se requiere silink:../admin/managing-high-availability-groups.html["grupos de alta disponibilidad"] están configurados.



== Directrices para nodos basados en Linux

Si las políticas de red empresarial restringen el acceso a cualquiera de estos puertos, puede reasignar los puertos en el momento de la implementación utilizando un parámetro de configuración de implementación. Para obtener más información sobre la reasignación de puertos y los parámetros de configuración de implementación, consulte:

* link:../rhel/index.html["Instalar StorageGRID en Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Instalar StorageGRID en Ubuntu o Debian"]




== Directrices para nodos basados en VMware

Configure los siguientes puertos solo si necesita definir restricciones de firewall que sean externas a la red de VMware.

Si las políticas de red empresarial restringen el acceso a cualquiera de estos puertos, puede reasignar los puertos cuando implemente nodos mediante VMware vSphere Web Client o mediante una configuración de archivo al automatizar la implementación de nodos de la red. Para obtener más información sobre la reasignación de puertos y los parámetros de configuración de implementación, consultelink:../vmware/index.html["Instalar StorageGRID en VMware"] .



== Directrices para los nodos de dispositivos

Si las políticas de red empresarial restringen el acceso a cualquiera de estos puertos, puede reasignar los puertos mediante el instalador del dispositivo StorageGRID . Ver https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["Opcional: Reasignar los puertos de red para el dispositivo"^] .



== Puertos internos de StorageGRID

[cols="1a,1a,1a,1a,4a"]
|===
| Puerto | TCP o UDP | De | A | Detalles 


 a| 
22
 a| 
TCP
 a| 
Nodo de administración principal
 a| 
Todos los nodos
 a| 
Para los procedimientos de mantenimiento, el nodo de administración principal debe poder comunicarse con todos los demás nodos mediante SSH en el puerto 22.  Permitir el tráfico SSH desde otros nodos es opcional.



 a| 
80
 a| 
TCP
 a| 
Accesorios
 a| 
Nodo de administración principal
 a| 
Los dispositivos StorageGRID lo utilizan para comunicarse con el nodo de administración principal para iniciar la instalación.



 a| 
123
 a| 
UDP
 a| 
Todos los nodos
 a| 
Todos los nodos
 a| 
Servicio de protocolo de tiempo de red.  Cada nodo sincroniza su hora con la de todos los demás nodos mediante NTP.



 a| 
443
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Se utiliza para comunicar el estado al nodo de administración principal durante la instalación y otros procedimientos de mantenimiento.



 a| 
1055
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Tráfico interno para instalación, ampliación, recuperación y otros procedimientos de mantenimiento.



 a| 
1139
 a| 
TCP
 a| 
Nodos de almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno entre nodos de almacenamiento.



 a| 
1501
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de almacenamiento con ADC
 a| 
Informes, auditoría y configuración de tráfico interno.



 a| 
1502
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno relacionado con S3 y Swift.



 a| 
1504
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de administración
 a| 
Servicio NMS de informes y configuración de tráfico interno.



 a| 
1505
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de administración
 a| 
Tráfico interno del servicio AMS.



 a| 
1506
 a| 
TCP
 a| 
Todos los nodos
 a| 
Todos los nodos
 a| 
Estado del servidor tráfico interno.



 a| 
1507
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de puerta de enlace
 a| 
Balanceador de carga de tráfico interno.



 a| 
1508
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Gestión de configuración de tráfico interno.



 a| 
1511
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno de metadatos.



 a| 
7001
 a| 
TCP
 a| 
Nodos de almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Comunicación entre clústeres de nodos TLS de Cassandra.



 a| 
7443
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Tráfico interno para instalación, expansión, recuperación, otros procedimientos de mantenimiento e informes de errores.



 a| 
8011
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Tráfico interno para instalación, ampliación, recuperación y otros procedimientos de mantenimiento.



 a| 
8443
 a| 
TCP
 a| 
Nodo de administración principal
 a| 
Nodos de dispositivos
 a| 
Tráfico interno relacionado con el procedimiento del modo de mantenimiento.



 a| 
9042
 a| 
TCP
 a| 
Nodos de almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Puerto de cliente Cassandra.



 a| 
9999
 a| 
TCP
 a| 
Todos los nodos
 a| 
Todos los nodos
 a| 
Tráfico interno para múltiples servicios.  Incluye procedimientos de mantenimiento, métricas y actualizaciones de red.



 a| 
10226
 a| 
TCP
 a| 
Nodos de almacenamiento
 a| 
Nodo de administración principal
 a| 
Utilizado por los dispositivos StorageGRID para reenviar paquetes de AutoSupport desde E-Series SANtricity System Manager al nodo de administración principal.



 a| 
10342
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodo de administración principal
 a| 
Tráfico interno para instalación, ampliación, recuperación y otros procedimientos de mantenimiento.



 a| 
18000
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento con ADC
 a| 
Tráfico interno del servicio de cuentas.



 a| 
18001
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento con ADC
 a| 
Tráfico interno de la Federación de Identidad.



 a| 
18002
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Tráfico de API interna relacionado con protocolos de objetos.



 a| 
18003
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento con ADC
 a| 
La plataforma atiende el tráfico interno.



 a| 
18017
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno del servicio Data Mover para grupos de almacenamiento en la nube.



 a| 
18019
 a| 
TCP
 a| 
Nodos de almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Servicio de fragmentos de tráfico interno para codificación de borrado.



 a| 
18082
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno relacionado con S3.



 a| 
18083
 a| 
TCP
 a| 
Todos los nodos
 a| 
Nodos de almacenamiento
 a| 
Tráfico interno relacionado con Swift.



 a| 
18086
 a| 
TCP
 a| 
Todos los nodos de la red
 a| 
Todos los nodos de almacenamiento
 a| 
Tráfico interno relacionado con el servicio LDR.



 a| 
18200
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento
 a| 
Estadísticas adicionales sobre solicitudes de clientes.



 a| 
19000
 a| 
TCP
 a| 
Nodos de administración/almacenamiento
 a| 
Nodos de almacenamiento con ADC
 a| 
Tráfico interno del servicio Keystone .

|===
.Información relacionada
link:external-communications.html["Comunicaciones externas"]
