---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: Siga los requisitos para cada tipo de red StorageGRID . 
---
= Requisitos específicos de la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga los requisitos para cada tipo de red StorageGRID .



== Puertas de enlace y enrutadores de red

* Si se configura, la puerta de enlace para una red determinada debe estar dentro de la subred de la red específica.
* Si configura una interfaz utilizando direccionamiento estático, debe especificar una dirección de puerta de enlace distinta de 0.0.0.0.
* Si no tiene una puerta de enlace, la mejor práctica es configurar la dirección de la puerta de enlace para que sea la dirección IP de la interfaz de red.




== Subredes


NOTE: Cada red debe estar conectada a su propia subred que no se superponga con ninguna otra red en el nodo.

El administrador de cuadrícula aplica las siguientes restricciones durante la implementación.  Se proporcionan aquí para ayudar en la planificación de la red previa a la implementación.

* La máscara de subred para cualquier dirección IP de red no puede ser 255.255.255.254 o 255.255.255.255 (/31 o /32 en notación CIDR).
* La subred definida por una dirección IP de interfaz de red y una máscara de subred (CIDR) no puede superponerse a la subred de ninguna otra interfaz configurada en el mismo nodo.
* No utilice subredes que contengan las siguientes direcciones IPv4 para la red de cuadrícula, la red de administración o la red de cliente de ningún nodo:
+
** 192.168.130.101
** 192.168.131.101
** 192.168.130.102
** 192.168.131.102
** 198.51.100.2
** 198.51.100.4


+
Por ejemplo, no utilice los siguientes rangos de subred para la red de cuadrícula, la red de administración o la red de cliente de ningún nodo:

+
** 192.168.130.0/24 porque este rango de subred contiene las direcciones IP 192.168.130.101 y 192.168.130.102
** 192.168.131.0/24 porque este rango de subred contiene las direcciones IP 192.168.131.101 y 192.168.131.102
** 198.51.100.0/24 porque este rango de subred contiene las direcciones IP 198.51.100.2 y 198.51.100.4


* La subred de la red Grid para cada nodo debe incluirse en el GNSL.
* La subred de red de administración no puede superponerse a la subred de red de cuadrícula, a la subred de red de cliente ni a ninguna subred en GNSL.
* Las subredes del AESL no pueden superponerse con ninguna subred del GNSL.
* La subred de la red del cliente no puede superponerse a la subred de la red de cuadrícula, a la subred de la red de administración, a ninguna subred de GNSL ni a ninguna subred de AESL.




== Red de cuadrícula

* En el momento de la implementación, cada nodo de la red debe estar conectado a la red de la red y debe poder comunicarse con el nodo de administración principal mediante la configuración de red que especifique al implementar el nodo.
* Durante las operaciones normales de la red, cada nodo de la red debe poder comunicarse con todos los demás nodos de la red a través de la red.
+

NOTE: La red Grid debe ser directamente enrutable entre cada nodo.  No se admite la traducción de direcciones de red (NAT) entre nodos.

* Si la red de cuadrícula consta de varias subredes, agréguelas a la Lista de subredes de la red de cuadrícula (GNSL).  Se crean rutas estáticas en todos los nodos para cada subred en GNSL.
* Si la interfaz de red de cuadrícula está configurada como troncal para admitir interfaces VLAN, la VLAN nativa del troncal debe ser la VLAN utilizada para el tráfico de red de cuadrícula.  Todos los nodos de la red deben ser accesibles a través de la VLAN nativa troncal.




== Red de administración

La red de administración es opcional.  Si planea configurar una red de administración, siga estos requisitos y pautas.

Los usos típicos de la red de administración incluyen conexiones de gestión, AutoSupport, KMS y conexiones a servidores críticos como NTP, DNS y LDAP si estas conexiones no se proporcionan a través de la red Grid o la red del cliente.


NOTE: La red de administración y AESL pueden ser únicos para cada nodo, siempre que se pueda acceder a los servicios de red y clientes deseados.


NOTE: Debe definir al menos una subred en la red de administración para habilitar conexiones entrantes desde subredes externas.  Las rutas estáticas se generan automáticamente en cada nodo para cada subred en el AESL.



== Red de clientes

La red de clientes es opcional.  Si planea configurar una red de cliente, tenga en cuenta las siguientes consideraciones.

* La red de clientes está diseñada para soportar el tráfico de los clientes S3.  Si se configura, la puerta de enlace de la red del cliente se convierte en la puerta de enlace predeterminada del nodo.
* Si usa una red de cliente, puede ayudar a proteger StorageGRID de ataques hostiles al aceptar tráfico de cliente entrante solo en puntos finales del balanceador de carga configurados explícitamente. Ver link:../admin/configuring-load-balancer-endpoints.html["Configurar los puntos finales del balanceador de carga"] .
* Si la interfaz de red del cliente está configurada como un enlace troncal para admitir interfaces VLAN, considere si es necesario configurar la interfaz de red del cliente (eth2).  Si está configurado, el tráfico de la red del cliente fluirá a través de la VLAN nativa del tronco, tal como se configuró en el conmutador.


.Información relacionada
link:../maintain/changing-nodes-network-configuration.html["Cambiar la configuración de la red del nodo"]
