---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: Puede utilizar el Administrador de inquilinos para crear depósitos S3 para datos de objetos. 
---
= Crear un bucket S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el Administrador de inquilinos para crear depósitos S3 para datos de objetos.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Pertenece a un grupo de usuarios que tiene acceso de root o administra todos los bucketslink:tenant-management-permissions.html["permiso"] . Estos permisos anulan la configuración de permisos en las políticas de grupo o de depósito.
+

NOTE: Los permisos para establecer o modificar las propiedades de bloqueo de objetos S3 de depósitos u objetos se pueden otorgar mediantelink:../s3/bucket-and-group-access-policies.html["política de cubos o política de grupo"] .

* Si planea habilitar el Bloqueo de objetos S3 para un depósito, un administrador de la red ha habilitado la configuración global de Bloqueo de objetos S3 para el sistema StorageGRID y usted ha revisado los requisitos para los depósitos y objetos de Bloqueo de objetos S3.
* Si cada inquilino tendrá 5000 depósitos, cada nodo de almacenamiento en la red tendrá un mínimo de 64 GB de RAM.
+

NOTE: Cada cuadrícula puede tener un máximo de 100.000 contenedores.





== Acceder al asistente

.Pasos
. Seleccione *Ver depósitos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Depósitos*.
. Seleccione *Crear depósito*.




== Introducir detalles

.Pasos
. Introduzca detalles para el depósito.
+
[cols="1a,3a"]
|===
| Campo | Descripción 


 a| 
Nombre del depósito
 a| 
Un nombre para el depósito que cumple con estas reglas:

** Debe ser único en cada sistema StorageGRID (no solo único dentro de la cuenta del inquilino).
** Debe ser compatible con DNS.
** Debe contener al menos 3 y no más de 63 caracteres.
** Cada etiqueta debe comenzar y terminar con una letra minúscula o un número y solo puede utilizar letras minúsculas, números y guiones.
** No debe contener puntos en las solicitudes de estilo alojado virtualmente.  Los períodos causarán problemas con la verificación del certificado comodín del servidor.


Para obtener más información, consulte la https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Documentación de Amazon Web Services (AWS) sobre las reglas de nombres de bucket"^] .

*Nota*: No puedes cambiar el nombre del depósito después de crearlo.



 a| 
Región
 a| 
La región del cubo.

Su administrador de StorageGRID administra las regiones disponibles. La región de un depósito puede afectar la política de protección de datos aplicada a los objetos. De forma predeterminada, todos los depósitos se crean en el `us-east-1` región.

*Nota*: No puedes cambiar la región después de crear el depósito.

|===
. Seleccione *Continuar*.




== Administrar configuraciones

.Pasos
. De manera opcional, habilite el control de versiones de objetos para el depósito.
+
Habilite el control de versiones de objetos si desea almacenar todas las versiones de cada objeto en este depósito.  Luego puede recuperar versiones anteriores de un objeto según sea necesario.  Debe habilitar el control de versiones de objetos si el depósito se utilizará para la replicación entre redes.

. Si la configuración global de Bloqueo de objetos S3 está habilitada, habilite opcionalmente el Bloqueo de objetos S3 para que el depósito almacene objetos utilizando un modelo de escritura única, lectura múltiple (WORM).
+
Habilite el bloqueo de objetos S3 para un depósito solo si necesita conservar objetos durante un período de tiempo fijo, por ejemplo, para cumplir con ciertos requisitos reglamentarios. El bloqueo de objetos S3 es una configuración permanente que le ayuda a evitar que los objetos se eliminen o sobrescriban durante un período de tiempo fijo o de manera indefinida.

+

CAUTION: Una vez habilitada la configuración de bloqueo de objetos S3 para un depósito, no se puede deshabilitar. Cualquier persona con los permisos correctos puede agregar objetos a este depósito que no se pueden modificar.  Es posible que no puedas eliminar estos objetos ni el depósito en sí.

+
Si habilita el Bloqueo de objetos S3 para un depósito, el control de versiones del depósito se habilita automáticamente.

. Si seleccionó *Habilitar bloqueo de objetos S3*, habilite opcionalmente la *Retención predeterminada* para este depósito.
+

NOTE: Su administrador de red debe darle permiso paralink:../tenant/using-s3-object-lock.html["Utilice funciones específicas de S3 Object Lock"] .

+
Cuando la *Retención predeterminada* está habilitada, los objetos nuevos agregados al depósito estarán automáticamente protegidos contra eliminación o sobrescritura. La configuración *Retención predeterminada* no se aplica a los objetos que tienen sus propios períodos de retención.

+
.. Si la *Retención predeterminada* está habilitada, especifique un *Modo de retención predeterminado* para el depósito.
+
[cols="1a,2a"]
|===
| Modo de retención predeterminado | Descripción 


 a| 
Gobernancia
 a| 
*** Usuarios con la `s3:BypassGovernanceRetention` El permiso puede utilizar el `x-amz-bypass-governance-retention: true` encabezado de solicitud para omitir la configuración de retención.
*** Estos usuarios pueden eliminar una versión de un objeto antes de que se alcance su fecha de conservación.
*** Estos usuarios pueden aumentar, disminuir o eliminar la fecha de conservación de un objeto.




 a| 
Cumplimiento
 a| 
*** El objeto no se puede eliminar hasta que se alcance su fecha de conservación.
*** La fecha de conservación del objeto se puede aumentar, pero no se puede disminuir.
*** La fecha de retención del objeto no se puede eliminar hasta que se alcance esa fecha.


*Nota*: El administrador de su red debe permitirle utilizar el modo de cumplimiento.

|===
.. Si la *Retención predeterminada* está habilitada, especifique el *Período de retención predeterminado* para el depósito.
+
El *Período de retención predeterminado* indica durante cuánto tiempo se deben conservar los objetos nuevos agregados a este depósito, a partir del momento en que se ingieren. Especifique un valor que sea menor o igual al período de retención máximo para el inquilino, según lo establecido por el administrador de la red.

+
Se establece un período de retención _máximo_, que puede tener un valor de entre 1 día y 100 años, cuando el administrador de la red crea el inquilino.  Cuando se establece un período de retención _predeterminado_, no puede exceder el valor establecido para el período de retención máximo.  Si es necesario, solicite al administrador de su red que aumente o disminuya el período máximo de retención.



. [[limite-de-capacidad]]Opcionalmente, seleccione *Habilitar límite de capacidad*.
+
El límite de capacidad es la capacidad máxima disponible para los objetos de este bucket. Este valor representa una cantidad lógica (tamaño del objeto), no una cantidad física (tamaño en disco).

+
Si no se establece ningún límite, la capacidad de este depósito es ilimitada. Consulte link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["Uso del límite de capacidad"] Para más información.

. Seleccione *Crear depósito*.
+
El depósito se crea y se agrega a la tabla en la página Depósitos.

. Opcionalmente, seleccione *Ir a la página de detalles del depósito* paralink:viewing-s3-bucket-details.html["ver detalles del depósito"] y realizar una configuración adicional.

