---
permalink: tenant/creating-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to create platform services endpoint 
summary: Debe crear al menos un punto final del tipo correcto antes de poder habilitar un servicio de plataforma. 
---
= Crear punto final de servicios de plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear al menos un punto final del tipo correcto antes de poder habilitar un servicio de plataforma.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Un administrador de StorageGRID habilitó los servicios de plataforma para su cuenta de inquilino.
* Perteneces a un grupo de usuarios que tiene lalink:tenant-management-permissions.html["Administrar puntos finales o permisos de acceso raíz"] .
* Se han creado los recursos a los que hace referencia el punto final de servicios de la plataforma:
+
** Replicación de CloudMirror: depósito S3
** Notificación de eventos: Amazon Simple Notification Service (Amazon SNS) o tema de Kafka
** Notificación de búsqueda: índice de Elasticsearch, si el clúster de destino no está configurado para crear índices automáticamente.


* Tienes la información sobre el recurso de destino:
+
** Host y puerto para el Identificador uniforme de recursos (URI)
+

NOTE: Si planea utilizar un depósito alojado en un sistema StorageGRID como punto final para la replicación de CloudMirror, comuníquese con el administrador de la red para determinar los valores que debe ingresar.

** Nombre único de recurso (URN)
+
link:specifying-urn-for-platform-services-endpoint.html["Especificar URN para el punto final de los servicios de la plataforma"]

** Credenciales de autenticación (si es necesario):
+
[role="tabbed-block"]
====
.Puntos finales de integración de búsqueda
--
Para los puntos finales de integración de búsqueda, puede utilizar las siguientes credenciales:

*** Clave de acceso: ID de clave de acceso y clave de acceso secreta
*** HTTP básico: Nombre de usuario y contraseña


--
.Puntos finales de replicación de CloudMirror
--
Para los puntos finales de replicación de CloudMirror, puede utilizar las siguientes credenciales:

*** Clave de acceso: ID de clave de acceso y clave de acceso secreta
*** CAP (Portal de acceso C2S): URL de credenciales temporales, certificados de servidor y cliente, claves de cliente y una frase de contraseña de clave privada de cliente opcional.


--
.Puntos finales de Amazon SNS
--
Para los puntos finales de Amazon SNS, puede utilizar las siguientes credenciales:

*** Clave de acceso: ID de clave de acceso y clave de acceso secreta


--
.Puntos finales de Kafka
--
Para los puntos finales de Kafka, puede utilizar las siguientes credenciales:

*** SASL/PLAIN: Nombre de usuario y contraseña
*** SASL/SCRAM-SHA-256: Nombre de usuario y contraseña
*** SASL/SCRAM-SHA-512: Nombre de usuario y contraseña


--
====
** Certificado de seguridad (si se utiliza un certificado CA personalizado)


* Si las funciones de seguridad de Elasticsearch están habilitadas, tiene el privilegio de clúster de monitorización para realizar pruebas de conectividad y el privilegio de escritura de índice o los privilegios de índice y eliminación de índice para las actualizaciones de documentos.


.Pasos
. Seleccione *ALMACENAMIENTO (S3)* > *Puntos finales de servicios de plataforma*.  Aparece la página de puntos finales de servicios de la plataforma.
. Seleccione *Crear punto final*.
. Ingrese un nombre para mostrar para describir brevemente el punto final y su propósito.
+
El tipo de servicio de plataforma que admite el punto final se muestra junto al nombre del punto final cuando aparece en la página Puntos finales, por lo que no es necesario incluir esa información en el nombre.

. En el campo *URI*, especifique el Identificador único de recurso (URI) del punto final.
+
--
Utilice uno de los siguientes formatos:

[listing]
----
https://host:port
http://host:port
----
Si no especifica un puerto, se utilizan los siguientes puertos predeterminados:

** Puerto 443 para URI HTTPS y puerto 80 para URI HTTP (la mayoría de los puntos finales)
** Puerto 9092 para HTTPS y URI HTTP (solo puntos finales de Kafka)


--
+
Por ejemplo, el URI de un depósito alojado en StorageGRID podría ser:

+
[listing]
----
https://s3.example.com:10443
----
+
En este ejemplo, `s3.example.com` representa la entrada DNS para la IP virtual (VIP) del grupo de alta disponibilidad (HA) de StorageGRID , y `10443` Representa el puerto definido en el punto final del balanceador de carga.

+

NOTE: Siempre que sea posible, debe conectarse a un grupo de alta disponibilidad de nodos de equilibrio de carga para evitar un único punto de falla.

+
De manera similar, el URI de un bucket alojado en AWS podría ser:

+
[listing]
----
https://s3-aws-region.amazonaws.com
----
+

NOTE: Si el punto final se utiliza para el servicio de replicación CloudMirror, no incluya el nombre del depósito en la URI.  Incluye el nombre del depósito en el campo *URN*.

. Introduzca el nombre de recurso único (URN) para el punto final.
+

NOTE: No se puede cambiar el URN de un punto final una vez creado el punto final.

. Seleccione *Continuar*.
. Seleccione un valor para *Tipo de autenticación*.
+
[role="tabbed-block"]
====
.Puntos finales de integración de búsqueda
--
Ingrese o cargue las credenciales para un punto final de integración de búsqueda.

Las credenciales que proporcione deben tener permisos de escritura para el recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticación | Descripción | Cartas credenciales 


 a| 
Anónimo
 a| 
Proporciona acceso anónimo al destino.  Sólo funciona para puntos finales que tienen la seguridad deshabilitada.
 a| 
Sin autenticación.



 a| 
Tecla de acceso
 a| 
Utiliza credenciales de estilo AWS para autenticar las conexiones con el destino.
 a| 
** ID de clave de acceso
** Clave de acceso secreta




 a| 
HTTP básico
 a| 
Utiliza un nombre de usuario y una contraseña para autenticar las conexiones al destino.
 a| 
** Nombre de usuario
** Password


|===
--
.Puntos finales de replicación de CloudMirror
--
Ingrese o cargue las credenciales para un punto final de replicación de CloudMirror.

Las credenciales que proporcione deben tener permisos de escritura para el recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticación | Descripción | Cartas credenciales 


 a| 
Anónimo
 a| 
Proporciona acceso anónimo al destino.  Sólo funciona para puntos finales que tienen la seguridad deshabilitada.
 a| 
Sin autenticación.



 a| 
Tecla de acceso
 a| 
Utiliza credenciales de estilo AWS para autenticar las conexiones con el destino.
 a| 
** ID de clave de acceso
** Clave de acceso secreta




 a| 
CAP (Portal de acceso C2S)
 a| 
Utiliza certificados y claves para autenticar las conexiones al destino.
 a| 
** URL de credenciales temporales
** Certificado de CA del servidor (carga de archivo PEM)
** Certificado de cliente (carga de archivo PEM)
** Clave privada del cliente (carga de archivo PEM, formato cifrado OpenSSL o formato de clave privada sin cifrar)
** Frase de contraseña de la clave privada del cliente (opcional)


|===
--
.Puntos finales de Amazon SNS
--
Ingrese o cargue las credenciales para un punto final de Amazon SNS.

Las credenciales que proporcione deben tener permisos de escritura para el recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticación | Descripción | Cartas credenciales 


 a| 
Anónimo
 a| 
Proporciona acceso anónimo al destino.  Sólo funciona para puntos finales que tienen la seguridad deshabilitada.
 a| 
Sin autenticación.



 a| 
Tecla de acceso
 a| 
Utiliza credenciales de estilo AWS para autenticar las conexiones con el destino.
 a| 
** ID de clave de acceso
** Clave de acceso secreta


|===
--
.Puntos finales de Kafka
--
Ingrese o cargue las credenciales para un punto final de Kafka.

Las credenciales que proporcione deben tener permisos de escritura para el recurso de destino.

[cols="1a,2a,2a"]
|===
| Tipo de autenticación | Descripción | Cartas credenciales 


 a| 
Anónimo
 a| 
Proporciona acceso anónimo al destino.  Sólo funciona para puntos finales que tienen la seguridad deshabilitada.
 a| 
Sin autenticación.



 a| 
SASL/LLANO
 a| 
Utiliza un nombre de usuario y una contraseña con texto sin formato para autenticar las conexiones al destino.
 a| 
** Nombre de usuario
** Password




 a| 
SASL/SCRAM-SHA-256
 a| 
Utiliza un nombre de usuario y una contraseña mediante un protocolo de desafío-respuesta y hash SHA-256 para autenticar las conexiones al destino.
 a| 
** Nombre de usuario
** Password




 a| 
SASL/SCRAM-SHA-512
 a| 
Utiliza un nombre de usuario y una contraseña mediante un protocolo de desafío-respuesta y hash SHA-512 para autenticar las conexiones al destino.
 a| 
** Nombre de usuario
** Password


|===
Seleccione *Usar autenticación mediante delegación* si el nombre de usuario y la contraseña se derivan de un token de delegación obtenido de un clúster de Kafka.

--
====
. Seleccione *Continuar*.
. Seleccione un botón de opción para *Verificar servidor* para elegir cómo se verifica la conexión TLS al punto final.
+
[cols="1a,2a"]
|===
| Tipo de verificación del certificado | Descripción 


 a| 
Utilice un certificado CA personalizado
 a| 
Utilice un certificado de seguridad personalizado.  Si selecciona esta configuración, copie y pegue el certificado de seguridad personalizado en el cuadro de texto *Certificado CA*.



 a| 
Utilice el certificado CA del sistema operativo
 a| 
Utilice el certificado CA de Grid predeterminado instalado en el sistema operativo para proteger las conexiones.



 a| 
No verificar el certificado
 a| 
El certificado utilizado para la conexión TLS no está verificado.  Esta opción no es segura.

|===
. Seleccione *Probar y crear punto final*.
+
** Aparece un mensaje de éxito si se puede acceder al punto final utilizando las credenciales especificadas.  La conexión al punto final se valida desde un nodo en cada sitio.
** Aparece un mensaje de error si falla la validación del punto final.  Si necesita modificar el punto final para corregir el error, seleccione *Regresar a los detalles del punto final* y actualice la información.  Luego, seleccione *Probar y crear punto final*.
+

NOTE: La creación de puntos finales falla si los servicios de la plataforma no están habilitados para su cuenta de inquilino.  Comuníquese con su administrador de StorageGRID .





Después de haber configurado un punto final, puede usar su URN para configurar un servicio de plataforma.

.Información relacionada
* link:specifying-urn-for-platform-services-endpoint.html["Especificar URN para el punto final de los servicios de la plataforma"]
* link:configuring-cloudmirror-replication.html["Configurar la replicación de CloudMirror"]
* link:configuring-event-notifications.html["Configurar notificaciones de eventos"]
* link:configuring-search-integration-service.html["Configurar el servicio de integración de búsqueda"]

