---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: Si está utilizando un inquilino S3 y tiene los permisos adecuados, puede eliminar las claves de acceso S3 de otro usuario.  Una vez que se elimina una clave de acceso, ya no se puede usar para acceder a los objetos y depósitos en la cuenta del inquilino. 
---
= Eliminar las claves de acceso S3 de otro usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está utilizando un inquilino S3 y tiene los permisos adecuados, puede eliminar las claves de acceso S3 de otro usuario.  Una vez que se elimina una clave de acceso, ya no se puede usar para acceder a los objetos y depósitos en la cuenta del inquilino.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:tenant-management-permissions.html["Permiso de acceso root"] .



CAUTION: Se puede acceder a los depósitos y objetos S3 que pertenecen a un usuario mediante el ID de clave de acceso y la clave de acceso secreta que se muestran para ese usuario en el Administrador de inquilinos.  Por este motivo, proteja las claves de acceso como lo haría con una contraseña.  Rote las claves de acceso periódicamente, elimine las claves no utilizadas de la cuenta y nunca las comparta con otros usuarios.

.Pasos
. Seleccione *GESTIÓN DE ACCESO* > *Usuarios*.
. Desde la página Usuarios, seleccione el usuario cuyas claves de acceso S3 desea administrar.
. Desde la página de detalles del usuario, seleccione *Teclas de acceso* y luego seleccione la casilla de verificación para cada tecla de acceso que desee eliminar.
. Seleccione *Acciones* > *Eliminar clave seleccionada*.
. Desde el cuadro de diálogo de confirmación, seleccione *Eliminar tecla*.
+
Aparece un mensaje de confirmación en la esquina superior derecha de la página.


