---
permalink: tenant/deleting-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete S3 access key 
summary: Si está utilizando un inquilino S3 y tiene el permiso adecuado, puede eliminar sus propias claves de acceso S3.  Una vez que se elimina una clave de acceso, ya no se puede usar para acceder a los objetos y depósitos en la cuenta del inquilino. 
---
= Eliminar sus propias claves de acceso S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está utilizando un inquilino S3 y tiene el permiso adecuado, puede eliminar sus propias claves de acceso S3.  Una vez que se elimina una clave de acceso, ya no se puede usar para acceder a los objetos y depósitos en la cuenta del inquilino.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:tenant-management-permissions.html["Administrar sus propios permisos de credenciales S3"] .



CAUTION: Se puede acceder a los depósitos y objetos S3 que pertenecen a su cuenta mediante el ID de clave de acceso y la clave de acceso secreta que se muestran para su cuenta en el Administrador de inquilinos.  Por este motivo, proteja las claves de acceso como lo haría con una contraseña.  Rote las claves de acceso periódicamente, elimine las claves no utilizadas de su cuenta y nunca las comparta con otros usuarios.

.Pasos
. Seleccione *ALMACENAMIENTO (S3)* > *Mis claves de acceso*.
. Desde la página Mis teclas de acceso, seleccione la casilla de verificación de cada tecla de acceso que desee eliminar.
. Seleccione *Tecla Eliminar*.
. Desde el cuadro de diálogo de confirmación, seleccione *Eliminar tecla*.
+
Aparece un mensaje de confirmación en la esquina superior derecha de la página.


