---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: Puede crear nuevos grupos más rápidamente duplicando un grupo existente. 
---
= Grupo duplicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear nuevos grupos más rápidamente duplicando un grupo existente.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Pertenece a un grupo de usuarios que tiene permiso de acceso Root. Ver link:tenant-management-permissions.html["Permisos de gestión de inquilinos"] .


.Pasos
. Seleccione *GESTIÓN DE ACCESO* > *Grupos*.
. Seleccione la casilla de verificación del grupo que desea duplicar.
. Seleccione *Duplicar grupo*. Para obtener detalles adicionales sobre cómo crear un grupo, consulte las instrucciones para crear grupos paralink:creating-groups-for-s3-tenant.html["un inquilino S3"] o paralink:creating-groups-for-swift-tenant.html["un inquilino rápido"] .
. Seleccione la pestaña *Grupo local* para crear un grupo local, o seleccione la pestaña *Grupo federado* para importar un grupo desde la fuente de identidad configurada previamente.
+
Si el inicio de sesión único (SSO) está habilitado para su sistema StorageGRID , los usuarios que pertenecen a grupos locales no podrán iniciar sesión en el Administrador de inquilinos, aunque pueden usar aplicaciones cliente para administrar los recursos del inquilino, segúnlink:tenant-management-permissions.html["permisos de grupo"] .

. Introduzca el nombre del grupo.
+
** *Grupo local*: Ingrese un nombre para mostrar y un nombre único.  Podrás editar el nombre para mostrar más tarde.
** *Grupo federado*: Ingrese el nombre único.  Para Active Directory, el nombre único es el nombre asociado con el `sAMAccountName` atributo.  Para OpenLDAP, el nombre único es el nombre asociado con el `uid` atributo.


. Seleccione *Continuar*.
. Según sea necesario, modifique los permisos para este grupo.
. Seleccione *Continuar*.
. Según sea necesario, si está duplicando un grupo para un inquilino S3, seleccione opcionalmente una política diferente de los botones de opción *Agregar política S3*.  Si seleccionó una política personalizada, actualice la cadena JSON según sea necesario.
. Seleccione *Crear grupo*.

