---
permalink: tenant/guidelines-for-configuring-openldap-server.html 
sidebar: sidebar 
keywords: how to configure open ldap 
summary: Si desea utilizar un servidor OpenLDAP para la federación de identidad, debe configurar ajustes específicos en el servidor OpenLDAP. 
---
= Directrices para configurar el servidor OpenLDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea utilizar un servidor OpenLDAP para la federación de identidad, debe configurar ajustes específicos en el servidor OpenLDAP.



== Superposiciones de miembros y refinaciones

Las superposiciones memberof y refint deben estar habilitadas.  Para obtener más información, consulte las instrucciones para el mantenimiento de la membresía de grupo inverso en la _Guía del administrador del software OpenLDAP_.



== Indexación

Debe configurar los siguientes atributos OpenLDAP con las palabras clave de índice especificadas:

[listing]
----
olcDbIndex: objectClass eq
olcDbIndex: uid eq,pres,sub
olcDbIndex: cn eq,pres,sub
olcDbIndex: entryUUID eq
----
Además, asegúrese de que los campos mencionados en la ayuda para el nombre de usuario estén indexados para un rendimiento óptimo.

Consulte la información sobre el mantenimiento de la membresía de grupo inverso en la _Guía del administrador del software OpenLDAP_.
