---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Una cuenta de inquilino le permite utilizar la API REST de Simple Storage Service (S3) o la API REST de Swift para almacenar y recuperar objetos en un sistema StorageGRID .' 
---
= Utilice una cuenta de inquilino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una cuenta de inquilino le permite utilizar la API REST de Simple Storage Service (S3) o la API REST de Swift para almacenar y recuperar objetos en un sistema StorageGRID .



== ¿Qué es una cuenta de inquilino?

Cada cuenta de inquilino tiene sus propios grupos federados o locales, usuarios, depósitos S3 o contenedores Swift y objetos.

Las cuentas de inquilino se pueden utilizar para segregar objetos almacenados por diferentes entidades.  Por ejemplo, se pueden utilizar varias cuentas de inquilino para cualquiera de estos casos de uso:

* *Caso de uso empresarial:* si el sistema StorageGRID se utiliza dentro de una empresa, el almacenamiento de objetos de la red podría estar segregado por los diferentes departamentos de la organización.  Por ejemplo, podría haber cuentas de inquilinos para el departamento de Marketing, el departamento de Atención al Cliente, el departamento de Recursos Humanos, etc.
+

NOTE: Si utiliza el protocolo de cliente S3, también puede usar depósitos S3 y políticas de depósitos para segregar objetos entre los departamentos de una empresa. No es necesario crear cuentas de inquilino separadas. Consulte las instrucciones para la implementaciónlink:../s3/bucket-and-group-access-policies.html["Cubos S3 y políticas de cubos"] Para más información.

* *Caso de uso de proveedor de servicios:* si un proveedor de servicios utiliza el sistema StorageGRID , el almacenamiento de objetos de la red puede estar segregado por las diferentes entidades que alquilan el almacenamiento.  Por ejemplo, podría haber cuentas de inquilinos para la Empresa A, la Empresa B, la Empresa C, etc.




== Cómo crear una cuenta de inquilino

Las cuentas de inquilinos son creadas por unlink:../admin/managing-tenants.html["Administrador de red StorageGRID que utiliza el Administrador de red"] .  Al crear una cuenta de inquilino, el administrador de la red especifica lo siguiente:

* Información básica que incluye el nombre del inquilino, el tipo de cliente (S3) y la cuota de almacenamiento opcional.
* Permisos para la cuenta de inquilino, como si la cuenta de inquilino puede usar servicios de la plataforma S3, configurar su propia fuente de identidad, usar S3 Select o usar una conexión de federación de red.
* El acceso raíz inicial para el inquilino, en función de si el sistema StorageGRID utiliza grupos y usuarios locales, federación de identidad o inicio de sesión único (SSO).


Además, los administradores de la red pueden habilitar la configuración de Bloqueo de objetos S3 para el sistema StorageGRID si las cuentas de inquilinos S3 necesitan cumplir con los requisitos reglamentarios.  Cuando el bloqueo de objetos S3 está habilitado, todas las cuentas de inquilinos de S3 pueden crear y administrar depósitos compatibles.



=== Configurar inquilinos de S3

Después de unlink:../admin/creating-tenant-account.html["Se crea una cuenta de inquilino S3"] , puede acceder al Administrador de inquilinos para realizar tareas como las siguientes:

* Configurar la federación de identidad (a menos que la fuente de identidad se comparta con la red)
* Administrar grupos y usuarios
* Utilice la federación de red para la clonación de cuentas y la replicación entre redes
* Administrar claves de acceso S3
* Crear y administrar depósitos S3
* Utilice los servicios de la plataforma S3
* Utilice S3 Select
* Monitorear el uso del almacenamiento



TIP: Si bien puede crear y administrar depósitos S3 con el Administrador de inquilinos, debe usar unlink:../s3/index.html["Cliente S3"] olink:use-s3-console.html["Consola S3"] para ingerir y gestionar objetos.
