---
permalink: tenant/managing-s3-access-keys.html 
sidebar: sidebar 
keywords: how to manage s3 access key 
summary: Cada usuario de una cuenta de inquilino S3 debe tener una clave de acceso para almacenar y recuperar objetos en el sistema StorageGRID .  Una clave de acceso consta de un ID de clave de acceso y una clave de acceso secreta. 
---
= Administrar claves de acceso S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada usuario de una cuenta de inquilino S3 debe tener una clave de acceso para almacenar y recuperar objetos en el sistema StorageGRID .  Una clave de acceso consta de un ID de clave de acceso y una clave de acceso secreta.

Las claves de acceso S3 se pueden gestionar de la siguiente manera:

* Los usuarios que tienen el permiso *Administrar sus propias credenciales S3* pueden crear o eliminar sus propias claves de acceso S3.
* Los usuarios que tienen permiso de *acceso root* pueden administrar las claves de acceso para la cuenta raíz S3 y todos los demás usuarios.  Las claves de acceso raíz brindan acceso completo a todos los depósitos y objetos para el inquilino, a menos que una política de depósito los deshabilite explícitamente.


StorageGRID admite la autenticación Signature Version 2 y Signature Version 4.  No se permite el acceso entre cuentas a menos que lo habilite explícitamente una política de bucket.
