---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Si habilitó el bloqueo de objetos S3 cuando creó el depósito, puede editarlo para cambiar la configuración de retención predeterminada.  Puede habilitar (o deshabilitar) la retención predeterminada y establecer un modo de retención y un período de retención predeterminados.' 
---
= Actualizar la retención predeterminada de bloqueo de objetos S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si habilitó el bloqueo de objetos S3 cuando creó el depósito, puede editarlo para cambiar la configuración de retención predeterminada.  Puede habilitar (o deshabilitar) la retención predeterminada y establecer un modo de retención y un período de retención predeterminados.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Perteneces a un grupo de usuarios que tiene lalink:tenant-management-permissions.html["Administrar todos los depósitos o permisos de acceso raíz"] . Estos permisos anulan la configuración de permisos en las políticas de grupo o de depósito.
* El bloqueo de objetos S3 está habilitado globalmente para su sistema StorageGRID y usted lo habilitó cuando creó el depósito. Ver link:using-s3-object-lock.html["Utilice S3 Object Lock para retener objetos"] .


.Pasos
. Seleccione *Ver depósitos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Depósitos*.
. Seleccione el nombre del depósito de la tabla.
+
Aparece la página de detalles del depósito.

. Desde la pestaña *Opciones de depósito*, seleccione el acordeón *Bloqueo de objeto S3*.
. De manera opcional, habilite o deshabilite la *Retención predeterminada* para este depósito.
+
Los cambios en esta configuración no se aplican a los objetos que ya están en el depósito ni a ningún objeto que pueda tener sus propios períodos de retención.

. Si la *Retención predeterminada* está habilitada, especifique un *Modo de retención predeterminado* para el depósito.
+
[cols="1a,2a"]
|===
| Modo de retención predeterminado | Descripción 


 a| 
Gobernancia
 a| 
** Usuarios con la `s3:BypassGovernanceRetention` El permiso puede utilizar el `x-amz-bypass-governance-retention: true` encabezado de solicitud para omitir la configuración de retención.
** Estos usuarios pueden eliminar una versión de un objeto antes de que se alcance su fecha de conservación.
** Estos usuarios pueden aumentar, disminuir o eliminar la fecha de conservación de un objeto.




 a| 
Cumplimiento
 a| 
** El objeto no se puede eliminar hasta que se alcance su fecha de conservación.
** La fecha de conservación del objeto se puede aumentar, pero no se puede disminuir.
** La fecha de retención del objeto no se puede eliminar hasta que se alcance esa fecha.


*Nota*: El administrador de su red debe permitirle utilizar el modo de cumplimiento.

|===
. Si la *Retención predeterminada* está habilitada, especifique el *Período de retención predeterminado* para el depósito.
+
El *Período de retención predeterminado* indica durante cuánto tiempo se deben conservar los objetos nuevos agregados a este depósito, a partir del momento en que se ingieren. Especifique un valor que sea menor o igual al período de retención máximo para el inquilino, según lo establecido por el administrador de la red.

+
Se establece un período de retención _máximo_, que puede tener un valor de entre 1 día y 100 años, cuando el administrador de la red crea el inquilino.  Cuando se establece un período de retención _predeterminado_, no puede exceder el valor establecido para el período de retención máximo.  Si es necesario, solicite al administrador de su red que aumente o disminuya el período máximo de retención.

. Seleccione *Guardar cambios*.

