---
permalink: tenant/viewing-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view other user access key 
summary: Si está utilizando un inquilino S3 y tiene los permisos adecuados, puede ver las claves de acceso S3 de otro usuario.  Puede ordenar la lista por tiempo de vencimiento para poder determinar qué claves caducarán pronto.  Según sea necesario, puede crear nuevas claves y eliminar claves que ya no se utilizan. 
---
= Ver las claves de acceso S3 de otro usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está utilizando un inquilino S3 y tiene los permisos adecuados, puede ver las claves de acceso S3 de otro usuario.  Puede ordenar la lista por tiempo de vencimiento para poder determinar qué claves caducarán pronto.  Según sea necesario, puede crear nuevas claves y eliminar claves que ya no se utilizan.

.Antes de empezar
* Ha iniciado sesión en el Administrador de inquilinos mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:tenant-management-permissions.html["Permiso de acceso root"] .



CAUTION: Se puede acceder a los depósitos y objetos S3 que pertenecen a un usuario mediante el ID de clave de acceso y la clave de acceso secreta que se muestran para ese usuario en el Administrador de inquilinos.  Por este motivo, proteja las claves de acceso como lo haría con una contraseña.  Rote las claves de acceso periódicamente, elimine las claves no utilizadas de la cuenta y nunca las comparta con otros usuarios.

.Pasos
. Seleccione *GESTIÓN DE ACCESO* > *Usuarios*.
. Desde la página Usuarios, seleccione el usuario cuyas claves de acceso S3 desea ver.
. Desde la página de detalles del usuario, seleccione *Teclas de acceso*.
. Ordene las claves por *Tiempo de expiración* o *ID de clave de acceso*.
. Según sea necesario, cree nuevas claves y elimine manualmente las claves que ya no se utilizan.
+
Si crea nuevas claves antes de que caduquen las claves existentes, el usuario puede comenzar a usar las nuevas claves sin perder temporalmente el acceso a los objetos de la cuenta.

+
Las claves caducadas se eliminan automáticamente.



.Información relacionada
* link:creating-another-users-s3-access-keys.html["Crear las claves de acceso S3 de otro usuario"]
* link:deleting-another-users-s3-access-keys.html["Eliminar las claves de acceso S3 de otro usuario"]

