---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: Debe descargar los archivos de instalación de StorageGRID y extraer los archivos. Opcionalmente, puede verificar manualmente los archivos en el paquete de instalación. 
---
= Descargue y extraiga los archivos de instalación de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar los archivos de instalación de StorageGRID y extraer los archivos. Opcionalmente, puede verificar manualmente los archivos en el paquete de instalación.

.Pasos
. Ir a la https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de descargas de NetApp para StorageGRID"^] .
. Seleccione el botón para descargar la última versión o seleccione otra versión del menú desplegable y seleccione *Ir*.
. Sign in con el nombre de usuario y la contraseña de su cuenta de NetApp .
. Si aparece una declaración de Precaución/Lectura obligatoria, léala y seleccione la casilla de verificación.
+

CAUTION: Debe aplicar las revisiones necesarias después de instalar la versión de StorageGRID . Para obtener más información, consulte lalink:../maintain/storagegrid-hotfix-procedure.html["Procedimiento de revisión en las instrucciones de recuperación y mantenimiento"]

. Lea el Acuerdo de licencia de usuario final, seleccione la casilla de verificación y luego seleccione *Aceptar y continuar*.
. En la columna *Instalar StorageGRID*, seleccione el archivo de instalación .tgz o .zip para VMware.
+

NOTE: Utilice el `.zip` archivo si está ejecutando Windows en la computadora portátil de servicio.

. Guarde el archivo de instalación.
. [[vmware-download-verification-package]]Si necesita verificar el archivo de instalación:
+
.. Descargue el paquete de verificación de firma de código de StorageGRID .  El nombre de archivo de este paquete utiliza el formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` , dónde `<version-number>` es la versión del software StorageGRID .
.. Siga los pasos paralink:../vmware/download-files-verify.html["verificar manualmente los archivos de instalación"] .


. Extraiga los archivos del archivo de instalación.
. Elige los archivos que necesitas.
+
Los archivos que necesita dependen de la topología de red planificada y de cómo implementará su sistema StorageGRID .




NOTE: Las rutas enumeradas en la tabla son relativas al directorio de nivel superior instalado por el archivo de instalación extraído.

[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./vsphere/LÉAME  a| 
Un archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID .



| ./vsphere/NLF000000.txt  a| 
Una licencia gratuita que no proporciona ningún derecho de soporte para el producto.



| ./vsphere/ NetApp-SG-versión-SHA.vmdk  a| 
El archivo de disco de la máquina virtual que se utiliza como plantilla para crear máquinas virtuales de nodo de cuadrícula.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
El archivo de plantilla de formato de virtualización abierta(`.ovf` ) y archivo de manifiesto(`.mf` ) para implementar el nodo de administración principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
El archivo de plantilla(`.ovf` ) y archivo de manifiesto(`.mf` ) para implementar nodos de administración no principales.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
El archivo de plantilla(`.ovf` ) y archivo de manifiesto(`.mf` ) para implementar nodos de puerta de enlace.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
El archivo de plantilla(`.ovf` ) y archivo de manifiesto(`.mf` ) para implementar nodos de almacenamiento basados en máquinas virtuales.



| Herramienta de scripting de implementación | Descripción 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Un script de shell Bash utilizado para automatizar la implementación de nodos de red virtuales.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Un archivo de configuración de ejemplo para usar con el `deploy-vsphere-ovftool.sh` guion.



| ./vsphere/configure-storagegrid.py  a| 
Un script de Python utilizado para automatizar la configuración de un sistema StorageGRID .



| ./vsphere/configure-sga.py  a| 
Un script de Python utilizado para automatizar la configuración de dispositivos StorageGRID .



| ./vsphere/storagegrid-ssoauth.py  a| 
Un ejemplo de script de Python que puede utilizar para iniciar sesión en la API de administración de Grid cuando el inicio de sesión único (SSO) está habilitado.  También puede utilizar este script para la integración de Ping Federate.



| ./vsphere/configure-storagegrid.sample.json  a| 
Un archivo de configuración de ejemplo para usar con el `configure-storagegrid.py` guion.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para usar con el `configure-storagegrid.py` guion.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Un ejemplo de secuencia de comandos de Python que puede utilizar para iniciar sesión en la API de administración de Grid cuando el inicio de sesión único (SSO) está habilitado mediante Active Directory o Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Un script de ayuda llamado por el compañero `storagegrid-ssoauth-azure.py` Script de Python para realizar interacciones de SSO con Azure.



| ./vsphere/extras/esquemas-api  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de realizar una actualización, puede usar estos esquemas para confirmar que cualquier código que haya escrito para usar las API de administración de StorageGRID será compatible con la nueva versión de StorageGRID si no tiene un entorno de StorageGRID que no sea de producción para realizar pruebas de compatibilidad de actualización.

|===