---
permalink: rhel/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: Debe asignar volúmenes de almacenamiento en bloque a cada host. 
---
= Configurar el almacenamiento del host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asignar volúmenes de almacenamiento en bloque a cada host.

.Antes de empezar
Ha revisado los siguientes temas, que proporcionan la información que necesita para realizar esta tarea:

* link:storage-and-performance-requirements.html["Requisitos de almacenamiento y rendimiento"]
* link:node-container-migration-requirements.html["Requisitos de migración del contenedor de nodos"]


.Acerca de esta tarea
Al asignar volúmenes de almacenamiento en bloque (LUN) a los hosts, utilice las tablas en "Requisitos de almacenamiento" para determinar lo siguiente:

* Número de volúmenes necesarios para cada host (según la cantidad y los tipos de nodos que se implementarán en ese host)
* Categoría de almacenamiento para cada volumen (es decir, datos del sistema o datos de objeto)
* Tamaño de cada volumen


Utilizará esta información, así como el nombre persistente asignado por Linux a cada volumen físico cuando implemente nodos StorageGRID en el host.


NOTE: No necesita particionar, formatear ni montar ninguno de estos volúmenes; solo necesita asegurarse de que sean visibles para los hosts.


NOTE: Solo se requiere un LUN de datos de objeto para los nodos de almacenamiento de solo metadatos.

Evite utilizar archivos de dispositivos especiales "sin procesar"(`/dev/sdb` , por ejemplo) mientras compone su lista de nombres de volúmenes.  Estos archivos pueden cambiar durante los reinicios del host, lo que afectará el funcionamiento correcto del sistema.  Si está utilizando LUN iSCSI y rutas múltiples de Device Mapper, considere usar alias de rutas múltiples en el `/dev/mapper` directorio, especialmente si su topología SAN incluye rutas de red redundantes al almacenamiento compartido.  Alternativamente, puede utilizar los enlaces creados por el sistema en `/dev/disk/by-path/` para los nombres de sus dispositivos persistentes.

Por ejemplo:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
Los resultados variarán para cada instalación.

Asigne nombres descriptivos a cada uno de estos volúmenes de almacenamiento en bloque para simplificar la instalación inicial de StorageGRID y los procedimientos de mantenimiento futuros.  Si está utilizando el controlador de múltiples rutas del asignador de dispositivos para el acceso redundante a volúmenes de almacenamiento compartido, puede utilizar el `alias` campo en tu `/etc/multipath.conf` archivo.

Por ejemplo:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
El uso del campo de alias de esta manera hace que los alias aparezcan como dispositivos de bloque en el `/dev/mapper` directorio en el host, lo que le permite especificar un nombre amigable y fácilmente validado siempre que una operación de configuración o mantenimiento requiera especificar un volumen de almacenamiento en bloque.


NOTE: Si está configurando un almacenamiento compartido para admitir la migración de nodos StorageGRID y utiliza Device Mapper Multipathing, puede crear e instalar un dispositivo común `/etc/multipath.conf` en todos los hosts ubicados conjuntamente.  Solo asegúrese de utilizar un volumen de almacenamiento de motor de contenedor diferente en cada host.  El uso de alias e incluir el nombre de host de destino en el alias para cada LUN de volumen de almacenamiento del motor de contenedor hará que esto sea fácil de recordar y es lo recomendado.


NOTE: La compatibilidad con Docker como motor de contenedores para implementaciones de solo software está obsoleta. Docker será reemplazado por otro motor de contenedores en una versión futura.

.Información relacionada
link:configuring-docker-storage-volume.html["Configurar el volumen de almacenamiento del motor de contenedores"]
