---
permalink: rhel/download-files-verify.html 
sidebar: sidebar 
keywords: red hat linux installation files, how to verify files 
summary: Si es necesario, puede verificar manualmente los archivos en el archivo de instalación de StorageGRID . 
---
= Verificar manualmente los archivos de instalación (opcional)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si es necesario, puede verificar manualmente los archivos en el archivo de instalación de StorageGRID .

.Antes de empezar
Tieneslink:../rhel/downloading-and-extracting-storagegrid-installation-files.html#rhel-download-verification-package["descargué el paquete de verificación"] desde https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de descargas de NetApp para StorageGRID"^] .

.Pasos
. Extraiga los artefactos del paquete de verificación:
+
`tar -xf StorageGRID_11.9.0_Code_Signature_Verification_Package.tar.gz`

. Asegúrese de que se hayan extraído estos artefactos:
+
** Certificado de hoja: `Leaf-Cert.pem`
** Cadena de certificados: `CA-Int-Cert.pem`
** Cadena de respuesta de marca de tiempo: `TS-Cert.pem`
** Archivo de suma de comprobación: `sha256sum`
** Firma de suma de comprobación: `sha256sum.sig`
** Archivo de respuesta de marca de tiempo: `sha256sum.sig.tsr`


. Utilice la cadena para verificar que el certificado de hoja sea válido.
+
*Ejemplo*: `openssl verify -CAfile CA-Int-Cert.pem Leaf-Cert.pem`

+
*Resultado esperado*: `Leaf-Cert.pem: OK`

. Si el paso _2_ falló debido a un certificado de hoja vencido, utilice el `tsr` archivo a verificar.
+
*Ejemplo*: `openssl ts -CAfile CA-Int-Cert.pem -untrusted TS-Cert.pem -verify -data sha256sum.sig -in sha256sum.sig.tsr`

+
*Los resultados esperados incluyen*: `Verification: OK`

. Cree un archivo de clave pública a partir del certificado de hoja.
+
*Ejemplo*: `openssl x509 -pubkey -noout -in Leaf-Cert.pem > Leaf-Cert.pub`

+
*Resultado esperado*: _ninguno_

. Utilice la clave pública para verificar la `sha256sum` archivo contra `sha256sum.sig` .
+
*Ejemplo*: `openssl dgst -sha256 -verify Leaf-Cert.pub -signature sha256sum.sig sha256sum`

+
*Resultado esperado*: `Verified OK`

. Verificar el `sha256sum` contenido del archivo contra sumas de comprobación recién creadas.
+
*Ejemplo*: `sha256sum -c sha256sum`

+
*Resultado esperado*: `_<filename>_: OK` +
`_<filename>_` es el nombre del archivo que descargaste.

. link:../rhel/downloading-and-extracting-storagegrid-installation-files.html["Complete los pasos restantes"]para extraer y elegir los archivos apropiados del archivo de instalación.

