---
permalink: rhel/installing-storagegrid-webscale-host-service.html 
sidebar: sidebar 
keywords: how to install host services 
summary: Utilice el paquete RPM de StorageGRID para instalar los servicios de host de StorageGRID . 
---
= Instalar servicios de host de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el paquete RPM de StorageGRID para instalar los servicios de host de StorageGRID .

.Acerca de esta tarea
Estas instrucciones describen cómo instalar los servicios de host desde los paquetes RPM.  Como alternativa, puede utilizar los metadatos del repositorio DNF incluidos en el archivo de instalación para instalar los paquetes RPM de forma remota.  Consulte las instrucciones del repositorio DNF para su sistema operativo Linux.

.Pasos
. Copie los paquetes RPM de StorageGRID en cada uno de sus hosts o póngalos a disposición en el almacenamiento compartido.
+
Por ejemplo, colóquelos en el `/tmp` directorio, por lo que puede utilizar el comando de ejemplo en el siguiente paso.

. Inicie sesión en cada host como root o usando una cuenta con permiso sudo y ejecute los siguientes comandos en el orden especificado:
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Images-version-SHA.rpm
----
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Service-version-SHA.rpm
----
+

CAUTION: Primero debe instalar el paquete de imágenes y luego el paquete de servicios.

+

NOTE: Si colocó los paquetes en un directorio distinto de `/tmp` , modifique el comando para reflejar la ruta que utilizó.


