---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Puede utilizar una máquina virtual para alojar cualquier tipo de nodo StorageGRID .  Necesita una máquina virtual para cada nodo de la red. 
---
= Requisitos de software para Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar una máquina virtual para alojar cualquier tipo de nodo StorageGRID .  Necesita una máquina virtual para cada nodo de la red.

Para instalar StorageGRID en Red Hat Enterprise Linux (RHEL), debe instalar algunos paquetes de software de terceros. Algunas distribuciones de Linux compatibles no contienen estos paquetes de forma predeterminada. Las versiones de paquetes de software en las que se prueban las instalaciones de StorageGRID incluyen las que se enumeran en esta página.

Si selecciona una distribución de Linux y una opción de instalación en tiempo de ejecución de contenedor que requiere alguno de estos paquetes, y la distribución de Linux no los instala automáticamente, instale una de las versiones enumeradas aquí si está disponible a través de su proveedor o del vendedor de soporte para su distribución de Linux.  De lo contrario, utilice las versiones de paquetes predeterminadas disponibles de su proveedor.

Todas las opciones de instalación requieren Podman o Docker.  No instale ambos paquetes.  Instale sólo el paquete requerido por su opción de instalación.


NOTE: La compatibilidad con Docker como motor de contenedores para implementaciones de solo software está obsoleta. Docker será reemplazado por otro motor de contenedores en una versión futura.



== Versiones de Python probadas

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Versiones de Podman probadas

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== Versiones de Docker probadas


IMPORTANT: La compatibilidad con Docker está obsoleta y se eliminará en una versión futura.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2

