---
permalink: rhel/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot red hat linux installation 
summary: Si ocurre algún problema durante la instalación del sistema StorageGRID , puede acceder a los archivos de registro de instalación.  Es posible que el soporte técnico también necesite utilizar los archivos de registro de instalación para resolver problemas. 
---
= Solucionar problemas de instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ocurre algún problema durante la instalación del sistema StorageGRID , puede acceder a los archivos de registro de instalación.  Es posible que el soporte técnico también necesite utilizar los archivos de registro de instalación para resolver problemas.

Los siguientes archivos de registro de instalación están disponibles en el contenedor que ejecuta cada nodo:

* `/var/local/log/install.log`(se encuentra en todos los nodos de la red)
* `/var/local/log/gdu-server.log`(se encuentra en el nodo de administración principal)


Los siguientes archivos de registro de instalación están disponibles en el host:

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/node-name.log`


Para saber cómo acceder a los archivos de registro, consultelink:../monitor/collecting-log-files-and-system-data.html["Recopilar archivos de registro y datos del sistema"] .

.Información relacionada
link:../troubleshoot/index.html["Solucionar problemas de un sistema StorageGRID"]
