---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Al cambiar las contraseñas de acceso SSH para los nodos de administración también se actualizan los conjuntos únicos de claves SSH internas para cada nodo de la red.  El nodo de administración principal utiliza estas claves SSH para acceder a los nodos mediante una autenticación segura y sin contraseña. 
---
= Cambiar las contraseñas de acceso SSH para los nodos de administración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al cambiar las contraseñas de acceso SSH para los nodos de administración también se actualizan los conjuntos únicos de claves SSH internas para cada nodo de la red.  El nodo de administración principal utiliza estas claves SSH para acceder a los nodos mediante una autenticación segura y sin contraseña.

Utilice una clave SSH para iniciar sesión en un nodo como `admin` o al usuario root en una máquina virtual o conexión de consola física.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:admin-group-permissions.html["Permiso de mantenimiento o acceso root"] .
* Tienes la contraseña de aprovisionamiento actual.


.Acerca de esta tarea
Las nuevas contraseñas de acceso para los nodos de administración y las nuevas claves internas para cada nodo se almacenan en el `Passwords.txt` archivo en el paquete de recuperación. Las claves se enumeran en la columna Contraseña de ese archivo.

Hay contraseñas de acceso SSH independientes para las claves SSH utilizadas para la comunicación entre nodos.  Estos no se modifican con este procedimiento.



== Acceder al asistente

.Pasos
. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Contraseñas de red*.
. En *Cambiar claves SSH*, seleccione *Realizar un cambio*.




== [[download-current]]Descargar el paquete de recuperación actual

Antes de cambiar las claves de acceso SSH, descargue el paquete de recuperación actual. Puede utilizar las claves de este archivo si el proceso de cambio de clave falla para algún nodo.

.Pasos
. Introduzca la contraseña de aprovisionamiento para su red.
. Seleccione *Descargar paquete de recuperación*.
. Copiar el archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .

. Seleccione *Continuar*.
. Cuando aparezca el cuadro de diálogo de confirmación, seleccione *Sí* si está listo para comenzar a cambiar las claves de acceso SSH.
+

CAUTION: No puedes cancelar este proceso una vez iniciado.





== Cambiar las claves de acceso SSH

Cuando se inicia el proceso de cambio de claves de acceso SSH, se genera un nuevo paquete de recuperación que incluye las nuevas claves. Luego, las claves se actualizan en cada nodo.

.Pasos
. Espere a que se genere el nuevo paquete de recuperación, lo que puede tardar unos minutos.
. Cuando el botón Descargar nuevo paquete de recuperación esté habilitado, seleccione *Descargar nuevo paquete de recuperación* y guarde el archivo del nuevo paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
. Cuando se complete la descarga:
+
.. Abrir el `.zip` archivo.
.. Confirme que puede acceder al contenido, incluido el `Passwords.txt` archivo, que contiene las nuevas claves de acceso SSH.
.. Copiar el nuevo archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: No sobrescriba el paquete de recuperación antiguo.

+
El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .



. Espere a que las claves se actualicen en cada nodo, lo que puede demorar unos minutos.
+
Si se cambian las claves de todos los nodos, aparece un banner de éxito verde.

+
Si se produce un error durante el proceso de actualización, un mensaje de banner enumera la cantidad de nodos cuyas claves no se pudieron cambiar.  El sistema volverá a intentar automáticamente el proceso en cualquier nodo cuya clave no haya sido cambiada.  Si el proceso finaliza con algunos nodos que aún no tienen una clave modificada, aparece el botón *Reintentar*.

+
Si la actualización de la clave falló para uno o más nodos:

+
.. Revise los mensajes de error enumerados en la tabla.
.. Resolver los problemas.
.. Seleccione *Reintentar*.
+
Al volver a intentarlo solo se cambian las claves de acceso SSH en los nodos que fallaron durante intentos de cambio de clave anteriores.



. Después de cambiar las claves de acceso SSH para todos los nodos, elimine el archivo<<download-current,primer paquete de recuperación que descargaste>> .
. Opcionalmente, seleccione *MANTENIMIENTO* > *Sistema* > *Paquete de recuperación* para descargar una copia adicional del nuevo paquete de recuperación.

