---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nodo de su red tiene una contraseña de consola de nodo única, que necesita para iniciar sesión en el nodo.  Utilice estos pasos para cambiar la contraseña de la consola de nodo para cada nodo de su red.  Las contraseñas se almacenan en el paquete de recuperación. 
---
= Cambiar las contraseñas de la consola del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nodo de su red tiene una contraseña de consola de nodo única, que necesita para iniciar sesión en el nodo.  Utilice estos pasos para cambiar la contraseña única de la consola de cada nodo de su red.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:admin-group-permissions.html["Permiso de mantenimiento o acceso root"] .
* Tienes la contraseña de aprovisionamiento actual.


.Acerca de esta tarea
Utilice la contraseña de la consola del nodo para iniciar sesión en un nodo como "admin" mediante SSH, o como usuario root en una conexión de consola física/VM.  El proceso de cambio de contraseña de la consola del nodo crea nuevas contraseñas para cada nodo de su red y almacena las contraseñas en un archivo actualizado. `Passwords.txt` archivo en el paquete de recuperación.  Las contraseñas aparecen en la columna Contraseña del archivo Passwords.txt.


NOTE: Hay contraseñas de acceso SSH independientes para las claves SSH utilizadas para la comunicación entre nodos.  Las contraseñas de acceso SSH no se modifican con este procedimiento.



== Acceder al asistente

.Pasos
. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Contraseñas de red*.
. En *Cambiar contraseñas de la consola del nodo*, seleccione *Realizar un cambio*.




== Introduzca la contraseña de aprovisionamiento

.Pasos
. Introduzca la contraseña de aprovisionamiento para su red.
. Seleccione *Continuar*.




== [[download-current]]Descargar el paquete de recuperación actual

Antes de cambiar las contraseñas de la consola del nodo, descargue el paquete de recuperación actual. Puede utilizar las contraseñas de este archivo si el proceso de cambio de contraseña falla para algún nodo.

.Pasos
. Seleccione *Descargar paquete de recuperación*.
. Copiar el archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .

. Seleccione *Continuar*.
. Cuando aparezca el cuadro de diálogo de confirmación, seleccione *Sí* si está listo para comenzar a cambiar las contraseñas de la consola del nodo.
+
No puedes cancelar este proceso una vez iniciado.





== Cambiar las contraseñas de la consola del nodo

Cuando se inicia el proceso de contraseña de la consola del nodo, se genera un nuevo paquete de recuperación que incluye las nuevas contraseñas.  Luego, las contraseñas se actualizan en cada nodo.

.Pasos
. Espere a que se genere el nuevo paquete de recuperación, lo que puede tardar unos minutos.
. Seleccione *Descargar nuevo paquete de recuperación*.
. Cuando se complete la descarga:
+
.. Abrir el `.zip` archivo.
.. Confirme que puede acceder al contenido, incluido el `Passwords.txt` archivo, que contiene las nuevas contraseñas de la consola del nodo.
.. Copiar el nuevo archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: No sobrescriba el paquete de recuperación antiguo.

+
El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .



. Seleccione la casilla de verificación para indicar que ha descargado el nuevo paquete de recuperación y verificado el contenido.
. Seleccione *Cambiar contraseñas de la consola del nodo* y espere a que todos los nodos se actualicen con las nuevas contraseñas.  Esto podría tardar unos minutos.
+
Si se cambian las contraseñas de todos los nodos, aparece un banner de éxito verde.  Vaya al siguiente paso.

+
Si se produce un error durante el proceso de actualización, aparecerá un mensaje con la lista de nodos que no pudieron cambiar sus contraseñas. El sistema volverá a intentar automáticamente el proceso en cualquier nodo cuya contraseña no se haya podido cambiar. Si el proceso finaliza con algunos nodos que aún no tienen la contraseña cambiada, aparece el botón *Reintentar*.

+
Si la actualización de contraseña falló para uno o más nodos:

+
.. Revise los mensajes de error enumerados en la tabla.
.. Resolver los problemas.
.. Seleccione *Reintentar*.
+

NOTE: Al volver a intentarlo solo se cambian las contraseñas de la consola de nodo en los nodos que fallaron durante intentos anteriores de cambio de contraseña.



. Después de cambiar las contraseñas de la consola de nodo para todos los nodos, elimine el archivo<<download-current,primer paquete de recuperación que descargaste>> .
. Opcionalmente, utilice el enlace *Paquete de recuperación* para descargar una copia adicional del nuevo paquete de recuperación.

