---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: Puede configurar la seguridad de la red y de los objetos para cifrar los objetos almacenados, evitar ciertas solicitudes S3 o permitir que las conexiones de los clientes a los nodos de almacenamiento utilicen HTTP en lugar de HTTPS. 
---
= Configurar la seguridad de la red y de los objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar la seguridad de la red y de los objetos para cifrar los objetos almacenados, evitar ciertas solicitudes S3 o permitir que las conexiones de los clientes a los nodos de almacenamiento utilicen HTTP en lugar de HTTPS.



== Cifrado de objetos almacenados

El cifrado de objetos almacenados permite el cifrado de todos los datos de los objetos a medida que se ingieren a través de S3.  De forma predeterminada, los objetos almacenados no están cifrados, pero puede elegir cifrarlos utilizando el algoritmo de cifrado AES-128 o AES-256.  Cuando habilita la configuración, todos los objetos recién ingeridos se cifran, pero no se realiza ningún cambio en los objetos almacenados existentes.  Si deshabilita el cifrado, los objetos actualmente cifrados permanecerán cifrados, pero los objetos recién ingeridos no lo estarán.

La configuración de cifrado de objetos almacenados se aplica únicamente a los objetos S3 que no se han cifrado mediante cifrado a nivel de depósito o de objeto.

Para obtener más detalles sobre los métodos de cifrado de StorageGRID , consultelink:../admin/reviewing-storagegrid-encryption-methods.html["Revisar los métodos de cifrado de StorageGRID"] .



== Evitar modificaciones del cliente

Evitar modificaciones del cliente es una configuración de todo el sistema.  Cuando se selecciona la opción *Impedir modificación del cliente*, se rechazan las siguientes solicitudes.



=== API REST de S3

* Solicitudes de DeleteBucket
* Cualquier solicitud para modificar los datos de un objeto existente, los metadatos definidos por el usuario o el etiquetado de objetos S3




== Habilitar HTTP para conexiones de nodo de almacenamiento

De forma predeterminada, las aplicaciones cliente utilizan el protocolo de red HTTPS para cualquier conexión directa a los nodos de almacenamiento.  Opcionalmente, puede habilitar HTTP para estas conexiones, por ejemplo, al probar una cuadrícula que no es de producción.

Utilice HTTP para las conexiones de nodo de almacenamiento solo si los clientes S3 necesitan realizar conexiones HTTP directamente a los nodos de almacenamiento.  No es necesario utilizar esta opción para clientes que solo usan conexiones HTTPS o para clientes que se conectan al servicio Load Balancer (porque puedelink:../admin/configuring-load-balancer-endpoints.html["configurar cada punto final del balanceador de carga"] para utilizar HTTP o HTTPS).

Verlink:summary-ip-addresses-and-ports-for-client-connections.html["Resumen: Direcciones IP y puertos para conexiones de cliente"] para conocer qué puertos utilizan los clientes S3 cuando se conectan a nodos de almacenamiento mediante HTTP o HTTPS.



== Seleccionar opciones

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tienes permiso de acceso root.


.Pasos
. Seleccione *CONFIGURACIÓN* > *Seguridad* > *Configuración de seguridad*.
. Seleccione la pestaña *Red y objetos*.
. Para el cifrado de objetos almacenados, utilice la configuración *Ninguno* (predeterminada) si no desea que se cifren los objetos almacenados, o seleccione *AES-128* o *AES-256* para cifrar los objetos almacenados.
. Opcionalmente, seleccione *Evitar modificación del cliente* si desea evitar que los clientes S3 realicen solicitudes específicas.
+

NOTE: Si cambia esta configuración, tomará aproximadamente un minuto para que se aplique la nueva configuración.  El valor configurado se almacena en caché para mejorar el rendimiento y la escala.

. Opcionalmente, seleccione *Habilitar HTTP para conexiones de nodo de almacenamiento* si los clientes se conectan directamente a los nodos de almacenamiento y desea utilizar conexiones HTTP.
+

NOTE: Tenga cuidado al habilitar HTTP para una cuadrícula de producción porque las solicitudes se enviarán sin cifrar.

. Seleccione *Guardar*.

