---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Si es un usuario local del Grid Manager, puede cambiar su propia contraseña. 
---
= Cambiar tu contraseña
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si es un usuario local del Grid Manager, puede cambiar su propia contraseña.

.Antes de empezar
Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .

.Acerca de esta tarea
Si inicia sesión en StorageGRID como un usuario federado o si el inicio de sesión único (SSO) está habilitado, no podrá cambiar su contraseña en Grid Manager.  En su lugar, debe cambiar su contraseña en la fuente de identidad externa, por ejemplo, Active Directory o OpenLDAP.

.Pasos
. Desde el encabezado del Administrador de cuadrícula, seleccione *_su nombre_* > *Cambiar contraseña*.
. Introduzca su contraseña actual.
. Escriba una nueva contraseña.
+
Su contraseña debe contener al menos 8 y no más de 32 caracteres.  Las contraseñas distinguen entre mayúsculas y minúsculas.

. Ingrese nuevamente la nueva contraseña.
. Seleccione *Guardar*.

