---
permalink: admin/copying-storagegrid-system-ca-certificate.html 
sidebar: sidebar 
keywords: grid ca certificate, copy certificate 
summary: 'StorageGRID utiliza una autoridad de certificación interna (CA) para proteger el tráfico interno.  Este certificado no cambia si carga sus propios certificados.' 
---
= Copiar el certificado de CA de Grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID utiliza una autoridad de certificación (CA) interna para proteger el tráfico interno.  Este certificado no cambia si carga sus propios certificados.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tieneslink:admin-group-permissions.html["permisos de acceso específicos"] .


.Acerca de esta tarea
Si se ha configurado un certificado de servidor personalizado, las aplicaciones cliente deben verificar el servidor utilizando el certificado de servidor personalizado.  No deben copiar el certificado CA del sistema StorageGRID .

.Pasos
. Seleccione *CONFIGURACIÓN* > *Seguridad* > *Certificados* y luego seleccione la pestaña *Grid CA*.
. En la sección *Certificado PEM*, descargue o copie el certificado.
+
[role="tabbed-block"]
====
.Descargar archivo de certificado
--
Descargar el certificado `.pem` archivo.

.. Seleccione *Descargar certificado*.
.. Especifique el nombre del archivo del certificado y la ubicación de descarga.  Guarde el archivo con la extensión `.pem` .
+
Por ejemplo:  `storagegrid_certificate.pem`



--
.Copiar certificado PEM
--
Copie el texto del certificado para pegarlo en otro lugar.

.. Seleccione *Copiar certificado PEM*.
.. Pegue el certificado copiado en un editor de texto.
.. Guarde el archivo de texto con la extensión `.pem` .
+
Por ejemplo:  `storagegrid_certificate.pem`



--
====

