---
permalink: admin/disabling-single-sign-on.html 
sidebar: sidebar 
keywords: disable sso, disable single sign on 
summary: 'Puede deshabilitar el inicio de sesión único (SSO) si ya no desea utilizar esta funcionalidad.  Debe deshabilitar el inicio de sesión único antes de poder deshabilitar la federación de identidad.' 
---
= Deshabilitar el inicio de sesión único
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desactivar el inicio de sesión único (SSO) si ya no desea utilizar esta funcionalidad.  Debe deshabilitar el inicio de sesión único antes de poder deshabilitar la federación de identidad.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tieneslink:admin-group-permissions.html["permisos de acceso específicos"] .


.Pasos
. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Inicio de sesión único*.
+
Aparece la página de inicio de sesión único.

. Seleccione la opción *Deshabilitado*.
. Seleccione *Guardar*.
+
Aparece un mensaje de advertencia que indica que los usuarios locales ahora podrán iniciar sesión.

. Seleccione *Aceptar*.
+
La próxima vez que inicie sesión en StorageGRID , aparecerá la página de Sign in de StorageGRID y deberá ingresar el nombre de usuario y la contraseña de un usuario de StorageGRID local o federado.


