---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: admin network, client network, grid network, access interface, trunk interface 
summary: StorageGRID admite hasta tres interfaces de red por nodo de red, lo que le permite configurar la red para cada nodo de red individual para que coincida con sus requisitos de seguridad y acceso. 
---
= Directrices para redes StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar Grid Manager para configurar y administrar redes y conexiones de StorageGRID .

Verlink:configuring-client-connections.html["Configurar conexiones de cliente S3"] para aprender cómo conectar clientes S3.



== Redes StorageGRID predeterminadas

De forma predeterminada, StorageGRID admite tres interfaces de red por nodo de red, lo que le permite configurar la red para cada nodo de red individual para que coincida con sus requisitos de seguridad y acceso.

Para obtener más información sobre la topología de red, consultelink:../network/index.html["Pautas para establecer redes"] .



=== Red de cuadrícula

Requerido.  La red Grid se utiliza para todo el tráfico interno de StorageGRID .  Proporciona conectividad entre todos los nodos de la red, en todos los sitios y subredes.



=== Red de administración

Opcional. La red de administración normalmente se utiliza para la administración y el mantenimiento del sistema.  También se puede utilizar para acceder al protocolo de cliente.  La red de administración normalmente es una red privada y no necesita ser enrutable entre sitios.



=== Red de clientes

Opcional. La red de cliente es una red abierta que normalmente se utiliza para proporcionar acceso a aplicaciones de cliente S3, de modo que la red de cuadrícula se puede aislar y proteger.  La red del cliente puede comunicarse con cualquier subred accesible a través de la puerta de enlace local.



== Pautas

* Cada nodo StorageGRID requiere una interfaz de red dedicada, una dirección IP, una máscara de subred y una puerta de enlace para cada red a la que está asignado.
* Un nodo de red no puede tener más de una interfaz en una red.
* Se admite una única puerta de enlace por red y por nodo de la red, y debe estar en la misma subred que el nodo.  Puede implementar un enrutamiento más complejo en la puerta de enlace, si es necesario.
* En cada nodo, cada red se asigna a una interfaz de red específica.
+
[cols="1a,1a"]
|===
| Red | Nombre de la interfaz 


 a| 
Red
 a| 
eth0



 a| 
Administrador (opcional)
 a| 
eth1



 a| 
Cliente (opcional)
 a| 
eth2

|===
* Si el nodo está conectado a un dispositivo StorageGRID , se utilizan puertos específicos para cada red.  Para obtener más detalles, consulte las instrucciones de instalación de su aparato.
* La ruta predeterminada se genera automáticamente, por nodo.  Si eth2 está habilitado, entonces 0.0.0.0/0 usa la red del cliente en eth2.  Si eth2 no está habilitado, entonces 0.0.0.0/0 usa la red Grid en eth0.
* La red del cliente no estará operativa hasta que el nodo de la red se haya unido a la red.
* La red de administración se puede configurar durante la implementación del nodo de la red para permitir el acceso a la interfaz de usuario de instalación antes de que la red esté completamente instalada.




== Interfaces opcionales

Opcionalmente, puede agregar interfaces adicionales a un nodo.  Por ejemplo, es posible que desee agregar una interfaz troncal a un nodo de administración o de puerta de enlace, para poder usarlink:../admin/configure-vlan-interfaces.html["Interfaces VLAN"] para segregar el tráfico perteneciente a diferentes aplicaciones o inquilinos.  O bien, es posible que desee agregar una interfaz de acceso para usar en unlink:../admin/configure-high-availability-group.html["grupo de alta disponibilidad (HA)"] .

Para agregar interfaces troncales o de acceso, consulte lo siguiente:

* *VMware (después de instalar el nodo)*:link:../maintain/vmware-adding-trunk-or-access-interfaces-to-node.html["VMware: Agregar interfaces troncales o de acceso a un nodo"]
+
** *Red Hat Enterprise Linux (antes de instalar el nodo)*:link:../rhel/creating-node-configuration-files.html["Crear archivos de configuración de nodos"]
** *Ubuntu o Debian (antes de instalar el nodo)*:link:../ubuntu/creating-node-configuration-files.html["Crear archivos de configuración de nodos"]
** *RHEL, Ubuntu o Debian (después de instalar el nodo)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: Agregar interfaces troncales o de acceso a un nodo"]



