---
permalink: admin/identifying-primary-admin-node.html 
sidebar: sidebar 
keywords: primary admin node, configuration management node 
summary: El nodo de administración principal proporciona más funciones que los nodos de administración no principales.  Por ejemplo, algunos procedimientos de mantenimiento deben realizarse utilizando el nodo de administración principal. 
---
= Identificar el nodo de administración principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El nodo de administración principal proporciona más funciones que los nodos de administración no principales.  Por ejemplo, algunos procedimientos de mantenimiento deben realizarse utilizando el nodo de administración principal.

Para obtener más información sobre los nodos de administración, consultelink:../primer/what-admin-node-is.html["¿Qué es un nodo de administración?"] .

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tieneslink:admin-group-permissions.html["permisos de acceso específicos"] .


.Pasos
. Seleccione *NODOS*.
. Introduzca *primary* en el cuadro de búsqueda.
+
En los resultados de la búsqueda, identifique el nodo con "Nodo de administración principal" que se muestra en la columna Tipo.  Se debe incluir un nodo de administración principal.


