---
permalink: admin/manage-security.html 
sidebar: sidebar 
keywords: how to manage security 
summary: Puede configurar varias configuraciones de seguridad desde Grid Manager para ayudar a proteger su sistema StorageGRID . 
---
= Gestionar la seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar varias configuraciones de seguridad desde Grid Manager para ayudar a proteger su sistema StorageGRID .



== Administrar el cifrado

StorageGRID ofrece varias opciones para cifrar datos.  Deberíalink:reviewing-storagegrid-encryption-methods.html["revise los métodos de cifrado disponibles"] para determinar cuáles cumplen con sus requisitos de protección de datos.



== Administrar certificados

Puedelink:using-storagegrid-security-certificates.html["configurar y administrar los certificados del servidor"] Se utiliza para conexiones HTTP o los certificados de cliente utilizados para autenticar la identidad de un cliente o usuario en el servidor.



== Configurar servidores de administración de claves

Usando unlink:kms-configuring.html["servidor de gestión de claves"] Le permite proteger los datos de StorageGRID incluso si se elimina un dispositivo del centro de datos.  Una vez cifrados los volúmenes del dispositivo, no podrá acceder a ningún dato del dispositivo a menos que el nodo pueda comunicarse con el KMS.


NOTE: Para utilizar la administración de claves de cifrado, debe habilitar la configuración *Cifrado de nodo* para cada dispositivo durante la instalación, antes de agregar el dispositivo a la red.



== Administrar la configuración del proxy

Si está utilizando servicios de la plataforma S3 o grupos de almacenamiento en la nube, puede configurar unlink:configuring-storage-proxy-settings.html["servidor proxy de almacenamiento"] entre los nodos de almacenamiento y los puntos finales externos de S3.  Si envía paquetes de AutoSupport mediante HTTPS o HTTP, puede configurar unlink:configuring-admin-proxy-settings.html["servidor proxy de administración"] entre los nodos de administración y el soporte técnico.



== Controlar cortafuegos

Para mejorar la seguridad de su sistema, puede controlar el acceso a los nodos de administración de StorageGRID abriendo o cerrando puertos específicos en ellink:controlling-access-through-firewalls.html["cortafuegos externo"] .  También puede controlar el acceso a la red de cada nodo configurando sulink:manage-firewall-controls.html["cortafuegos interno"] .  Puede evitar el acceso a todos los puertos excepto aquellos necesarios para su implementación.
