---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'Una cuenta de inquilino le permite utilizar la API REST de Simple Storage Service (S3) para almacenar y recuperar objetos en un sistema StorageGRID .' 
---
= ¿Qué son las cuentas de inquilinos?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una cuenta de inquilino le permite utilizar la API REST de Simple Storage Service (S3) para almacenar y recuperar objetos en un sistema StorageGRID .


TIP: Se han eliminado los detalles rápidos de esta versión del sitio de documentación. Ver https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8: Administrar inquilinos"^] .

Como administrador de la red, usted crea y administra las cuentas de inquilino que los clientes S3 usan para almacenar y recuperar objetos.

Cada cuenta de inquilino tiene grupos federados o locales, usuarios, depósitos S3 y objetos.

Las cuentas de inquilino se pueden utilizar para segregar objetos almacenados por diferentes entidades.  Por ejemplo, se pueden utilizar varias cuentas de inquilino para cualquiera de estos casos de uso:

* *Caso de uso empresarial:* si está administrando un sistema StorageGRID en una aplicación empresarial, es posible que desee segregar el almacenamiento de objetos de la red por los diferentes departamentos de su organización.  En este caso, podría crear cuentas de inquilino para el departamento de Marketing, el departamento de Atención al Cliente, el departamento de Recursos Humanos, etc.
+

NOTE: Si utiliza el protocolo de cliente S3, puede usar depósitos S3 y políticas de depósitos para segregar objetos entre los departamentos de una empresa. No es necesario utilizar cuentas de inquilino. Consulte las instrucciones para la implementaciónlink:../s3/bucket-and-group-access-policies.html["Cubos S3 y políticas de cubos"] Para más información.

* *Caso de uso de proveedor de servicios:* Si administra un sistema StorageGRID como proveedor de servicios, puede segregar el almacenamiento de objetos de la red por las diferentes entidades que alquilarán el almacenamiento en su red.  En este caso, crearía cuentas de inquilino para la Empresa A, la Empresa B, la Empresa C, etc.


Para obtener más información, consulte link:../tenant/index.html["Utilice una cuenta de inquilino"] .



== ¿Cómo creo una cuenta de inquilino?

Utilice el administrador de Grid para crear una cuenta de inquilino.  Al crear una cuenta de inquilino, se especifica la siguiente información:

* Información básica que incluye el nombre del inquilino, el tipo de cliente (S3) y la cuota de almacenamiento opcional.
* Permisos para la cuenta de inquilino, como si la cuenta de inquilino puede usar servicios de la plataforma S3, configurar su propia fuente de identidad, usar S3 Select o usar una conexión de federación de red.
* El acceso raíz inicial para el inquilino, en función de si el sistema StorageGRID utiliza grupos y usuarios locales, federación de identidad o inicio de sesión único (SSO).


Además, puede habilitar la configuración de Bloqueo de objetos S3 para el sistema StorageGRID si las cuentas de inquilinos S3 deben cumplir con requisitos reglamentarios.  Cuando el bloqueo de objetos S3 está habilitado, todas las cuentas de inquilinos de S3 pueden crear y administrar depósitos compatibles.



== ¿Para qué se utiliza Tenant Manager?

Después de crear la cuenta de inquilino, los usuarios inquilinos pueden iniciar sesión en el Administrador de inquilinos para realizar tareas como las siguientes:

* Configurar la federación de identidad (a menos que la fuente de identidad se comparta con la red)
* Administrar grupos y usuarios
* Utilice la federación de red para la clonación de cuentas y la replicación entre redes
* Administrar claves de acceso S3
* Crear y administrar depósitos S3
* Utilice los servicios de la plataforma S3
* Utilice S3 Select
* Monitorear el uso del almacenamiento



TIP: Si bien los usuarios inquilinos de S3 pueden crear y administrar claves de acceso y depósitos de S3 con el Administrador de inquilinos, deben usar una aplicación cliente de S3 para ingerir y administrar objetos. Verlink:../s3/index.html["Utilice la API REST de S3"] Para más detalles.
