---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords: storage node is full 
summary: 'A medida que los nodos de almacenamiento alcanzan su capacidad, debe expandir el sistema StorageGRID mediante la incorporación de nuevo almacenamiento.  Hay tres opciones disponibles: agregar volúmenes de almacenamiento, agregar estantes de expansión de almacenamiento y agregar nodos de almacenamiento.' 
---
= Administrar nodos de almacenamiento completos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A medida que los nodos de almacenamiento alcanzan su capacidad, debe expandir el sistema StorageGRID mediante la incorporación de nuevo almacenamiento.  Hay tres opciones disponibles: agregar volúmenes de almacenamiento, agregar estantes de expansión de almacenamiento y agregar nodos de almacenamiento.



== Agregar volúmenes de almacenamiento

Cada nodo de almacenamiento admite una cantidad máxima de volúmenes de almacenamiento.  El máximo definido varía según la plataforma.  Si un nodo de almacenamiento contiene menos que la cantidad máxima de volúmenes de almacenamiento, puede agregar volúmenes para aumentar su capacidad. Vea las instrucciones paralink:../expand/index.html["Ampliación de un sistema StorageGRID"] .



== Añadir estantes de expansión de almacenamiento

Algunos nodos de almacenamiento del dispositivo StorageGRID , como SG6060 o SG6160, pueden admitir estantes de almacenamiento adicionales.  Si tiene dispositivos StorageGRID con capacidades de expansión que aún no se han ampliado a su capacidad máxima, puede agregar estantes de almacenamiento para aumentar la capacidad. Vea las instrucciones paralink:../expand/index.html["Ampliación de un sistema StorageGRID"] .



== Agregar nodos de almacenamiento

Puede aumentar la capacidad de almacenamiento agregando nodos de almacenamiento.  Al agregar almacenamiento se debe tener en cuenta cuidadosamente las reglas ILM actualmente activas y los requisitos de capacidad. Vea las instrucciones paralink:../expand/index.html["Ampliación de un sistema StorageGRID"] .
