---
permalink: s3/configuring-tenant-accounts-and-connections.html 
sidebar: sidebar 
keywords: aws cli, test s3 client connection 
summary: 'Puede utilizar la interfaz de línea de comandos de Amazon Web Services (AWS CLI) para probar su conexión al sistema y verificar que puede leer y escribir objetos.' 
---
= Probar la configuración de la API REST de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la interfaz de línea de comandos de Amazon Web Services (AWS CLI) para probar su conexión al sistema y verificar que puede leer y escribir objetos.

.Antes de empezar
* Ha descargado e instalado la AWS CLI desde https://aws.amazon.com/cli["aws.amazon.com/cli"^] .
* Opcionalmente, tieneslink:../admin/configuring-load-balancer-endpoints.html["creó un punto final de balanceador de carga"] .  De lo contrario, conoce la dirección IP del nodo de almacenamiento al que desea conectarse y el número de puerto a utilizar. Ver link:../admin/summary-ip-addresses-and-ports-for-client-connections.html["Direcciones IP y puertos para conexiones de cliente"] .
* Tieneslink:../admin/creating-tenant-account.html["creó una cuenta de inquilino S3"] .
* Has iniciado sesión en el inquilino ylink:../tenant/creating-your-own-s3-access-keys.html["creó una clave de acceso"] .


Para obtener más detalles sobre estos pasos, consultelink:../admin/configuring-client-connections.html["Configurar conexiones de cliente"] .

.Pasos
. Configure los ajustes de AWS CLI para usar la cuenta que creó en el sistema StorageGRID :
+
.. Entrar al modo de configuración: `aws configure`
.. Introduzca el ID de la clave de acceso para la cuenta que ha creado.
.. Introduzca la clave de acceso secreta para la cuenta que ha creado.
.. Introduzca la región predeterminada a utilizar. Por ejemplo,  `us-east-1` .
.. Ingrese el formato de salida predeterminado a utilizar o presione *Enter* para seleccionar JSON.


. Crear un depósito.
+
Este ejemplo supone que configuró un punto final del balanceador de carga para usar la dirección IP 10.96.101.17 y el puerto 10443.

+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443
--no-verify-ssl create-bucket --bucket testbucket
----
+
Si el depósito se crea correctamente, se devuelve la ubicación del depósito, como se ve en el siguiente ejemplo:

+
[listing]
----
"Location": "/testbucket"
----
. Subir un objeto.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
put-object --bucket testbucket --key s3.pdf --body C:\s3-test\upload\s3.pdf
----
+
Si el objeto se carga correctamente, se devuelve un Etag, que es un hash de los datos del objeto.

. Enumere el contenido del depósito para verificar que se cargó el objeto.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
list-objects --bucket testbucket
----
. Eliminar el objeto.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
delete-object --bucket testbucket --key s3.pdf
----
. Eliminar el depósito.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
delete-bucket --bucket testbucket
----

