---
permalink: s3/get-storage-usage-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET storage usage request 
summary: La solicitud de uso de almacenamiento GET le indica la cantidad total de almacenamiento en uso por una cuenta y para cada depósito asociado con la cuenta. 
---
= Solicitud de uso de almacenamiento GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La solicitud de uso de almacenamiento GET le indica la cantidad total de almacenamiento en uso por una cuenta y para cada depósito asociado con la cuenta.

La cantidad de almacenamiento utilizada por una cuenta y sus depósitos se puede obtener mediante una solicitud ListBuckets modificada con el `x-ntap-sg-usage` parámetro de consulta.  El uso del almacenamiento del bucket se rastrea por separado de las solicitudes PUT y DELETE procesadas por el sistema.  Puede haber algún retraso antes de que los valores de uso coincidan con los valores esperados en función del procesamiento de las solicitudes, en particular si el sistema está bajo una carga pesada.

De forma predeterminada, StorageGRID intenta recuperar información de uso utilizando una consistencia global fuerte.  Si no se puede lograr una consistencia global fuerte, StorageGRID intenta recuperar la información de uso con una consistencia de sitio fuerte.

Debe tener el permiso s3:ListAllMyBuckets o ser la cuenta root para completar esta operación.



== Ejemplo de solicitud

[listing, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Ejemplo de respuesta

Este ejemplo muestra una cuenta que tiene cuatro objetos y 12 bytes de datos en dos grupos.  Cada contenedor contiene dos objetos y seis bytes de datos.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


== Control de versiones

Cada versión de objeto almacenada contribuirá a la `ObjectCount` y `DataBytes` valores en la respuesta.  Los marcadores de eliminación no se agregan a la `ObjectCount` total.

.Información relacionada
link:consistency-controls.html["Valores de consistencia"]
