---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: Puede utilizar la solicitud GET Object de S3 para recuperar un objeto de un bucket de S3. 
---
= Obtener objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la solicitud GetObject de S3 para recuperar un objeto de un depósito de S3.



== GetObject y objetos multipart

Puedes utilizar el `partNumber` parámetro de solicitud para recuperar una parte específica de un objeto multiparte o segmentado.  El `x-amz-mp-parts-count` El elemento de respuesta indica cuántas partes tiene el objeto.

Puedes configurar `partNumber` a 1 tanto para objetos segmentados/multiparte como para objetos no segmentados/no multiparte; sin embargo, el `x-amz-mp-parts-count` El elemento de respuesta solo se devuelve para objetos segmentados o multiparte.



== Caracteres UTF-8 en metadatos de usuario

StorageGRID no analiza ni interpreta caracteres UTF-8 escapados en metadatos definidos por el usuario.  Las solicitudes GET para un objeto con caracteres UTF-8 escapados en metadatos definidos por el usuario no devuelven el `x-amz-missing-meta` encabezado si el nombre o valor de la clave incluye caracteres no imprimibles.



== Encabezado de solicitud compatible

Se admite el siguiente encabezado de solicitud:

* `x-amz-checksum-mode`: Especificar `ENABLED`
+
El `Range` El encabezado no es compatible con `x-amz-checksum-mode` para ObtenerObjeto.  Cuando incluyes `Range` en la solicitud con `x-amz-checksum-mode` habilitado, StorageGRID no devuelve un valor de suma de comprobación en la respuesta.





== Encabezado de solicitud no compatible

El siguiente encabezado de solicitud no es compatible y devuelve `XNotImplemented` :

* `x-amz-website-redirect-location`




== Control de versiones

Si un `versionId` Si no se especifica el subrecurso, la operación obtiene la versión más reciente del objeto en un depósito versionado.  Si la versión actual del objeto es un marcador de eliminación, se devuelve un estado "No encontrado" con el `x-amz-delete-marker` encabezado de respuesta establecido en `true` .



== Encabezados de solicitud para cifrado del lado del servidor con claves de cifrado proporcionadas por el cliente (SSE-C)

Utilice los tres encabezados si el objeto está encriptado con una clave única que usted proporcionó.

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256` .
* `x-amz-server-side-encryption-customer-key`:Especifique su clave de cifrado para el objeto.
* `x-amz-server-side-encryption-customer-key-MD5`:Especifique el resumen MD5 de la clave de cifrado del objeto.



CAUTION: Las claves de cifrado que usted proporciona nunca se almacenan.  Si pierde una clave de cifrado, perderá el objeto correspondiente.  Antes de utilizar las claves proporcionadas por el cliente para proteger los datos de los objetos, revise las consideraciones enlink:using-server-side-encryption.html["Utilice cifrado del lado del servidor"] .



== Comportamiento de GetObject para objetos del grupo de almacenamiento en la nube

Si un objeto ha sido almacenado en unlink:../ilm/what-cloud-storage-pool-is.html["Grupo de almacenamiento en la nube"] , el comportamiento de una solicitud GetObject depende del estado del objeto. Verlink:head-object.html["Objeto principal"] Para más detalles.


NOTE: Si un objeto está almacenado en un grupo de almacenamiento en la nube y también existen una o más copias del objeto en la red, las solicitudes GetObject intentarán recuperar datos de la red, antes de recuperarlos del grupo de almacenamiento en la nube.

[cols="1a,1a"]
|===
| Estado del objeto | Comportamiento de GetObject 


 a| 
Objeto ingerido en StorageGRID pero aún no evaluado por ILM, u objeto almacenado en un grupo de almacenamiento tradicional o que utiliza codificación de borrado
 a| 
`200 OK`

Se recupera una copia del objeto.



 a| 
Objeto en el grupo de almacenamiento en la nube pero que aún no ha pasado a un estado no recuperable
 a| 
`200 OK`

Se recupera una copia del objeto.



 a| 
Objeto en transición a un estado no recuperable
 a| 
`403 Forbidden` ,  `InvalidObjectState`

Utilice unlink:post-object-restore.html["Restaurar objeto"] solicitud para restaurar el objeto a un estado recuperable.



 a| 
Objeto en proceso de restauración desde un estado no recuperable
 a| 
`403 Forbidden` ,  `InvalidObjectState`

Espere a que se complete la solicitud RestoreObject.



 a| 
Objeto completamente restaurado al grupo de almacenamiento en la nube
 a| 
`200 OK`

Se recupera una copia del objeto.

|===


=== Objetos multiparte o segmentados en un grupo de almacenamiento en la nube

Si cargó un objeto de varias partes o si StorageGRID dividió un objeto grande en segmentos, StorageGRID determina si el objeto está disponible en el grupo de almacenamiento en la nube mediante el muestreo de un subconjunto de las partes o segmentos del objeto.  En algunos casos, una solicitud GetObject podría devolver incorrectamente `200 OK` cuando algunas partes del objeto ya han sido trasladadas a un estado no recuperable o cuando algunas partes del objeto aún no han sido restauradas.

En estos casos:

* La solicitud GetObject podría devolver algunos datos pero detenerse a mitad de la transferencia.
* Una solicitud GetObject posterior podría devolver `403 Forbidden` .




== GetObject y replicación entre cuadrículas

Si estas usandolink:../admin/grid-federation-overview.html["federación de red"] ylink:../tenant/grid-federation-manage-cross-grid-replication.html["replicación entre redes"] está habilitado para un bucket, el cliente S3 puede verificar el estado de replicación de un objeto emitiendo una solicitud GetObject.  La respuesta incluye el StorageGRID específico `x-ntap-sg-cgr-replication-status` encabezado de respuesta, que tendrá uno de los siguientes valores:

[cols="1a,2a"]
|===
| Red | Estado de replicación 


 a| 
Fuente
 a| 
* *COMPLETADO*: La replicación fue exitosa.
* *PENDIENTE*: El objeto aún no ha sido replicado.
* *FALLO*: La replicación falló con un error permanente. Un usuario debe resolver el error.




 a| 
Destino
 a| 
*RÉPLICA*: El objeto fue replicado desde la cuadrícula de origen.

|===

NOTE: StorageGRID no es compatible con `x-amz-replication-status` encabezamiento.
