---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency 
summary: La solicitud de consistencia de depósito GET le permite determinar la consistencia que se aplica a un depósito en particular. 
---
= Obtener consistencia del bucket
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La solicitud de consistencia de depósito GET le permite determinar la consistencia que se aplica a un depósito en particular.

La consistencia predeterminada está configurada para garantizar la lectura después de la escritura para los objetos recién creados.

Debe tener el permiso s3:GetBucketConsistency o ser la cuenta root para completar esta operación.



== Ejemplo de solicitud

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Respuesta

En el XML de respuesta, `<Consistency>` devolverá uno de los siguientes valores:

[cols="1a,2a"]
|===
| Consistencia | Descripción 


 a| 
todo
 a| 
Todos los nodos reciben los datos inmediatamente o la solicitud fallará.



 a| 
fuerte-global
 a| 
Garantiza la consistencia de lectura tras escritura para todas las solicitudes de clientes en todos los sitios.



 a| 
sitio fuerte
 a| 
Garantiza la consistencia de lectura tras escritura para todas las solicitudes de clientes dentro de un sitio.



 a| 
lectura después de nueva escritura
 a| 
(Predeterminado) Proporciona consistencia de lectura después de escritura para objetos nuevos y consistencia eventual para actualizaciones de objetos.  Ofrece alta disponibilidad y garantías de protección de datos.  Recomendado para la mayoría de los casos.



 a| 
disponible
 a| 
Proporciona consistencia eventual tanto para objetos nuevos como para actualizaciones de objetos.  Para los depósitos S3, úselo solo cuando sea necesario (por ejemplo, para un depósito que contiene valores de registro que rara vez se leen, o para operaciones HEAD o GET en claves que no existen).  No compatible con depósitos S3 FabricPool .

|===


== Ejemplo de respuesta

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.Información relacionada
link:consistency-controls.html["Valores de consistencia"]
