---
permalink: s3/operations-on-the-service.html 
sidebar: sidebar 
keywords: listbuckets, get service, operations on the service 
summary: El sistema StorageGRID admite operaciones en el servicio. 
---
= Operaciones en el servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema StorageGRID admite las siguientes operaciones en el servicio.

[cols="1a,2a"]
|===
| Operación | Implementación 


 a| 
Lista de cubos

(anteriormente llamado Servicio GET)
 a| 
Implementado con todo el comportamiento de la API REST de Amazon S3.  Sujeto a cambios sin previo aviso.



 a| 
Uso de almacenamiento GET
 a| 
El StorageGRIDlink:get-storage-usage-request.html["Uso de almacenamiento GET"] La solicitud le indica la cantidad total de almacenamiento en uso por una cuenta y para cada depósito asociado con la cuenta.  Esta es una operación en el servicio con una ruta de / y un parámetro de consulta personalizado(`?x-ntap-sg-usage` ) agregado.



 a| 
OPCIONES /
 a| 
Las aplicaciones cliente pueden emitir `OPTIONS /` solicitudes al puerto S3 en un nodo de almacenamiento, sin proporcionar credenciales de autenticación S3, para determinar si el nodo de almacenamiento está disponible.  Puede utilizar esta solicitud para realizar monitoreo o para permitir que los balanceadores de carga externos identifiquen cuando un nodo de almacenamiento está inactivo.

|===