---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: Puede utilizar la solicitud S3 RestoreObject para restaurar un objeto almacenado en un grupo de almacenamiento en la nube. 
---
= Restaurar objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la solicitud S3 RestoreObject para restaurar un objeto almacenado en un grupo de almacenamiento en la nube.



== Tipo de solicitud admitido

StorageGRID solo admite solicitudes RestoreObject para restaurar un objeto.  No es compatible con el `SELECT` tipo de restauración.  Seleccione solicitudes de devolución `XNotImplemented` .



== Control de versiones

Opcionalmente, especifique `versionId` para restaurar una versión específica de un objeto en un depósito versionado.  Si no lo especifica `versionId` , se restaura la versión más reciente del objeto



== Comportamiento de RestoreObject en objetos del grupo de almacenamiento en la nube

Si un objeto ha sido almacenado en unlink:../ilm/what-cloud-storage-pool-is.html["Grupo de almacenamiento en la nube"] Una solicitud RestoreObject tiene el siguiente comportamiento, según el estado del objeto. Verlink:head-object.html["Objeto principal"] Para más detalles.


NOTE: Si un objeto está almacenado en un grupo de almacenamiento en la nube y también existen una o más copias del objeto en la red, no es necesario restaurar el objeto emitiendo una solicitud RestoreObject.  En cambio, la copia local se puede recuperar directamente, mediante una solicitud GetObject.

[cols="1a,2a"]
|===
| Estado del objeto | Comportamiento de RestoreObject 


 a| 
Objeto ingerido en StorageGRID pero aún no evaluado por ILM, o el objeto no está en un grupo de almacenamiento en la nube
 a| 
`403 Forbidden` ,  `InvalidObjectState`



 a| 
Objeto en el grupo de almacenamiento en la nube pero que aún no ha pasado a un estado no recuperable
 a| 
`200 OK`No se realizan cambios

*Nota*: Antes de que un objeto pase a un estado no recuperable, no se puede cambiar su `expiry-date` .



 a| 
Objeto en transición a un estado no recuperable
 a| 
`202 Accepted`Restaura una copia recuperable del objeto en el grupo de almacenamiento en la nube durante la cantidad de días especificada en el cuerpo de la solicitud.  Al final de este período, el objeto vuelve a un estado no recuperable.

Opcionalmente, utilice el `Tier` Elemento de solicitud para determinar cuánto tiempo tardará en finalizar el trabajo de restauración(`Expedited` , `Standard` , o `Bulk` ).  Si no lo especifica `Tier` , el `Standard` Se utiliza el nivel.

*Importante*: Si un objeto se ha transferido a S3 Glacier Deep Archive o el grupo de almacenamiento en la nube usa almacenamiento de blobs de Azure, no podrá restaurarlo mediante el `Expedited` nivel.  Se devuelve el siguiente error `403 Forbidden` , `InvalidTier` : `Retrieval option is not supported by this storage class` .



 a| 
Objeto en proceso de restauración desde un estado no recuperable
 a| 
`409 Conflict` ,  `RestoreAlreadyInProgress`



 a| 
Objeto completamente restaurado al grupo de almacenamiento en la nube
 a| 
`200 OK`

*Nota:* Si un objeto se ha restaurado a un estado recuperable, puede cambiar su `expiry-date` volviendo a emitir la solicitud RestoreObject con un nuevo valor para `Days` .  La fecha de restauración se actualiza en relación con el momento de la solicitud.

|===