---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: UploadPart, UploadPartCopy, multipart uploads, uploads, 
summary: La operación UploadPartCopy carga una parte de un objeto copiando datos de un objeto existente como fuente de datos. 
---
= Subir copia parcial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La operación UploadPartCopy carga una parte de un objeto copiando datos de un objeto existente como fuente de datos.

La operación UploadPartCopy se implementa con todo el comportamiento de la API REST de Amazon S3.  Sujeto a cambios sin previo aviso.

Esta solicitud lee y escribe los datos del objeto especificados en `x-amz-copy-source-range` dentro del sistema StorageGRID .

Se admiten los siguientes encabezados de solicitud:

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== Encabezados de solicitud para el cifrado del lado del servidor

Si especificó el cifrado SSE-C para la solicitud CreateMultipartUpload, también debe incluir los siguientes encabezados de solicitud en cada solicitud UploadPartCopy:

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256` .
* `x-amz-server-side-encryption-customer-key`:Especifique la misma clave de cifrado que proporcionó en la solicitud CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`:Especifique el mismo resumen MD5 que proporcionó en la solicitud CreateMultipartUpload.


Si el objeto de origen está cifrado mediante una clave proporcionada por el cliente (SSE-C), debe incluir los siguientes tres encabezados en la solicitud UploadPartCopy, para que el objeto pueda descifrarse y luego copiarse:

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`: Especificar `AES256` .
* `x-amz-copy-source​-server-side-encryption-customer-key`:Especifique la clave de cifrado que proporcionó cuando creó el objeto de origen.
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`:Especifique el resumen MD5 que proporcionó cuando creó el objeto de origen.



CAUTION: Las claves de cifrado que usted proporciona nunca se almacenan.  Si pierde una clave de cifrado, perderá el objeto correspondiente.  Antes de utilizar las claves proporcionadas por el cliente para proteger los datos de los objetos, revise las consideraciones enlink:using-server-side-encryption.html["Utilice cifrado del lado del servidor"] .



== Control de versiones

La carga multiparte consta de operaciones separadas para iniciar la carga, enumerar las cargas, cargar partes, ensamblar las partes cargadas y completar la carga.  Los objetos se crean (y se versionan si corresponde) cuando se realiza la operación CompleteMultipartUpload.
