---
permalink: s3/use-s3-select.html 
sidebar: sidebar 
keywords: use S3 Select, S3 Select 
summary: StorageGRID admite las siguientes cláusulas Select, tipos de datos, operadores y palabras clave reservadas de Amazon S3 para el comando SelectObjectContent. 
---
= Utilice S3 Select
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID admite las siguientes cláusulas Select de Amazon S3, tipos de datos y operadores paralink:select-object-content.html["Comando SelectObjectContent"] .


NOTE: Cualquier artículo que no esté en la lista no será compatible.

Para la sintaxis, véaselink:select-object-content.html["Seleccionar contenido del objeto"] .  Para obtener más información sobre S3 Select, consulte la https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html["Documentación de AWS para S3 Select"^] .

Solo las cuentas de inquilino que tienen S3 Select habilitado pueden emitir consultas SelectObjectContent. Ver ellink:../admin/manage-s3-select-for-tenant-accounts.html["Consideraciones y requisitos para el uso de S3 Select"] .



[[clauses]]
== Cláusulas

* Lista SELECT
* cláusula FROM
* cláusula WHERE
* Cláusula LIMIT




[[data-types]]
== Tipos de datos

* bool
* entero
* cadena
* flotar
* decimal, numérico
* marca de tiempo




[[operators]]
== Operadores



[[logical-operators]]
=== Operadores lógicos

* Y
* NO
* O




[[comparison-operators]]
=== Operadores de comparación

* <
* >
* <=
* >=
* =
* =
* <>
* !=
* ENTRE
* EN




[[pattern-matching-operators]]
=== Operadores de coincidencia de patrones

* COMO
* _
* %




[[unitary-operators]]
=== Operadores unitarios

* ES NULO
* NO ES NULO




[[math-operators]]
=== Operadores matemáticos

* +
* -
* *
* /
* %


StorageGRID sigue la precedencia del operador Amazon S3 Select.



[[aggregate-functions]]
== Funciones agregadas

* AVG()
* CONTAR(*)
* MÁX()
* MÍNIMO()
* SUMA()




[[conditional-functions]]
== Funciones condicionales

* CASO
* JUNTARSE
* NULLIF




[[conversion-functions]]
== Funciones de conversión

* CAST (para tipos de datos admitidos)




[[date-functions]]
== Funciones de fecha

* FECHA_AÑADIR
* FECHA_DIFF
* EXTRACTO
* A_CADENA
* HASTA_LA_MARCA_DE_TIEMPO
* UTCNOW




[[string-functions]]
== Funciones de cadena

* LONGITUD_CARACTER, LONGITUD_CARACTER
* MÁS BAJO
* SUBCADENA
* RECORTAR
* SUPERIOR

