---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: Los archivos MIB contienen definiciones e información sobre las propiedades de los recursos y servicios administrados para los nodos de su red.  Puede acceder a los archivos MIB que definen los objetos y las notificaciones para StorageGRID.  Estos archivos pueden ser útiles para monitorear su red. 
---
= Acceder a archivos MIB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los archivos MIB contienen definiciones e información sobre las propiedades de los recursos y servicios administrados para los nodos de su red.  Puede acceder a los archivos MIB que definen los objetos y las notificaciones para StorageGRID.  Estos archivos pueden ser útiles para monitorear su red.

Verlink:using-snmp-monitoring.html["Utilice la monitorización SNMP"] para obtener más información sobre los archivos SNMP y MIB.



== Acceder a archivos MIB

Siga estos pasos para acceder a los archivos MIB.

.Pasos
. Seleccione *CONFIGURACIÓN* > *Monitoreo* > *Agente SNMP*.
. En la página del agente SNMP, seleccione el archivo que desea descargar:
+
** *NETAPP-STORAGEGRID-MIB.txt*: Define la tabla de alertas y las notificaciones (trampas) accesibles en todos los nodos de administración.
** *ES-NETAPP-06-MIB.mib*: Define objetos y notificaciones para dispositivos basados en E-Series.
** *MIB_1_10.zip*: Define objetos y notificaciones para dispositivos con una interfaz BMC .
+
[]
====

TIP: También puede acceder a los archivos MIB en la siguiente ubicación en cualquier nodo StorageGRID : `/usr/share/snmp/mibs`

====


. Para extraer los OID de StorageGRID del archivo MIB:
+
.. Obtenga el OID de la raíz del MIB de StorageGRID :
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
Resultado: `.1.3.6.1.4.1.789.28669` (`28669` es siempre el OID para StorageGRID)

.. Busque el OID de StorageGRID en todo el árbol (usando `paste` para unir líneas):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: El `snmptranslate` El comando tiene muchas opciones que son útiles para explorar la MIB.  Este comando está disponible en cualquier nodo StorageGRID .



== Contenido del archivo MIB

Todos los objetos están bajo el OID StorageGRID .

[cols="1a,1a,2a"]
|===
| Nombre del objeto | Identificador de objeto (OID) | Descripción 


| .iso.org.dod.internet.  + empresas privadas.  + netapp.storagegrid | .1.3.6.1.4.1.789.28669  a| 
El módulo MIB para entidades NetApp StorageGRID .

|===


== Objetos MIB

[cols="1a,1a,2a"]
|===
| Nombre del objeto | Identificador de objeto (OID) | Descripción 


| recuento de alertas activas | .1.3.6.1.4.1. + 789.28669.1.3  a| 
El número de alertas activas en activeAlertTable.



| tabla de alerta activa | .1.3.6.1.4.1. + 789.28669.1.4  a| 
Una tabla de alertas activas en StorageGRID.



| ID de alerta activa | .1.3.6.1.4.1. + 789.28669.1.4.1.1  a| 
El ID de la alerta.  Único en el conjunto actual de alertas activas.



| nombreAlertaActiva | .1.3.6.1.4.1. + 789.28669.1.4.1.2  a| 
El nombre de la alerta.



| instancia de alerta activa | .1.3.6.1.4.1. + 789.28669.1.4.1.3  a| 
El nombre de la entidad que generó la alerta, normalmente el nombre del nodo.



| activeAlertSeverity | .1.3.6.1.4.1. + 789.28669.1.4.1.4  a| 
La gravedad de la alerta.



| hora de inicio de alerta activa | .1.3.6.1.4.1. + 789.28669.1.4.1.5  a| 
La fecha y hora en que se activó la alerta.

|===


== Tipos de notificaciones (trampas)

Todas las notificaciones incluyen las siguientes variables como varbinds:

* ID de alerta activa
* nombreAlertaActiva
* instancia de alerta activa
* activeAlertSeverity
* hora de inicio de alerta activa


[cols="1a,1a,2a"]
|===
| Tipo de notificación | Identificador de objeto (OID) | Descripción 


| alerta menor activa | .1.3.6.1.4.1. + 789.28669.0.6  a| 
Una alerta con gravedad menor



| alerta mayor activa | .1.3.6.1.4.1. + 789.28669.0.7  a| 
Una alerta con mayor gravedad



| alerta crítica activa | .1.3.6.1.4.1. + 789.28669.0.8  a| 
Una alerta con gravedad crítica

|===