---
permalink: monitor/disabling-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: Puede cambiar el estado habilitado/deshabilitado para una regla de alerta predeterminada o personalizada. 
---
= Deshabilitar reglas de alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar el estado habilitado/deshabilitado para una regla de alerta predeterminada o personalizada.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:../admin/admin-group-permissions.html["Administrar alertas o permisos de acceso root"] .


.Acerca de esta tarea
Cuando una regla de alerta está deshabilitada, sus expresiones no se evalúan y no se activan alertas.


CAUTION: En general, no se recomienda deshabilitar una regla de alerta predeterminada.  Si una regla de alerta está deshabilitada, es posible que no detecte un problema subyacente hasta que impida que se complete una operación crítica.

.Pasos
. Seleccione *ALERTAS* > *Reglas*.
+
Aparece la página Reglas de alerta.

. Seleccione el botón de opción correspondiente a la regla de alerta que desea deshabilitar o habilitar.
. Seleccione *Editar regla*.
+
Aparece el cuadro de diálogo Editar regla.

. Seleccione o desmarque la casilla de verificación *Habilitado* para determinar si esta regla de alerta está actualmente habilitada.
+
Si una regla de alerta está deshabilitada, sus expresiones no se evalúan y no se activan alertas.

+

NOTE: Si deshabilita la regla de alerta para una alerta actual, deberá esperar unos minutos hasta que la alerta deje de mostrarse como una alerta activa.

. Seleccione *Guardar*.
+
*Deshabilitado* aparece en la columna *Estado*.


