---
permalink: monitor/removing-custom-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: Puede eliminar una regla de alerta personalizada si ya no desea utilizarla. 
---
= Eliminar reglas de alerta personalizadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede eliminar una regla de alerta personalizada si ya no desea utilizarla.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:../admin/admin-group-permissions.html["Administrar alertas o permisos de acceso root"] .


.Pasos
. Seleccione *ALERTAS* > *Reglas*.
+
Aparece la página Reglas de alerta.

. Seleccione el botón de opción correspondiente a la regla de alerta personalizada que desea eliminar.
+
No se puede eliminar una regla de alerta predeterminada.

. Seleccione *Eliminar regla personalizada*.
+
Aparece un cuadro de diálogo de confirmación.

. Seleccione *Aceptar* para eliminar la regla de alerta.
+
Cualquier instancia activa de la alerta se resolverá en 10 minutos.


