---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: Los mensajes de auditoría pueden ayudarle a comprender mejor las operaciones detalladas de su sistema StorageGRID .  Puede utilizar registros de auditoría para solucionar problemas y evaluar el rendimiento. 
---
= Revisar los mensajes de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría pueden ayudarle a comprender mejor las operaciones detalladas de su sistema StorageGRID .  Puede utilizar registros de auditoría para solucionar problemas y evaluar el rendimiento.

Durante el funcionamiento normal del sistema, todos los servicios de StorageGRID generan mensajes de auditoría, como se indica a continuación:

* Los mensajes de auditoría del sistema están relacionados con el sistema de auditoría en sí, los estados de los nodos de la red, la actividad de las tareas de todo el sistema y las operaciones de respaldo del servicio.
* Los mensajes de auditoría de almacenamiento de objetos están relacionados con el almacenamiento y la administración de objetos dentro de StorageGRID, incluido el almacenamiento y la recuperación de objetos, las transferencias de nodo de red a nodo de red y las verificaciones.
* Los mensajes de auditoría de lectura y escritura del cliente se registran cuando una aplicación cliente S3 realiza una solicitud para crear, modificar o recuperar un objeto.
* Los mensajes de auditoría de administración registran las solicitudes de los usuarios a la API de administración.


Cada nodo de administración almacena mensajes de auditoría en archivos de texto.  El recurso compartido de auditoría contiene el archivo activo (audit.log), así como registros de auditoría comprimidos de días anteriores.  Cada nodo de la red también almacena una copia de la información de auditoría generada en el nodo.

Puede acceder a los archivos de registro de auditoría directamente desde la línea de comando del nodo de administración.

StorageGRID puede enviar información de auditoría de forma predeterminada, o puede cambiar el destino:

* StorageGRID tiene como valor predeterminado los destinos de auditoría de nodos locales.
* Las entradas del registro de auditoría de Grid Manager y Tenant Manager podrían enviarse a un nodo de almacenamiento.
* Opcionalmente, puede cambiar el destino de los registros de auditoría y enviar información de auditoría a un servidor syslog externo. Los registros locales de registros de auditoría continúan generándose y almacenándose cuando se configura un servidor syslog externo.
* link:../monitor/configure-audit-messages.html["Obtenga información sobre cómo configurar mensajes de auditoría y destinos de registro"] .


Para obtener detalles sobre el archivo de registro de auditoría, el formato de los mensajes de auditoría, los tipos de mensajes de auditoría y las herramientas disponibles para analizar los mensajes de auditoría, consultelink:../audit/index.html["Revisar los registros de auditoría"] .
