---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: Puede deshabilitar las notificaciones SNMP, actualizar cadenas de comunidad o agregar o eliminar direcciones de agentes, usuarios USM y destinos de trampa. 
---
= Actualizar el agente SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede deshabilitar las notificaciones SNMP, actualizar cadenas de comunidad o agregar o eliminar direcciones de agentes, usuarios USM y destinos de trampa.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:../admin/admin-group-permissions.html["Permiso de acceso root"] .


.Acerca de esta tarea
Verlink:configuring-snmp-agent.html["Configurar el agente SNMP"] para obtener detalles sobre cada campo en la página del agente SNMP.  Debes seleccionar *Guardar* en la parte inferior de la página para confirmar cualquier cambio que realices en cada pestaña.

.Pasos
. Seleccione *CONFIGURACIÓN* > *Monitoreo* > *Agente SNMP*.
+
Aparece la página del agente SNMP.

. Para deshabilitar el agente SNMP en todos los nodos de la red, desmarque la casilla *Habilitar SNMP* y seleccione *Guardar*.
+
Si vuelve a habilitar el agente SNMP, se conservarán todas las configuraciones de SNMP anteriores.

. Opcionalmente, actualice la información en la sección Configuración básica:
+
.. Según sea necesario, actualice el *Contacto del sistema* y la *Ubicación del sistema*.
.. De manera opcional, seleccione o desmarque la casilla de verificación *Habilitar notificaciones del agente SNMP* para controlar si el agente SNMP de StorageGRID envía notificaciones de captura e información.
+
Cuando esta casilla de verificación no está marcada, el agente SNMP admite acceso MIB de solo lectura, pero no envía notificaciones SNMP.

.. De manera opcional, seleccione o desmarque la casilla de verificación *Habilitar trampas de autenticación* para controlar si el agente SNMP de StorageGRID envía trampas de autenticación cuando recibe mensajes de protocolo autenticados incorrectamente.


. Si usa SNMPv1 o SNMPv2c, opcionalmente actualice o agregue una *Comunidad de solo lectura* en la sección Cadenas de la comunidad.
. Para actualizar los destinos de trampa, seleccione la pestaña Destinos de trampa en la sección Otras configuraciones.
+
Utilice esta pestaña para definir uno o más destinos para las notificaciones de captura o información de StorageGRID .  Cuando habilita el agente SNMP y selecciona *Guardar*, StorageGRID envía notificaciones a cada destino definido cuando se activan alertas.  También se envían notificaciones estándar para las entidades MIB-II compatibles (por ejemplo, ifDown y coldStart).

+
Para obtener detalles sobre qué ingresar, consultelink:../monitor/configuring-snmp-agent.html#create-trap-destinations["Crear destinos de trampa"] .

+
** Opcionalmente, actualice o elimine la comunidad de trampas predeterminada.
+
Si elimina la comunidad de trampa predeterminada, primero debe asegurarse de que todos los destinos de trampa existentes utilicen una cadena de comunidad personalizada.

** Para agregar un destino de trampa, seleccione *Crear*.
** Para editar un destino de trampa, seleccione el botón de opción y seleccione *Editar*.
** Para eliminar un destino de trampa, seleccione el botón de opción y seleccione *Eliminar*.
** Para confirmar los cambios, seleccione *Guardar* en la parte inferior de la página.


. Para actualizar las direcciones del agente, seleccione la pestaña Direcciones del agente en la sección Otras configuraciones.
+
Utilice esta pestaña para especificar una o más "direcciones de escucha".  Estas son las direcciones StorageGRID en las que el agente SNMP puede recibir consultas.

+
Para obtener detalles sobre qué ingresar, consultelink:../monitor/configuring-snmp-agent.html#create-agent-addresses["Crear direcciones de agentes"] .

+
** Para agregar una dirección de agente, seleccione *Crear*.
** Para editar la dirección de un agente, seleccione el botón de opción y seleccione *Editar*.
** Para eliminar una dirección de agente, seleccione el botón de opción y seleccione *Eliminar*.
** Para confirmar los cambios, seleccione *Guardar* en la parte inferior de la página.


. Para actualizar los usuarios de USM, seleccione la pestaña Usuarios de USM en la sección Otras configuraciones.
+
Utilice esta pestaña para definir los usuarios de USM que están autorizados a consultar la MIB o a recibir trampas e informes.

+
Para obtener detalles sobre qué ingresar, consultelink:../monitor/configuring-snmp-agent.html#create-usm-users["Crear usuarios de USM"] .

+
** Para agregar un usuario USM, seleccione *Crear*.
** Para editar un usuario USM, seleccione el botón de opción y seleccione *Editar*.
+
No se puede cambiar el nombre de usuario de un usuario USM existente.  Si necesita cambiar un nombre de usuario, debe eliminar el usuario y crear uno nuevo.

+

NOTE: Si agrega o elimina el ID de motor autorizado de un usuario y ese usuario está actualmente seleccionado para un destino, debe editar o eliminar el destino.  De lo contrario, se produce un error de validación al guardar la configuración del agente SNMP.

** Para eliminar un usuario de USM, seleccione el botón de opción y seleccione *Eliminar*.
+

NOTE: Si el usuario que eliminó está actualmente seleccionado para un destino de trampa, debe editar o eliminar el destino.  De lo contrario, se produce un error de validación al guardar la configuración del agente SNMP.

** Para confirmar los cambios, seleccione *Guardar* en la parte inferior de la página.


. Cuando haya actualizado la configuración del agente SNMP, seleccione *Guardar*.

