---
permalink: maintain/checking-storage-state-after-recovering-storage-volumes.html 
sidebar: sidebar 
keywords: storagegrid, storage volume recovery, storage state, storage volume 
summary: Después de recuperar los volúmenes de almacenamiento, debe verificar que el estado deseado del nodo de almacenamiento esté configurado en línea y asegurarse de que el estado estará en línea de manera predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento. 
---
= Comprobar el estado del almacenamiento después de recuperar volúmenes de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de recuperar los volúmenes de almacenamiento, debe verificar que el estado deseado del nodo de almacenamiento esté configurado en línea y asegurarse de que el estado estará en línea de manera predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Se ha recuperado el nodo de almacenamiento y se ha completado la recuperación de datos.


.Pasos
. Seleccione *SOPORTE* > *Herramientas* > *Topología de cuadrícula*.
. Verifique los valores de *Nodo de almacenamiento recuperado* > *LDR* > *Almacenamiento* > *Estado de almacenamiento - deseado* y *Estado de almacenamiento - actual*.
+
El valor de ambos atributos debe ser En línea.

. Si el Estado de almacenamiento - Deseado está configurado en Solo lectura, complete los siguientes pasos:
+
.. Haga clic en la pestaña *Configuración*.
.. En la lista desplegable *Estado de almacenamiento – Deseado*, seleccione *En línea*.
.. Haga clic en *Aplicar cambios*.
.. Haga clic en la pestaña *Descripción general* y confirme que los valores de *Estado de almacenamiento - Deseado* y *Estado de almacenamiento - Actual* estén actualizados a En línea.



