---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Después de recuperar un nodo de almacenamiento del dispositivo, debe verificar que el estado deseado del nodo de almacenamiento del dispositivo esté configurado en línea y asegurarse de que el estado sea en línea de manera predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento. 
---
= Comprobar el estado del almacenamiento después de recuperar el nodo de almacenamiento del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de recuperar un nodo de almacenamiento del dispositivo, debe verificar que el estado deseado del nodo de almacenamiento del dispositivo esté configurado en línea y asegurarse de que el estado sea en línea de manera predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Se ha recuperado el nodo de almacenamiento y se ha completado la recuperación de datos.


.Pasos
. Seleccione *SOPORTE* > *Herramientas* > *Topología de cuadrícula*.
. Verifique los valores de *Nodo de almacenamiento recuperado* > *LDR* > *Almacenamiento* > *Estado de almacenamiento - deseado* y *Estado de almacenamiento - actual*.
+
El valor de ambos atributos debe ser En línea.

. Si el Estado de almacenamiento - Deseado está configurado en Solo lectura, complete los siguientes pasos:
+
.. Haga clic en la pestaña *Configuración*.
.. En la lista desplegable *Estado de almacenamiento – Deseado*, seleccione *En línea*.
.. Haga clic en *Aplicar cambios*.
.. Haga clic en la pestaña *Descripción general* y confirme que los valores de *Estado de almacenamiento - Deseado* y *Estado de almacenamiento - Actual* estén actualizados a En línea.



