---
permalink: maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission admin node, decommission gateway node 
summary: Revise las consideraciones para dar de baja un nodo de administración o un nodo de puerta de enlace. 
---
= Consideraciones para el desmantelamiento de nodos de administración o de puerta de enlace
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise las consideraciones para dar de baja un nodo de administración o un nodo de puerta de enlace.



== Consideraciones para el nodo de administración

* No puedes desmantelar el nodo de administración principal.
* No se puede desmantelar un nodo de administración si una de sus interfaces de red es parte de un grupo de alta disponibilidad (HA).  Primero debe eliminar las interfaces de red del grupo HA. Vea las instrucciones paralink:../admin/managing-high-availability-groups.html["gestión de grupos de alta disponibilidad"] .
* Según sea necesario, puede cambiar de forma segura las políticas de ILM mientras desmantela un nodo de administración.
* Si desmantela un nodo de administración y el inicio de sesión único (SSO) está habilitado para su sistema StorageGRID , debe recordar quitar la confianza de usuario autenticado del nodo de los Servicios de federación de Active Directory (AD FS).
* Si utilizaslink:../admin/grid-federation-overview.html["federación de red"] Asegúrese de que la dirección IP del nodo que está desmantelando no se haya especificado para una conexión de federación de red.
* Cuando desmantela un nodo de administración desconectado, perderá los registros de auditoría de ese nodo; sin embargo, estos registros también deben existir en el nodo de administración principal.




== Consideraciones para el nodo de enlace

* No se puede desmantelar un nodo de puerta de enlace si una de sus interfaces de red es parte de un grupo de alta disponibilidad (HA).  Primero debe eliminar las interfaces de red del grupo HA. Vea las instrucciones paralink:../admin/managing-high-availability-groups.html["gestión de grupos de alta disponibilidad"] .
* Según sea necesario, puede cambiar de forma segura las políticas de ILM mientras desmantela un nodo de puerta de enlace.
* Si utilizaslink:../admin/grid-federation-overview.html["federación de red"] Asegúrese de que la dirección IP del nodo que está desmantelando no se haya especificado para una conexión de federación de red.
* Puede desmantelar de forma segura un nodo de puerta de enlace mientras esté desconectado.

