---
permalink: maintain/index.html 
sidebar: sidebar 
keywords: maintain overview, maintenance overview, about maintain, about maintenance 
summary: Las tareas de mantenimiento de la red incluyen el desmantelamiento de un nodo o sitio, el cambio de nombre de una red, un nodo o un sitio y el mantenimiento de la red.  También puede realizar procedimientos de host y middleware y procedimientos de nodo de red. 
---
= Mantenimiento de la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las tareas de mantenimiento de la red incluyen el desmantelamiento de un nodo o sitio, el cambio de nombre de una red, un nodo o un sitio y el mantenimiento de redes.  También puede realizar procedimientos de host y middleware y procedimientos de nodo de red.


NOTE: En estas instrucciones, "Linux" se refiere a una implementación de Red Hat® Enterprise Linux®, Ubuntu® o Debian®. Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] .



== Antes de empezar

* Tiene un amplio conocimiento del sistema StorageGRID .
* Ha revisado la topología de su sistema StorageGRID y comprende la configuración de la red.
* Usted comprende que debe seguir todas las instrucciones exactamente y prestar atención a todas las advertencias.
* Usted comprende que los procedimientos de mantenimiento no descritos no son compatibles o requieren una contratación de servicios.




== Procedimientos de mantenimiento de electrodomésticos

Para conocer los procedimientos de hardware, consulte la https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["Instrucciones de mantenimiento para su dispositivo StorageGRID"^] .
