---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Puede supervisar el estado de los trabajos de reparación mediante el `repair-data` script desde la línea de comandos.' 
---
= Supervisar trabajos de reparación de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar el estado de los trabajos de reparación mediante el `repair-data` script desde la línea de comandos.

Estos incluyen trabajos que inició manualmente o trabajos que StorageGRID inició automáticamente como parte de un procedimiento de desmantelamiento.


NOTE: Si está ejecutando trabajos de restauración de volumen,link:../maintain/restoring-volume.html["Monitorear el progreso y ver un historial de esos trabajos en el Administrador de cuadrícula"] en cambio.

Monitorear el estado de `repair-data` trabajos en función de si utiliza *datos replicados*, *datos codificados por borrado (EC)* o ambos.

[role="tabbed-block"]
====
.Datos replicados
--
* Para obtener un porcentaje estimado de finalización de la reparación replicada, agregue el `show-replicated-repair-status` Opción para el comando reparar-datos.
+
`repair-data show-replicated-repair-status`

* Para determinar si las reparaciones están completas:
+
.. Seleccione *NODOS* > *_Nodo de almacenamiento en reparación_* > *ILM*.
.. Revise los atributos en la sección Evaluación.  Cuando se completan las reparaciones, el atributo *En espera - Todo* indica 0 objetos.


* Para supervisar la reparación con más detalle:
+
.. Seleccione *SOPORTE* > *Herramientas* > *Topología de cuadrícula*.
.. Seleccione *_grid_* > *_Nodo de almacenamiento en reparación_* > *LDR* > *Almacén de datos*.
.. Utilice una combinación de los siguientes atributos para determinar, lo mejor posible, si las reparaciones replicadas están completas.
+

NOTE: Pueden existir inconsistencias en Cassandra y no se realiza un seguimiento de las reparaciones fallidas.

+
*** *Reparaciones intentadas (XRPA)*: utilice este atributo para rastrear el progreso de las reparaciones replicadas.  Este atributo aumenta cada vez que un nodo de almacenamiento intenta reparar un objeto de alto riesgo.  Cuando este atributo no aumenta durante un período más largo que el período de escaneo actual (proporcionado por el atributo *Período de escaneo – Estimado*), significa que el escaneo ILM no encontró objetos de alto riesgo que necesiten reparación en ningún nodo.
+

NOTE: Los objetos de alto riesgo son objetos que corren el riesgo de perderse por completo.  Esto no incluye objetos que no satisfacen su configuración ILM.

*** *Período de escaneo estimado (XSCM)*: utilice este atributo para estimar cuándo se aplicará un cambio de política a los objetos ingeridos previamente.  Si el atributo *Reparaciones intentadas* no aumenta durante un período más largo que el período de escaneo actual, es probable que se realicen reparaciones replicadas.  Tenga en cuenta que el período de escaneo puede cambiar.  El atributo *Período de escaneo estimado (XSCM)* se aplica a toda la cuadrícula y es el máximo de todos los períodos de escaneo de nodos.  Puede consultar el historial de atributos *Período de escaneo – Estimado* de la cuadrícula para determinar un período de tiempo apropiado.






--
.Datos codificados por borrado (EC)
--
Para supervisar la reparación de datos codificados por borrado y volver a intentar cualquier solicitud que pueda haber fallado:

. Determinar el estado de las reparaciones de datos codificados por borrado:
+
** Seleccione *SOPORTE* > *Herramientas* > *Métricas* para ver el tiempo estimado de finalización y el porcentaje de finalización del trabajo actual. Luego, seleccione *Descripción general de EC* en la sección Grafana. Consulte los paneles *Tiempo estimado de finalización del trabajo de Grid EC* y *Porcentaje de trabajo de Grid EC completado*.
** Utilice este comando para ver el estado de un elemento específico. `repair-data` operación:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilice este comando para enumerar todas las reparaciones:
+
`repair-data show-ec-repair-status`

+
La salida enumera información, incluyendo `repair ID` , para todas las reparaciones realizadas anteriormente y actualmente en curso.



. Si la salida muestra que la operación de reparación falló, utilice el `--repair-id` Opción para reintentar la reparación.
+
Este comando vuelve a intentar una reparación de nodo fallida, utilizando el ID de reparación 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando vuelve a intentar una reparación de volumen fallida, utilizando el ID de reparación 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====