---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: Al recuperar un nodo de red que estaba alojado en un dispositivo de servicios, primero debe preparar el dispositivo para la reinstalación del software StorageGRID . 
---
= Preparar el dispositivo para la reinstalación (solo reemplazo de plataforma)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al recuperar un nodo de red que estaba alojado en un dispositivo de servicios, primero debe preparar el dispositivo para la reinstalación del software StorageGRID .

Realice este procedimiento solo si está reemplazando un nodo fallido que estaba alojado en un dispositivo de servicios.  No siga estos pasos si el nodo fallido originalmente estaba alojado en VMware o en un host Linux.

.Pasos
. Inicie sesión en el nodo de red fallido:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Prepare el dispositivo para la instalación del software StorageGRID .  Ingresar: `sgareinstall`
. Cuando se le solicite continuar, ingrese: `y`
+
El dispositivo se reinicia y su sesión SSH finaliza.  Por lo general, el instalador del dispositivo StorageGRID tarda unos 5 minutos en estar disponible, aunque en algunos casos es posible que tengas que esperar hasta 30 minutos.

+
El dispositivo de servicios se reinicia y los datos en el nodo de la red ya no son accesibles.  Las direcciones IP configuradas durante el proceso de instalación original deben permanecer intactas; sin embargo, se recomienda que lo confirme una vez completado el procedimiento.

+
Después de ejecutar el `sgareinstall` comando, se eliminan todas las cuentas, contraseñas y claves SSH proporcionadas por StorageGRID y se generan nuevas claves de host.


