---
permalink: maintain/rebooting-grid-node-from-command-shell.html 
sidebar: sidebar 
keywords: storagegrid, recover, reboot node, command shell reboot 
summary: Si necesita supervisar la operación de reinicio más de cerca o si no puede acceder al Administrador de red, puede iniciar sesión en el nodo de red y ejecutar el comando de reinicio del Administrador de servidor desde el shell de comandos. 
---
= Reiniciar el nodo de la red desde el shell de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si necesita supervisar la operación de reinicio más de cerca o si no puede acceder al Administrador de red, puede iniciar sesión en el nodo de red y ejecutar el comando de reinicio del Administrador de servidor desde el shell de comandos.

.Antes de empezar
Tú tienes el `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de la red:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Opcionalmente, detener servicios: `service servermanager stop`
+
Detener los servicios es un paso opcional, pero recomendado.  Los servicios pueden tardar hasta 15 minutos en apagarse, y es posible que desee iniciar sesión en el sistema de forma remota para supervisar el proceso de apagado antes de reiniciar el nodo en el siguiente paso.

. Reiniciar el nodo de la red: `reboot`
. Cerrar sesión en el shell de comandos: `exit`

