---
permalink: maintain/recovering-storagegrid-appliance-storage-node.html 
sidebar: sidebar 
keywords: recover, appliance storage node failure, workflow 
summary: El procedimiento para recuperar un nodo de almacenamiento de un dispositivo StorageGRID fallido es el mismo independientemente de si se está recuperando de la pérdida de la unidad del sistema o de la pérdida de volúmenes de almacenamiento únicamente. 
---
= Advertencias para recuperar nodos de almacenamiento del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El procedimiento para recuperar un nodo de almacenamiento de un dispositivo StorageGRID fallido es el mismo independientemente de si se está recuperando de la pérdida de la unidad del sistema o de la pérdida de volúmenes de almacenamiento únicamente.


CAUTION: Si más de un nodo de almacenamiento ha fallado (o está fuera de línea), comuníquese con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podría ocurrir pérdida de datos.


CAUTION: Si esta es la segunda falla del nodo de almacenamiento en menos de 15 días después de una falla o recuperación del nodo de almacenamiento, comuníquese con el soporte técnico.  Reconstruir Cassandra en dos o más nodos de almacenamiento dentro de 15 días puede provocar la pérdida de datos.


NOTE: Si ha fallado más de un nodo de almacenamiento en un sitio, es posible que se requiera un procedimiento de recuperación del sitio. Ver link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"] .


CAUTION: Si las reglas de ILM están configuradas para almacenar solo una copia replicada y la copia existe en un volumen de almacenamiento que ha fallado, no podrá recuperar el objeto.


NOTE: Para conocer los procedimientos de mantenimiento de hardware, como las instrucciones para reemplazar un controlador o reinstalar SANtricity OS, consulte la https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["Instrucciones de mantenimiento para su dispositivo de almacenamiento"^] .
