---
permalink: maintain/recovering-from-admin-node-failures.html 
sidebar: sidebar 
keywords: recover, admin node failure, workflow 
summary: El proceso de recuperación de un nodo de administración depende de si es el nodo de administración principal o un nodo de administración no principal. 
---
= Recuperación del nodo de administración primario o no primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El proceso de recuperación de un nodo de administración depende de si es el nodo de administración principal o un nodo de administración no principal.

Los pasos de alto nivel para recuperar un nodo de administración primario o no primario son los mismos, aunque los detalles de los pasos difieren.

Siga siempre el procedimiento de recuperación correcto para el nodo de administración que está recuperando.  Los procedimientos parecen iguales a alto nivel, pero difieren en los detalles.

.Opciones
* link:recovering-from-primary-admin-node-failures.html["Recuperarse de fallas del nodo de administración principal"]
* link:recovering-from-non-primary-admin-node-failures.html["Recuperarse de fallas del nodo de administración no principal"]

