---
permalink: maintain/recovering-from-non-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, non-primary admin node failure 
summary: 'Debe completar las siguientes tareas para recuperarse de una falla del nodo de administración no principal.  Un nodo de administración aloja el servicio del nodo de administración de configuración (CMN) y se conoce como el nodo de administración principal.  Aunque puede tener varios nodos de administración, cada sistema StorageGRID incluye solo un nodo de administración principal.  Todos los demás nodos de administración son nodos de administración no principales.' 
---
= Recuperarse de fallas del nodo de administración no principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar las siguientes tareas para recuperarse de una falla del nodo de administración no principal.  Un nodo de administración aloja el servicio del nodo de administración de configuración (CMN) y se conoce como el nodo de administración principal.  Aunque puede tener varios nodos de administración, cada sistema StorageGRID incluye solo un nodo de administración principal.  Todos los demás nodos de administración son nodos de administración no principales.

Siga estos pasos de alto nivel para recuperar un nodo de administración no principal:

. link:copying-audit-logs-from-failed-non-primary-admin-node.html["Copiar registros de auditoría del nodo de administración no principal que falló"]
. link:replacing-non-primary-admin-node.html["Reemplazar el nodo de administración no principal"]
. link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Seleccione Iniciar recuperación para configurar el nodo de administración no principal"]
. link:restoring-audit-log-on-recovered-non-primary-admin-node.html["Restaurar el registro de auditoría en un nodo de administración no principal recuperado"]
. link:restoring-admin-node-database-non-primary-admin-node.html["Restaurar la base de datos del nodo de administración al recuperar un nodo de administración no principal"]
. link:restoring-prometheus-metrics-non-primary-admin-node.html["Restaurar las métricas de Prometheus al recuperar un nodo de administración no principal"]

