---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: El procedimiento para recuperar un nodo de almacenamiento fallido depende del tipo de falla y del tipo de nodo de almacenamiento que ha fallado. 
---
= Recuperarse de fallos del nodo de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El procedimiento para recuperar un nodo de almacenamiento fallido depende del tipo de falla y del tipo de nodo de almacenamiento que ha fallado.

Utilice esta tabla para seleccionar el procedimiento de recuperación para un nodo de almacenamiento fallido.

[cols="1a,1a,1a"]
|===
| Asunto | Acción | Notas 


 a| 
* Más de un nodo de almacenamiento ha fallado.
* Un segundo nodo de almacenamiento falló menos de 15 días después de una falla o recuperación del nodo de almacenamiento.
+
Esto incluye el caso en el que un nodo de almacenamiento falla mientras la recuperación de otro nodo de almacenamiento aún está en proceso.


 a| 
Póngase en contacto con el soporte técnico.
 a| 
La recuperación de más de un nodo de almacenamiento (o más de un nodo de almacenamiento en un plazo de 15 días) podría afectar la integridad de la base de datos de Cassandra, lo que puede provocar la pérdida de datos.

El soporte técnico puede determinar cuándo es seguro comenzar la recuperación de un segundo nodo de almacenamiento.

*Nota*: Si más de un nodo de almacenamiento que contiene el servicio ADC falla en un sitio, perderá todas las solicitudes de servicio de plataforma pendientes para ese sitio.



 a| 
Ha fallado más de un nodo de almacenamiento en un sitio o ha fallado un sitio entero.
 a| 
Póngase en contacto con el soporte técnico. Podría ser necesario realizar un procedimiento de recuperación del sitio.
 a| 
El soporte técnico evaluará su situación y desarrollará un plan de recuperación. Ver link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"] .



 a| 
Se ha producido un error en un nodo de almacenamiento del dispositivo.
 a| 
link:recovering-storagegrid-appliance-storage-node.html["Recuperar el nodo de almacenamiento del dispositivo"]
 a| 
El procedimiento de recuperación de los nodos de almacenamiento del dispositivo es el mismo para todas las fallas.



 a| 
Uno o más volúmenes de almacenamiento han fallado, pero la unidad del sistema está intacta
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Recuperarse de una falla del volumen de almacenamiento donde la unidad del sistema está intacta"]
 a| 
Este procedimiento se utiliza para nodos de almacenamiento basados en software.



 a| 
La unidad del sistema ha fallado.
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["Recuperarse de una falla de la unidad del sistema"]
 a| 
El procedimiento de reemplazo de nodo depende de la plataforma de implementación y de si algún volumen de almacenamiento también ha fallado.

|===

NOTE: Algunos procedimientos de recuperación de StorageGRID utilizan Reaper para manejar las reparaciones de Cassandra.  Las reparaciones se producen automáticamente tan pronto como se hayan iniciado los servicios relacionados o requeridos.  Es posible que notes que la salida del script menciona "reaper" o "reparación de Cassandra".  Si ve un mensaje de error que indica que la reparación ha fallado, ejecute el comando indicado en el mensaje de error.
