---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: Debe completar una serie de tareas para recuperar un nodo de almacenamiento basado en software donde uno o más volúmenes de almacenamiento en el nodo de almacenamiento han fallado, pero la unidad del sistema está intacta.  Si solo fallaron los volúmenes de almacenamiento, el nodo de almacenamiento aún estará disponible para el sistema StorageGRID . 
---
= Recuperarse de una falla del volumen de almacenamiento donde la unidad del sistema está intacta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar una serie de tareas para recuperar un nodo de almacenamiento basado en software donde uno o más volúmenes de almacenamiento en el nodo de almacenamiento han fallado, pero la unidad del sistema está intacta.  Si solo fallaron los volúmenes de almacenamiento, el nodo de almacenamiento aún estará disponible para el sistema StorageGRID .


NOTE: Este procedimiento de recuperación se aplica únicamente a los nodos de almacenamiento basados en software.  Si los volúmenes de almacenamiento han fallado en un nodo de almacenamiento del dispositivo, utilice el procedimiento del dispositivo en su lugar:link:recovering-storagegrid-appliance-storage-node.html["Recuperar el nodo de almacenamiento del dispositivo"] .

Este procedimiento de recuperación incluye las siguientes tareas:

* link:reviewing-warnings-about-storage-volume-recovery.html["Revisar las advertencias para la recuperación del volumen de almacenamiento"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identificar y desmontar volúmenes de almacenamiento fallidos"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Recuperar los volúmenes y reconstruir la base de datos de Cassandra"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaurar datos de objetos"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Comprobar el estado de almacenamiento"]

