---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: Según sea necesario, puede cambiar los nombres para mostrar que se muestran en todo el Administrador de cuadrícula para toda la cuadrícula, cada sitio y cada nodo.  Puede actualizar los nombres para mostrar de forma segura y cuando lo necesite. 
---
= Utilice el procedimiento de cambio de nombre
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Según sea necesario, puede cambiar los nombres para mostrar que se muestran en todo el Administrador de cuadrícula para toda la cuadrícula, cada sitio y cada nodo.  Puede actualizar los nombres para mostrar de forma segura y cuando lo necesite.



== ¿Cuál es el procedimiento de cambio de nombre?

Cuando instala StorageGRID inicialmente, especifica un nombre para la red, cada sitio y cada nodo.  Estos nombres iniciales se conocen como _nombres del sistema_ y son los nombres que se muestran inicialmente en StorageGRID.

Los nombres de sistema son necesarios para las operaciones internas de StorageGRID y no se pueden cambiar. Sin embargo, puede utilizar el procedimiento de cambio de nombre para definir nuevos _nombres para mostrar_ para la cuadrícula, cada sitio y cada nodo.  Estos nombres para mostrar aparecen en varias ubicaciones de StorageGRID en lugar de (o en algunos casos, además de) los nombres del sistema subyacente.

Utilice el procedimiento de cambio de nombre para corregir errores tipográficos, implementar una convención de nomenclatura diferente o indicar que un sitio y todos sus nodos han sido reubicados.  A diferencia de los nombres de sistema, los nombres para mostrar se pueden actualizar cuando sea necesario y sin afectar las operaciones de StorageGRID .



== ¿Dónde aparecen los nombres del sistema y de la pantalla?

La siguiente tabla resume dónde se muestran los nombres del sistema y los nombres para mostrar en la interfaz de usuario de StorageGRID y en los archivos de StorageGRID .

[cols="2a,2a,3a"]
|===
| Ubicación | Nombre del sistema | Nombre para mostrar 


 a| 
Páginas del administrador de cuadrícula
 a| 
Se muestra a menos que se cambie el nombre del elemento
 a| 
Si se cambia el nombre de un elemento, se muestra en lugar del nombre del sistema en estas ubicaciones:

* Consola
* Página de nodos
* Páginas de configuración para grupos de alta disponibilidad, puntos finales de balanceador de carga, interfaces VLAN, servidores de administración de claves, contraseñas de red y control de firewall
* Alertas
* Definiciones de grupos de almacenamiento
* Página de búsqueda de metadatos de objetos
* Páginas relacionadas con los procedimientos de mantenimiento, incluidas actualizaciones, revisiones, actualizaciones del sistema operativo SANtricity , desmantelamiento, expansión, recuperación y verificación de existencia de objetos.
* Páginas de soporte (registros y diagnósticos)
* Página de inicio de sesión único, junto al nombre de host del nodo de administración en la tabla de detalles del nodo de administración




 a| 
*NODOS* > Pestaña *Descripción general* de un nodo
 a| 
Siempre mostrado
 a| 
Se muestra solo si se cambia el nombre del elemento



 a| 
Páginas heredadas en el Administrador de cuadrícula (por ejemplo, *SOPORTE* > *Topología de cuadrícula*)
 a| 
Mostrado
 a| 
No se muestra



 a| 
API de *salud del nodo*
 a| 
Siempre regresaba
 a| 
Se devuelve solo si se cambia el nombre del artículo



 a| 
Aviso al usar SSH para acceder a un nodo
 a| 
Se muestra como nombre principal a menos que se haya cambiado el nombre del elemento:

`admin@SYSTEM-NAME: ~ $`

Incluido entre paréntesis cuando se cambia el nombre del elemento:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
Se muestra como nombre principal cuando se cambia el nombre del elemento:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`archivo en el paquete de recuperación
 a| 
Se muestra como `Server Name`
 a| 
Se muestra como `Display Name`



 a| 
`/etc/hosts`archivo en todos los nodos

Por ejemplo:

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
Siempre se muestra en la segunda columna
 a| 
Cuando se cambia el nombre del elemento, se muestra en la cuarta columna



 a| 
`topology-display-names.json`, incluido con los datos de AutoSupport
 a| 
No incluido
 a| 
Vacío a menos que se hayan cambiado el nombre de los elementos; de lo contrario, asigna los identificadores de cuadrícula, sitio y nodo a sus nombres para mostrar.

|===


== Requisitos del nombre para mostrar

Antes de utilizar este procedimiento, revise los requisitos para los nombres para mostrar.



=== Nombres para mostrar de los nodos

Los nombres para mostrar de los nodos deben seguir estas reglas:

* Debe ser único en todo el sistema StorageGRID .
* No puede ser el mismo que el nombre del sistema de ningún otro elemento en su sistema StorageGRID .
* Debe contener al menos 1 y no más de 32 caracteres.
* Puede contener números, guiones (-) y letras mayúsculas y minúsculas.
* Puede comenzar o terminar con una letra o un número, pero no puede comenzar o terminar con un guion.
* No pueden ser todos números.
* No distinguen entre mayúsculas y minúsculas.  Por ejemplo, `DC1-ADM` y `dc1-adm` se consideran duplicados.


Puede cambiar el nombre de un nodo con un nombre para mostrar que haya sido utilizado previamente por un nodo diferente, siempre y cuando el cambio de nombre no genere un nombre para mostrar o un nombre de sistema duplicados.



=== Nombres para mostrar en la cuadrícula y los sitios

Los nombres para mostrar de la cuadrícula y los sitios siguen las mismas reglas con estas excepciones:

* Puede incluir espacios.
* Puede incluir estos caracteres especiales: `= - _ : , . @ !`
* Puede comenzar y terminar con caracteres especiales, incluidos guiones.
* Pueden ser todos números o caracteres especiales.




== Prácticas recomendadas para nombres para mostrar

Si planea cambiar el nombre de varios elementos, documente su esquema de nombres general antes de utilizar este procedimiento.  Piense en un sistema que garantice que los nombres sean únicos, consistentes y fáciles de entender a simple vista.

Puede utilizar cualquier convención de nomenclatura que se ajuste a los requisitos de su organización.  Tenga en cuenta estas sugerencias básicas de qué incluir:

* *Indicador de sitio*: si tiene varios sitios, agregue un código de sitio a cada nombre de nodo.
* *Tipo de nodo*: Los nombres de los nodos generalmente indican el tipo del nodo.  Puedes utilizar abreviaturas como `s` , `adm` , y `gw` (Nodo de almacenamiento, Nodo de administración y Nodo de puerta de enlace).
* *Número de nodo*: si un sitio contiene más de un nodo de un tipo particular, agregue un número único al nombre de cada nodo.


Piénselo dos veces antes de agregar detalles específicos a los nombres que probablemente cambiarán con el tiempo.  Por ejemplo, no incluya direcciones IP en los nombres de los nodos porque estas direcciones pueden cambiarse.  De manera similar, las ubicaciones de los racks o los números de modelo de los dispositivos pueden cambiar si usted mueve el equipo o actualiza el hardware.



=== Ejemplos de nombres para mostrar

Supongamos que su sistema StorageGRID tiene tres centros de datos y nodos de diferentes tipos en cada centro de datos.  Tus nombres para mostrar podrían ser tan simples como estos:

* *Red*: `StorageGRID Deployment`
* *Primer sitio*: `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *Segundo sitio*: `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *Tercer sitio*: `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



