---
permalink: maintain/replacing-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace storage node, replacing storage node 
summary: Si la unidad del sistema ha fallado, primero debe reemplazar el nodo de almacenamiento. 
---
= Reemplazar el nodo de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la unidad del sistema ha fallado, primero debe reemplazar el nodo de almacenamiento.

Debe seleccionar el procedimiento de reemplazo de nodo para su plataforma.  Los pasos para reemplazar un nodo son los mismos para todos los tipos de nodos de la red.


NOTE: Este procedimiento se aplica únicamente a los nodos de almacenamiento basados en software.  Debes seguir un procedimiento diferente paralink:recovering-storagegrid-appliance-storage-node.html["recuperar un nodo de almacenamiento del dispositivo"] .

*Linux:* Si no está seguro de si la unidad de su sistema ha fallado, siga las instrucciones para reemplazar el nodo para determinar qué pasos de recuperación son necesarios.

[cols="1a,2a"]
|===
| Plataforma | Procedimiento 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Reemplazar un nodo de VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Reemplazar un nodo Linux"]



 a| 
OpenStack
 a| 
Los archivos de disco de máquina virtual y los scripts proporcionados por NetApp para OpenStack ya no son compatibles con las operaciones de recuperación.  Si necesita recuperar un nodo que se ejecuta en una implementación de OpenStack, descargue los archivos para su sistema operativo Linux.  A continuación, siga el procedimiento paralink:all-node-types-replacing-linux-node.html["Reemplazar un nodo Linux"] .

|===