---
permalink: maintain/restoring-existing-nodes.html 
sidebar: sidebar 
keywords: recover, restore node to host, node configuration file, start host service 
summary: Para restaurar un nodo de red fallido en un nuevo host Linux, realice estos pasos para restaurar el archivo de configuración del nodo. 
---
= Restaurar los nodos de la red en el host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para restaurar un nodo de red fallido en un nuevo host Linux, realice estos pasos para restaurar el archivo de configuración del nodo.

. <<restore-validate-grid-nodes,Restaurar y validar el nodo>>restaurando el archivo de configuración del nodo.  Para una nueva instalación, se crea un archivo de configuración de nodo para cada nodo de la red que se instalará en un host.  Al restaurar un nodo de la red a un host de reemplazo, se restaura o reemplaza el archivo de configuración del nodo para cualquier nodo de la red que haya fallado.
. <<start-storagegrid-host-service,Iniciar el servicio de host de StorageGRID>> .
. Según sea necesario,<<recover-nodes-fail-start,recuperar cualquier nodo que no pueda iniciarse>> .


Si se conservaron volúmenes de almacenamiento en bloque del host anterior, es posible que deba realizar procedimientos de recuperación adicionales.  Los comandos de esta sección le ayudarán a determinar qué procedimientos adicionales son necesarios.



== Restaurar y validar nodos de la red

Debe restaurar los archivos de configuración de la red para cualquier nodo de red fallido y luego validar los archivos de configuración de la red y resolver cualquier error.

.Acerca de esta tarea
Puede importar cualquier nodo de la red que deba estar presente en el host, siempre que su `/var/local` El volumen no se perdió como resultado de la falla del host anterior.  Por ejemplo, el `/var/local` El volumen aún podría existir si utilizó almacenamiento compartido para los volúmenes de datos del sistema StorageGRID , como se describe en las instrucciones de instalación de StorageGRID para su sistema operativo Linux.  Al importar el nodo se restaura su archivo de configuración al host.

Si no es posible importar los nodos faltantes, deberá volver a crear sus archivos de configuración de cuadrícula.

Luego debe validar el archivo de configuración de la red y resolver cualquier problema de red o almacenamiento que pueda ocurrir antes de continuar reiniciando StorageGRID.  Al volver a crear el archivo de configuración para un nodo, debe utilizar para el nodo de reemplazo el mismo nombre que se utilizó para el nodo que está recuperando.

Consulte las instrucciones de instalación para obtener más información sobre la ubicación del `/var/local` volumen para un nodo.

* link:../rhel/index.html["Instalar StorageGRID en Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Instalar StorageGRID en Ubuntu o Debian"]


.Pasos
. En la línea de comandos del host recuperado, enumere todos los nodos StorageGRID configurados actualmente:``sudo storagegrid node list``
+
Si no se configuran nodos de la red, no habrá salida.  Si se configuran algunos nodos de la cuadrícula, se espera una salida en el siguiente formato:

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
Si algunos o todos los nodos de la red que deberían configurarse en el host no aparecen en la lista, deberá restaurar los nodos de la red que faltan.

. Para importar nodos de cuadrícula que tengan una `/var/local` volumen:
+
.. Ejecute el siguiente comando para cada nodo que desee importar:``sudo storagegrid node import node-var-local-volume-path``
+
El `storagegrid node import` El comando solo tiene éxito si el nodo de destino se apagó correctamente en el host en el que se ejecutó por última vez.  Si ese no es el caso, observarás un error similar al siguiente:

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. Si ve el error sobre que el nodo es propiedad de otro host, ejecute el comando nuevamente con el `--force` bandera para completar la importación:``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: Cualquier nodo importado con el `--force` La bandera requerirá pasos de recuperación adicionales antes de que puedan volver a unirse a la red, como se describe enlink:whats-next-performing-additional-recovery-steps-if-required.html["¿Qué sigue?: Realice pasos de recuperación adicionales, si es necesario"] .



. Para los nodos de la red que no tienen una `/var/local` volumen, vuelva a crear el archivo de configuración del nodo para restaurarlo en el host. Para obtener instrucciones, consulte:
+
** link:../rhel/creating-node-configuration-files.html["Crear archivos de configuración de nodo para Red Hat Enterprise Linux"]
** link:../ubuntu/creating-node-configuration-files.html["Crear archivos de configuración de nodo para Ubuntu o Debian"]
+

NOTE: Al volver a crear el archivo de configuración para un nodo, debe utilizar para el nodo de reemplazo el mismo nombre que se utilizó para el nodo que está recuperando.  Para las implementaciones de Linux, asegúrese de que el nombre del archivo de configuración contenga el nombre del nodo.  Debe utilizar las mismas interfaces de red, asignaciones de dispositivos de bloque y direcciones IP cuando sea posible.  Esta práctica minimiza la cantidad de datos que deben copiarse al nodo durante la recuperación, lo que podría hacer que la recuperación sea significativamente más rápida (en algunos casos, minutos en lugar de semanas).

+

NOTE: Si utiliza nuevos dispositivos de bloque (dispositivos que el nodo StorageGRID no utilizó anteriormente) como valores para cualquiera de las variables de configuración que comienzan con `BLOCK_DEVICE_` Cuando vuelva a crear el archivo de configuración para un nodo, siga las pautas en<<fix-block-errors,Corregir errores de dispositivos de bloque faltantes>> .



. Ejecute el siguiente comando en el host recuperado para enumerar todos los nodos StorageGRID .
+
`sudo storagegrid node list`

. Valide el archivo de configuración de nodo para cada nodo de la red cuyo nombre se mostró en la salida de la lista de nodos de storagegrid:
+
`sudo storagegrid node validate _node-name_`

+
Debe abordar cualquier error o advertencia antes de iniciar el servicio de host StorageGRID .  Las siguientes secciones brindan más detalles sobre los errores que podrían tener una importancia especial durante la recuperación.





=== Corregir errores de interfaz de red faltante

Si la red del host no está configurada correctamente o un nombre está mal escrito, se produce un error cuando StorageGRID verifica la asignación especificada en el `/etc/storagegrid/nodes/_node-name_.conf` archivo.

Es posible que vea un error o una advertencia que coincida con este patrón:

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: GRID_NETWORK_TARGET = <host-interface-name>
       <node-name>: Interface <host-interface-name>' does not exist
----
El error podría informarse para la red de cuadrícula, la red de administración o la red del cliente.  Este error significa que el `/etc/storagegrid/nodes/_node-name_.conf` El archivo asigna la red StorageGRID indicada a la interfaz de host denominada `_host-interface-name_` , pero no hay ninguna interfaz con ese nombre en el host actual.

Si recibe este error, verifique que haya completado los pasos enlink:deploying-new-linux-hosts.html["Implementar nuevos hosts Linux"] .  Utilice los mismos nombres para todas las interfaces de host que los que se usaron en el host original.

Si no puede nombrar las interfaces de host para que coincidan con el archivo de configuración del nodo, puede editar el archivo de configuración del nodo y cambiar el valor de GRID_NETWORK_TARGET, ADMIN_NETWORK_TARGET o CLIENT_NETWORK_TARGET para que coincida con una interfaz de host existente.

Asegúrese de que la interfaz del host proporcione acceso al puerto de red físico o VLAN apropiado, y que la interfaz no haga referencia directa a un dispositivo de enlace o puente.  Debe configurar una VLAN (u otra interfaz virtual) sobre el dispositivo de enlace en el host, o utilizar un puente y un par Ethernet virtual (veth).



=== Corregir errores de dispositivos de bloque faltantes

El sistema verifica que cada nodo recuperado se asigne a un archivo especial de dispositivo de bloque válido o a un enlace simbólico válido a un archivo especial de dispositivo de bloque.  Si StorageGRID encuentra una asignación no válida en el `/etc/storagegrid/nodes/_node-name_.conf` archivo, se muestra un error de dispositivo de bloque faltante.

Si observa un error que coincide con este patrón:

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: BLOCK_DEVICE_PURPOSE = <path-name>
       <node-name>: <path-name> does not exist
----
Eso significa que `/etc/storagegrid/nodes/_node-name_.conf` asigna el dispositivo de bloque utilizado por _node-name_ para `PURPOSE` a la ruta dada en el sistema de archivos de Linux, pero no hay un archivo especial de dispositivo de bloque válido, o un enlace simbólico a un archivo especial de dispositivo de bloque, en esa ubicación.

Verifique que haya completado los pasos enlink:deploying-new-linux-hosts.html["Implementar nuevos hosts Linux"] .  Utilice los mismos nombres de dispositivos persistentes para todos los dispositivos de bloque que se usaron en el host original.

Si no puede restaurar o recrear el archivo especial del dispositivo de bloque faltante, puede asignar un nuevo dispositivo de bloque del tamaño y categoría de almacenamiento adecuados y editar el archivo de configuración del nodo para cambiar el valor de `BLOCK_DEVICE_PURPOSE` para señalar el nuevo archivo especial del dispositivo de bloque.

Determine el tamaño y la categoría de almacenamiento adecuados utilizando las tablas para su sistema operativo Linux:

* link:../rhel/storage-and-performance-requirements.html["Requisitos de almacenamiento y rendimiento para Red Hat Enterprise Linux"]
* link:../ubuntu/storage-and-performance-requirements.html["Requisitos de almacenamiento y rendimiento para Ubuntu o Debian"]


Revise las recomendaciones para configurar el almacenamiento del host antes de continuar con el reemplazo del dispositivo de bloque:

* link:../rhel/configuring-host-storage.html["Configurar el almacenamiento del host para Red Hat Enterprise Linux"]
* link:../ubuntu/configuring-host-storage.html["Configurar el almacenamiento del host para Ubuntu o Debian"]



NOTE: Si debe proporcionar un nuevo dispositivo de almacenamiento en bloque para cualquiera de las variables del archivo de configuración que comienzan con `BLOCK_DEVICE_` Debido a que el dispositivo de bloque original se perdió con el host fallido, asegúrese de que el nuevo dispositivo de bloque no esté formateado antes de intentar otros procedimientos de recuperación.  El nuevo dispositivo de bloque no estará formateado si está usando almacenamiento compartido y ha creado un nuevo volumen.  Si no está seguro, ejecute el siguiente comando contra cualquier archivo especial del nuevo dispositivo de almacenamiento en bloque.

[CAUTION]
====
Ejecute el siguiente comando solo para nuevos dispositivos de almacenamiento en bloque.  No ejecute este comando si cree que el almacenamiento en bloque aún contiene datos válidos para el nodo que se está recuperando, ya que se perderán todos los datos del dispositivo.

`sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1`

====


== Iniciar el servicio de host de StorageGRID

Para iniciar los nodos StorageGRID y garantizar que se reinicien después de un reinicio del host, debe habilitar e iniciar el servicio de host StorageGRID .

.Pasos
. Ejecute los siguientes comandos en cada host:
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
. Ejecute el siguiente comando para garantizar que la implementación esté en curso:
+
[listing]
----
sudo storagegrid node status node-name
----
. Si algún nodo devuelve un estado de "No en ejecución" o "Detenido", ejecute el siguiente comando:
+
[listing]
----
sudo storagegrid node start node-name
----
. Si ya ha habilitado e iniciado el servicio de host StorageGRID (o si no está seguro de si el servicio se ha habilitado e iniciado), ejecute también el siguiente comando:
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----




== Recuperar nodos que no se inician normalmente

Si un nodo StorageGRID no se reincorpora a la red normalmente y no aparece como recuperable, es posible que esté dañado.  Puedes forzar el nodo al modo de recuperación.

.Pasos
. Confirme que la configuración de red del nodo sea correcta.
+
Es posible que el nodo no haya podido reincorporarse a la red debido a asignaciones de interfaz de red incorrectas o a una dirección IP o puerta de enlace de red incorrecta.

. Si la configuración de la red es correcta, emita el `force-recovery` dominio:
+
`sudo storagegrid node force-recovery _node-name_`

. Realice los pasos de recuperación adicionales para el nodo. Ver link:whats-next-performing-additional-recovery-steps-if-required.html["¿Qué sigue?: Realice pasos de recuperación adicionales, si es necesario"] .

