---
permalink: maintain/restoring-admin-node-database-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, primary admin node 
summary: Si desea conservar la información histórica sobre los atributos y las alertas de un nodo de administración principal que ha fallado, puede restaurar la base de datos del nodo de administración.  Solo puede restaurar esta base de datos si su sistema StorageGRID incluye otro nodo de administración. 
---
= Restaurar la base de datos del nodo de administración al recuperar el nodo de administración principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea conservar la información histórica sobre los atributos y las alertas de un nodo de administración principal que ha fallado, puede restaurar la base de datos del nodo de administración.  Solo puede restaurar esta base de datos si su sistema StorageGRID incluye otro nodo de administración.

.Antes de empezar
* El nodo de administración recuperado está instalado y funcionando.
* El sistema StorageGRID incluye al menos dos nodos de administración.
* Tú tienes el `Passwords.txt` archivo.
* Tienes la contraseña de aprovisionamiento.


.Acerca de esta tarea
Si un nodo de administración falla, se pierde la información histórica almacenada en su base de datos.  Esta base de datos incluye la siguiente información:

* Historial de alertas
* Datos de atributos históricos, que se utilizan en gráficos de estilo heredado en la página Nodos


Cuando recupera un nodo de administración, el proceso de instalación del software crea una base de datos de nodo de administración vacía en el nodo recuperado.  Sin embargo, la nueva base de datos sólo incluye información de los servidores y servicios que actualmente forman parte del sistema o que se agregarán posteriormente.

Si restauró un nodo de administración principal y su sistema StorageGRID tiene otro nodo de administración, puede restaurar la información histórica copiando la base de datos del nodo de administración desde un nodo de administración no principal (el _nodo de administración de origen_) al nodo de administración principal recuperado.  Si su sistema solo tiene un nodo de administración principal, no podrá restaurar la base de datos del nodo de administración.


NOTE: Copiar la base de datos del nodo de administración puede tardar varias horas.  Algunas funciones de Grid Manager no estarán disponibles mientras los servicios estén detenidos en el nodo de administración de origen.

.Pasos
. Inicie sesión en el nodo de administración de origen:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


. Desde el nodo de administración de origen, detenga el servicio MI: `service mi stop`
. Desde el nodo de administración de origen, detenga el servicio de interfaz de programación de aplicaciones de administración (mgmt-api): `service mgmt-api stop`
. Complete los siguientes pasos en el nodo de administración recuperado:
+
.. Inicie sesión en el nodo de administración recuperado:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a root: `su -`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


.. Detener el servicio MI: `service mi stop`
.. Detener el servicio mgmt-api: `service mgmt-api stop`
.. Agregue la clave privada SSH al agente SSH.  Ingresar:``ssh-add``
.. Ingrese la contraseña de acceso SSH que aparece en el `Passwords.txt` archivo.
.. Copie la base de datos del nodo de administración de origen al nodo de administración recuperado: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Cuando se le solicite, confirme que desea sobrescribir la base de datos MI en el nodo de administración recuperado.
+
La base de datos y sus datos históricos se copian al nodo de administración recuperado.  Una vez finalizada la operación de copia, el script inicia el nodo de administración recuperado.

.. Cuando ya no necesite acceso sin contraseña a otros servidores, elimine la clave privada del agente SSH.  Ingresar:``ssh-add -D``


. Reinicie los servicios en el nodo de administración de origen: `service servermanager start`

