---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Es posible que sea necesario reiniciar el administrador del servidor y todos los servicios que se ejecutan en un nodo de la red. 
---
= Reinicie el Administrador del servidor y todos los servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que sea necesario reiniciar el administrador del servidor y todos los servicios que se ejecutan en un nodo de la red.

.Antes de empezar
Tú tienes el `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de la red:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Reinicie el Administrador de servidor y todos los servicios en el nodo de la red: `service servermanager restart`
+
El Administrador de servidor y todos los servicios en el nodo de la red se detienen y luego se reinician.

+

NOTE: Usando el `restart` El comando es lo mismo que usar el `stop` orden seguida de la `start` dominio.

. Cerrar sesión en el shell de comandos: `exit`

