---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: Antes de recuperar volúmenes de almacenamiento fallidos para un nodo de almacenamiento, debe revisar las siguientes advertencias. 
---
= Advertencias para la recuperación del volumen de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de recuperar volúmenes de almacenamiento fallidos para un nodo de almacenamiento, revise las siguientes advertencias.

Los volúmenes de almacenamiento (o rangedbs) en un nodo de almacenamiento se identifican mediante un número hexadecimal, conocido como ID de volumen.  Por ejemplo, 0000 es el primer volumen y 000F es el decimosexto volumen.  El primer almacén de objetos (volumen 0) en cada nodo de almacenamiento utiliza hasta 4 TB de espacio para metadatos de objetos y operaciones de base de datos de Cassandra; cualquier espacio restante en ese volumen se utiliza para datos de objetos.  Todos los demás volúmenes de almacenamiento se utilizan exclusivamente para datos de objetos.

Si el volumen 0 falla y necesita recuperarse, la base de datos de Cassandra podría reconstruirse como parte del procedimiento de recuperación del volumen.  Cassandra también podría reconstruirse en las siguientes circunstancias:

* Un nodo de almacenamiento vuelve a estar en línea después de haber estado fuera de línea durante más de 15 días.
* La unidad del sistema y uno o más volúmenes de almacenamiento fallan y se recuperan.


Cuando se reconstruye Cassandra, el sistema utiliza información de otros nodos de almacenamiento. Si hay demasiados nodos de almacenamiento fuera de línea, es posible que algunos datos de Cassandra no estén disponibles. Si Cassandra se ha reconstruido recientemente, es posible que sus datos aún no sean consistentes en toda la red.  Puede ocurrir pérdida de datos si se reconstruye Cassandra cuando demasiados nodos de almacenamiento están fuera de línea o si dos o más nodos de almacenamiento se reconstruyen con una diferencia de 15 días entre sí.


CAUTION: Si más de un nodo de almacenamiento ha fallado (o está fuera de línea), comuníquese con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podría ocurrir pérdida de datos.


CAUTION: Si esta es la segunda falla del nodo de almacenamiento en menos de 15 días después de una falla o recuperación del nodo de almacenamiento, comuníquese con el soporte técnico.  Reconstruir Cassandra en dos o más nodos de almacenamiento dentro de 15 días puede provocar la pérdida de datos.


NOTE: Si ha fallado más de un nodo de almacenamiento en un sitio, es posible que se requiera un procedimiento de recuperación del sitio. Ver link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"] .


CAUTION: Si las reglas de ILM están configuradas para almacenar solo una copia replicada y la copia existe en un volumen de almacenamiento que ha fallado, no podrá recuperar el objeto.

.Información relacionada
link:warnings-and-considerations-for-grid-node-recovery.html["Advertencias y consideraciones para la recuperación del nodo de la red"]
