---
permalink: maintain/starting-or-restarting-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, start service, restart service 
summary: Es posible que necesite iniciar un servicio que se haya detenido o que necesite detener y reiniciar un servicio. 
---
= Iniciar o reiniciar el servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que necesite iniciar un servicio que se haya detenido o que necesite detener y reiniciar un servicio.

.Antes de empezar
Tú tienes el `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de la red:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Decide qué comando emitir, en función de si el servicio está ejecutándose o detenido.
+
** Si el servicio está actualmente detenido, utilice el `start` Comando para iniciar el servicio manualmente: `service _servicename_ start`
+
Por ejemplo:

+
[listing]
----
service ldr start
----
** Si el servicio se está ejecutando actualmente, utilice el `restart` Comando para detener el servicio y luego reiniciarlo: `service _servicename_ restart`
+
Por ejemplo:

+
[listing]
----
service ldr restart
----
+

NOTE: Usando el `restart` El comando es lo mismo que usar el `stop` orden seguida de la `start` dominio.  Puedes emitir `restart` incluso si el servicio está actualmente detenido.



. Cerrar sesión en el shell de comandos: `exit`

