---
permalink: maintain/stopping-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop service, service 
summary: Algunos procedimientos de mantenimiento requieren que usted detenga un solo servicio mientras mantiene otros servicios en funcionamiento en el nodo de la red.  Detenga servicios individuales únicamente cuando así lo indique un procedimiento de mantenimiento. 
---
= Detener el servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunos procedimientos de mantenimiento requieren que usted detenga un solo servicio mientras mantiene otros servicios en funcionamiento en el nodo de la red.  Detenga servicios individuales únicamente cuando así lo indique un procedimiento de mantenimiento.

.Antes de empezar
Tú tienes el `Passwords.txt` archivo.

.Acerca de esta tarea
Cuando utiliza estos pasos para "detener administrativamente" un servicio, el Administrador de servidor no reiniciará automáticamente el servicio.  Debe iniciar el servicio único manualmente o reiniciar el Administrador del servidor.

Si necesita detener el servicio LDR en un nodo de almacenamiento, tenga en cuenta que puede llevar un tiempo detener el servicio si hay conexiones activas.

.Pasos
. Inicie sesión en el nodo de la red:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Detener un servicio individual: `service _servicename_ stop`
+
Por ejemplo:

+
[listing]
----
service ldr stop
----
+

NOTE: Los servicios pueden tardar hasta 11 minutos en detenerse.

. Cerrar sesión en el shell de comandos: `exit`


.Información relacionada
link:forcing-service-to-terminate.html["Forzar la terminación del servicio"]
