---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: Es posible que necesite aplicar una revisión a su sistema StorageGRID si se detectan y resuelven problemas con el software entre versiones de funciones. 
---
= Procedimiento de revisión de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que necesite aplicar una revisión a su sistema StorageGRID si se detectan y resuelven problemas con el software entre versiones de funciones.

Las revisiones de StorageGRID contienen cambios de software que están disponibles fuera de una versión de parche o función.  Los mismos cambios se incluirán en una versión futura.  Además, cada versión de revisión contiene un resumen de todas las revisiones anteriores dentro de la versión de función o parche.



== Consideraciones para aplicar un hotfix

No se puede aplicar una revisión de StorageGRID cuando se está ejecutando otro procedimiento de mantenimiento.  Por ejemplo, no se puede aplicar una revisión mientras se ejecuta un procedimiento de desmantelamiento, expansión o recuperación.


NOTE: Si se pausa un procedimiento de desmantelamiento de un nodo o sitio, puede aplicar una revisión de forma segura.  Además, es posible que pueda aplicar una revisión durante las etapas finales de un procedimiento de actualización de StorageGRID .  Consulte las instrucciones para actualizar el software StorageGRID para obtener más detalles.

Después de cargar la revisión en el Administrador de cuadrícula, esta se aplica automáticamente al nodo de administración principal.  Luego, puede aprobar la aplicación de la revisión al resto de los nodos en su sistema StorageGRID .

Si una revisión no se puede aplicar a uno o más nodos, el motivo del error aparece en la columna Detalles de la tabla de progreso de la revisión.  Debes resolver cualquier problema que haya causado las fallas y luego volver a intentar todo el proceso.  Los nodos en los que se haya aplicado con éxito previamente la revisión se omitirán en las aplicaciones posteriores.  Puede volver a intentar de forma segura el proceso de revisión tantas veces como sea necesario hasta que se hayan actualizado todos los nodos.  La revisión debe instalarse correctamente en todos los nodos de la red para que la aplicación se complete.

Si bien los nodos de la red se actualizan con la nueva versión de revisión, los cambios reales en una revisión podrían afectar solo a servicios específicos en tipos específicos de nodos.  Por ejemplo, una revisión podría afectar únicamente al servicio LDR en los nodos de almacenamiento.



== Cómo se aplican las revisiones para la recuperación y expansión

Después de aplicar una revisión a su red, el nodo de administración principal instala automáticamente la misma versión de revisión en cualquier nodo restaurado mediante operaciones de recuperación o agregado en una expansión.

Sin embargo, si necesita recuperar el nodo de administración principal, debe instalar manualmente la versión correcta de StorageGRID y luego aplicar la revisión.  La versión final de StorageGRID del nodo de administración principal debe coincidir con la versión de los demás nodos de la red.

El siguiente ejemplo ilustra cómo aplicar una revisión al recuperar el nodo de administración principal:

. Supongamos que la red está ejecutando una versión StorageGRID 11._A.B_ con la última revisión.  La "versión de cuadrícula" es 11._D.B.y_.
. El nodo de administración principal falla.
. Vuelve a implementar el nodo de administración principal mediante StorageGRID 11._A.B_ y realiza el procedimiento de recuperación.
+

NOTE: Según sea necesario para que coincida con la versión de la red, puede utilizar una versión menor al implementar el nodo; no es necesario implementar primero la versión principal.

. A continuación, aplique la revisión 11._A.B.y_ al nodo de administración principal.


Para obtener más información, consulte link:configuring-replacement-primary-admin-node.html["Configurar el nodo de administración principal de reemplazo"] .
