---
permalink: maintain/viewing-current-status-of-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, status 
summary: Puede ver el estado actual de un servicio que se ejecuta en un nodo de la red en cualquier momento. 
---
= Ver el estado actual del servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver el estado actual de un servicio que se ejecuta en un nodo de la red en cualquier momento.

.Antes de empezar
Tú tienes el `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de la red:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .

. Ver el estado actual de un servicio que se ejecuta en un nodo de la red: `*service _servicename_ status* Se informa el estado actual del servicio solicitado que se ejecuta en el nodo de la red (en ejecución o no). Por ejemplo:
+
[listing]
----
cmn running for 1d, 14h, 21m, 2s
----
. Cerrar sesión en el shell de comandos: `*exit*`

