---
permalink: maintain/whats-next-performing-additional-recovery-steps-if-required.html 
sidebar: sidebar 
keywords: storagegrid, recover, corrective action, additional recovery 
summary: Según las acciones específicas que haya realizado para que los nodos StorageGRID se ejecuten en el host de reemplazo, es posible que deba realizar pasos de recuperación adicionales para cada nodo. 
---
= ¿Qué sigue?: Realice pasos de recuperación adicionales, si es necesario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Según las acciones específicas que haya realizado para que los nodos StorageGRID se ejecuten en el host de reemplazo, es posible que deba realizar pasos de recuperación adicionales para cada nodo.

La recuperación del nodo está completa si no fue necesario realizar ninguna acción correctiva mientras reemplazaba el host Linux o restauraba el nodo de red fallido en el nuevo host.



== Acciones correctivas y próximos pasos

Durante el reemplazo del nodo, es posible que haya sido necesario tomar una de estas acciones correctivas:

* Tuviste que usar el `--force` bandera para importar el nodo.
* Para cualquier `<PURPOSE>` , el valor de la `BLOCK_DEVICE_<PURPOSE>` La variable del archivo de configuración se refiere a un dispositivo de bloque que no contiene los mismos datos que tenía antes de la falla del host.
* Usted emitió `storagegrid node force-recovery _node-name_` para el nodo.
* Agregó un nuevo dispositivo de bloque.


Si realizó *alguna* de estas acciones correctivas, deberá realizar pasos de recuperación adicionales.

[cols="2a,1a"]
|===
| Tipo de recuperación | Siguiente paso 


 a| 
Nodo de administración principal
 a| 
link:configuring-replacement-primary-admin-node.html["Configurar el nodo de administración principal de reemplazo"]



 a| 
Nodo de administración no principal
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Seleccione Iniciar recuperación para configurar el nodo de administración no principal"]



 a| 
Nodo de puerta de enlace
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Seleccione Iniciar recuperación para configurar el nodo de puerta de enlace"]



 a| 
Nodo de almacenamiento (basado en software):

* Si tuvieras que usar el `--force` bandera para importar el nodo, o usted emitió `storagegrid node force-recovery _node-name_`
* Si tuvieras que hacer una reinstalación completa del nodo o necesitaras restaurar /var/local

 a| 
link:selecting-start-recovery-to-configure-storage-node.html["Seleccione Iniciar recuperación para configurar el nodo de almacenamiento"]



 a| 
Nodo de almacenamiento (basado en software):

* Si agregó un nuevo dispositivo de bloque.
* Si, por cualquier `<PURPOSE>` , el valor de la `BLOCK_DEVICE_<PURPOSE>` La variable del archivo de configuración se refiere a un dispositivo de bloque que no contiene los mismos datos que tenía antes de la falla del host.

 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Recuperarse de una falla del volumen de almacenamiento donde la unidad del sistema está intacta"]

|===