---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: Los nodos de puerta de enlace proporcionan una interfaz de equilibrio de carga dedicada que las aplicaciones cliente S3 pueden usar para conectarse a StorageGRID.  El equilibrio de carga maximiza la velocidad y la capacidad de conexión al distribuir la carga de trabajo entre múltiples nodos de almacenamiento.  Los nodos de puerta de enlace son opcionales. 
---
= ¿Qué es un nodo de enlace?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nodos de puerta de enlace proporcionan una interfaz de equilibrio de carga dedicada que las aplicaciones cliente S3 pueden usar para conectarse a StorageGRID.  El equilibrio de carga maximiza la velocidad y la capacidad de conexión al distribuir la carga de trabajo entre múltiples nodos de almacenamiento.  Los nodos de puerta de enlace son opcionales.

El servicio StorageGRID Load Balancer se proporciona en todos los nodos de administración y todos los nodos de puerta de enlace.  Realiza la terminación de seguridad de la capa de transporte (TLS) de las solicitudes de los clientes, inspecciona las solicitudes y establece nuevas conexiones seguras con los nodos de almacenamiento.  El servicio Load Balancer dirige sin problemas a los clientes a un nodo de almacenamiento óptimo, de modo que la falla de los nodos o incluso de un sitio completo sea transparente.

Configura uno o más puntos finales del balanceador de carga para definir el puerto y el protocolo de red (HTTPS o HTTP) que las solicitudes de cliente entrantes y salientes utilizarán para acceder a los servicios del balanceador de carga en los nodos de puerta de enlace y de administración.  El punto final del balanceador de carga también define el tipo de cliente (S3), el modo de enlace y, opcionalmente, una lista de inquilinos permitidos o bloqueados. Ver link:../admin/managing-load-balancing.html["Consideraciones para el equilibrio de carga"] .

Según sea necesario, puede agrupar las interfaces de red de varios nodos de puerta de enlace y nodos de administración en un grupo de alta disponibilidad (HA).  Si la interfaz activa en el grupo HA falla, una interfaz de respaldo puede administrar la carga de trabajo de la aplicación cliente. Ver link:../admin/managing-high-availability-groups.html["Administrar grupos de alta disponibilidad (HA)"] .



== Servicios principales para nodos de puerta de enlace

La siguiente tabla muestra los servicios principales para los nodos de puerta de enlace; sin embargo, esta tabla no enumera todos los servicios de los nodos.

[cols="1a,2a"]
|===
| Servicio | Función de tecla 


 a| 
Alta disponibilidad
 a| 
Administra direcciones IP virtuales de alta disponibilidad para grupos de nodos de administración y nodos de puerta de enlace.

*Nota:* Este servicio también se encuentra en los nodos de administración.



 a| 
Balanceador de carga
 a| 
Proporciona equilibrio de carga de capa 7 del tráfico S3 desde los clientes a los nodos de almacenamiento.  Este es el mecanismo de equilibrio de carga recomendado.

*Nota:* Este servicio también se encuentra en los nodos de administración.



 a| 
Monitor de estado del servidor (SSM)
 a| 
Supervisa el sistema operativo y el hardware subyacente.

|===