---
permalink: expand/copying-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, copy metrics, Admin Node expansion 
summary: Después de agregar un nuevo nodo de administración, puede copiar opcionalmente las métricas históricas mantenidas por Prometheus desde el nodo de administración principal al nuevo nodo de administración.  Copiar las métricas garantiza que las métricas históricas sean consistentes entre los nodos de administración. 
---
= Copiar métricas de Prometheus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de agregar un nuevo nodo de administración, puede copiar opcionalmente las métricas históricas mantenidas por Prometheus desde el nodo de administración principal al nuevo nodo de administración.  Copiar las métricas garantiza que las métricas históricas sean consistentes entre los nodos de administración.

.Antes de empezar
* El nuevo nodo de administración está instalado y funcionando.
* Tú tienes el `Passwords.txt` archivo.
* Tienes la contraseña de aprovisionamiento.


.Acerca de esta tarea
Cuando agrega un nodo de administración, el proceso de instalación del software crea una nueva base de datos de Prometheus.  Puede mantener las métricas históricas consistentes entre los nodos copiando la base de datos de Prometheus desde el nodo de administración principal (el _nodo de administración de origen_) al nuevo nodo de administración.


NOTE: Copiar la base de datos de Prometheus podría tardar una hora o más.  Algunas funciones de Grid Manager no estarán disponibles mientras los servicios estén detenidos en el nodo de administración de origen.

.Pasos
. Inicie sesión en el nodo de administración de origen:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


. Desde el nodo de administración de origen, detenga el servicio Prometheus: `service prometheus stop`
. Complete los siguientes pasos en el nuevo nodo de administración:
+
.. Inicie sesión en el nuevo nodo de administración:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a root: `su -`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


.. Detener el servicio Prometheus: `service prometheus stop`
.. Agregue la clave privada SSH al agente SSH.  Ingresar:``ssh-add``
.. Ingrese la contraseña de acceso SSH que aparece en el `Passwords.txt` archivo.
.. Copie la base de datos de Prometheus del nodo de administración de origen al nuevo nodo de administración: `/usr/local/prometheus/bin/prometheus-clone-db.sh _Source_Admin_Node_IP_`
.. Cuando se le solicite, presione *Enter* para confirmar que desea destruir la nueva base de datos de Prometheus en el nuevo nodo de administración.
+
La base de datos original de Prometheus y sus datos históricos se copian al nuevo nodo de administración.  Cuando se realiza la operación de copia, el script inicia el nuevo nodo de administración.  Aparece el siguiente estado:

+
`Database cloned, starting services`

.. Cuando ya no necesite acceso sin contraseña a otros servidores, elimine la clave privada del agente SSH.  Ingresar:
+
`ssh-add -D`



. Reinicie el servicio Prometheus en el nodo de administración de origen.
+
`service prometheus start`


