---
permalink: expand/index.html 
sidebar: sidebar 
keywords: expand grid 
summary: Puede ampliar la capacidad o las capacidades de su sistema StorageGRID sin interrumpir las operaciones del sistema. 
---
= Tipos de expansión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ampliar la capacidad o las capacidades de su sistema StorageGRID sin interrumpir las operaciones del sistema.

Una expansión de StorageGRID le permite agregar:

* Volúmenes de almacenamiento a nodos de almacenamiento
* Nuevos nodos de red en un sitio existente
* Un sitio completamente nuevo


El motivo por el que realiza la expansión determina cuántos nodos nuevos de cada tipo debe agregar y la ubicación de esos nuevos nodos.  Por ejemplo, existen diferentes requisitos de nodo si está realizando una expansión para aumentar la capacidad de almacenamiento, agregar capacidad de metadatos o agregar redundancia o nuevas capacidades.

Siga los pasos según el tipo de expansión que esté realizando:

[role="tabbed-block"]
====
.Agregar volúmenes de almacenamiento
--
Siga los pasos paralink:adding-storage-volumes-to-storage-nodes.html["Agregar volúmenes de almacenamiento a los nodos de almacenamiento"] .

--
.Agregar nodos de cuadrícula
--
. Siga los pasos paralink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["Agregar nodos de cuadrícula a un sitio existente"] .
. link:updating-subnets-for-grid-network.html["Actualizar las subredes"] .
. Implementar nodos de cuadrícula:
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["Accesorios"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: "Linux" se refiere a una implementación de Red Hat Enterprise Linux, Ubuntu o Debian. Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .



. link:performing-expansion.html["Realizar la expansión"] .
. link:configuring-expanded-storagegrid-system.html["Configurar el sistema expandido"] .


--
.Añadir nuevo sitio
--
. Siga los pasos paralink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["Agregar un nuevo sitio"] .
. link:updating-subnets-for-grid-network.html["Actualizar las subredes"] .
. Implementar nodos de cuadrícula:
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["Accesorios"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: "Linux" se refiere a una implementación de Red Hat Enterprise Linux, Ubuntu o Debian. Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .



. link:performing-expansion.html["Realizar la expansión"] .
. link:configuring-expanded-storagegrid-system.html["Configurar el sistema expandido"] .


--
====