---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: Los objetos se pueden recuperar por varios motivos, incluidas solicitudes de lectura de una aplicación cliente, verificaciones en segundo plano de datos de objetos replicados, reevaluaciones de ILM y la restauración de datos de objetos durante la recuperación de un nodo de almacenamiento. 
---
= Solucionar problemas de datos de objetos perdidos o faltantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los objetos se pueden recuperar por varios motivos, incluidas solicitudes de lectura de una aplicación cliente, verificaciones en segundo plano de datos de objetos replicados, reevaluaciones de ILM y la restauración de datos de objetos durante la recuperación de un nodo de almacenamiento.

El sistema StorageGRID utiliza información de ubicación en los metadatos de un objeto para determinar desde qué ubicación recuperar el objeto. Si no se encuentra una copia del objeto en la ubicación esperada, el sistema intenta recuperar otra copia del objeto desde otra parte del sistema, asumiendo que la política ILM contiene una regla para hacer dos o más copias del objeto.

Si esta recuperación es exitosa, el sistema StorageGRID reemplaza la copia faltante del objeto. De lo contrario, se activa la alerta *Objetos perdidos*, de la siguiente manera:

* En el caso de copias replicadas, si no se puede recuperar otra copia, el objeto se considera perdido y se activa la alerta.
* Para las copias con código de borrado, si no se puede recuperar una copia de la ubicación esperada, el atributo Copias corruptas detectadas (ECOR) se incrementa en uno antes de intentar recuperar una copia de otra ubicación.  Si no se encuentra otra copia, se activa la alerta.


Debe investigar todas las alertas de *Objetos perdidos* inmediatamente para determinar la causa raíz de la pérdida y si el objeto aún podría existir en un nodo de almacenamiento fuera de línea o que no esté disponible en ese momento. Ver link:../troubleshoot/investigating-lost-objects.html["Investigar objetos perdidos"] .

En el caso de que se pierdan datos de objetos sin copias, no existe solución de recuperación. Sin embargo, debe restablecer el contador de objetos perdidos para evitar que los objetos perdidos conocidos enmascaren cualquier objeto perdido nuevo. Ver link:resetting-lost-and-missing-object-counts.html["Restablecer el recuento de objetos perdidos y faltantes"] .
