---
permalink: troubleshoot/troubleshooting-admin-node-and-user-interface-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot admin node issues, how to troubleshoot user interface issues 
summary: Puede realizar varias tareas para ayudar a determinar el origen de los problemas relacionados con los nodos de administración y la interfaz de usuario de StorageGRID . 
---
= Solucionar problemas del nodo de administración y de la interfaz de usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar varias tareas para ayudar a determinar el origen de los problemas relacionados con los nodos de administración y la interfaz de usuario de StorageGRID .



== Errores de inicio de sesión en el nodo de administración

Si experimenta un error al iniciar sesión en un nodo de administración de StorageGRID , es posible que su sistema tenga un problema con unlink:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["redes"] o https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/troubleshooting-hardware-installation-sg100-and-sg1000.html["hardware"^] problema, un problema conlink:../primer/what-admin-node-is.html["Servicios del nodo de administración"] , o unlink:../maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Problema con la base de datos de Cassandra"] en nodos de almacenamiento conectados.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes el `Passwords.txt` archivo.
* Tieneslink:../admin/admin-group-permissions.html["permisos de acceso específicos"] .


.Acerca de esta tarea
Utilice estas pautas de solución de problemas si ve alguno de los siguientes mensajes de error al intentar iniciar sesión en un nodo de administración:

* `Your credentials for this account were invalid. Please try again.`
* `Waiting for services to start...`
* `Internal server error. The server encountered an error and could not complete your request. Please try again. If the problem persists, contact Technical Support.`
* `Unable to communicate with server. Reloading page...`


.Pasos
. Espere 10 minutos e intente iniciar sesión nuevamente.
+
Si el error no se resuelve automáticamente, vaya al siguiente paso.

. Si su sistema StorageGRID tiene más de un nodo de administración, intente iniciar sesión en Grid Manager desde otro nodo de administración para verificar el estado de un nodo de administración no disponible.
+
** Si puede iniciar sesión, puede utilizar las opciones *Panel de control*, *NODOS*, *Alertas* y *SOPORTE* para ayudar a determinar la causa del error.
** Si solo tiene un nodo de administración o aún no puede iniciar sesión, vaya al siguiente paso.


. Determinar si el hardware del nodo está fuera de línea.
. Si el inicio de sesión único (SSO) está habilitado para su sistema StorageGRID , consulte los pasos paralink:../admin/configuring-sso.html["configuración del inicio de sesión único"] .
+
Es posible que necesites deshabilitar y volver a habilitar temporalmente el SSO para un solo nodo de administración para resolver cualquier problema.

+

NOTE: Si SSO está habilitado, no podrá iniciar sesión usando un puerto restringido.  Debes utilizar el puerto 443.

. Determinar si la cuenta que estás utilizando pertenece a un usuario federado.
+
Si la cuenta de usuario federada no funciona, intente iniciar sesión en Grid Manager como un usuario local, como root.

+
** Si el usuario local puede iniciar sesión:
+
... Revisar alertas.
... Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Federación de identidades*.
... Haga clic en *Probar conexión* para validar su configuración de conexión para el servidor LDAP.
... Si la prueba falla, resuelva cualquier error de configuración.


** Si el usuario local no puede iniciar sesión y está seguro de que las credenciales son correctas, vaya al siguiente paso.


. Utilice Secure Shell (ssh) para iniciar sesión en el nodo de administración:
+
.. Introduzca el siguiente comando: `ssh admin@Admin_Node_IP`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a root: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
+
Cuando inicia sesión como root, el mensaje cambia de `$` a `#` .



. Ver el estado de todos los servicios que se ejecutan en el nodo de la red: `storagegrid-status`
+
Asegúrese de que los servicios nms, mi, nginx y mgmt api estén todos en ejecución.

+
La salida se actualiza inmediatamente si cambia el estado de un servicio.

+
....
$ storagegrid-status
Host Name                      99-211
IP Address                     10.96.99.211
Operating System Kernel        4.19.0         Verified
Operating System Environment   Debian 10.1    Verified
StorageGRID Webscale Release   11.4.0         Verified
Networking                                    Verified
Storage Subsystem                             Verified
Database Engine                5.5.9999+default Running
Network Monitoring             11.4.0         Running
Time Synchronization           1:4.2.8p10+dfsg Running
ams                            11.4.0         Running
cmn                            11.4.0         Running
nms                            11.4.0         Running
ssm                            11.4.0         Running
mi                             11.4.0         Running
dynip                          11.4.0         Running
nginx                          1.10.3         Running
tomcat                         9.0.27         Running
grafana                        6.4.3          Running
mgmt api                       11.4.0         Running
prometheus                     11.4.0         Running
persistence                    11.4.0         Running
ade exporter                   11.4.0         Running
alertmanager                   11.4.0         Running
attrDownPurge                  11.4.0         Running
attrDownSamp1                  11.4.0         Running
attrDownSamp2                  11.4.0         Running
node exporter                  0.17.0+ds      Running
sg snmp agent                  11.4.0         Running
....
. Confirme que el servicio nginx-gw se esté ejecutando `# service nginx-gw status`
. [[use_Lumberjack_to_collect_logs]]Utilice Lumberjack para recolectar troncos: `# /usr/local/sbin/lumberjack.rb`
+
Si la autenticación falló en el pasado, puede usar las opciones de script --start y --end de Lumberjack para especificar el rango de tiempo apropiado.  Utilice lumberjack -h para obtener detalles sobre estas opciones.

+
La salida a la terminal indica dónde se ha copiado el archivo de registro.

. [[review_logs, start=10]]Revise los siguientes registros:
+
** `/var/local/log/bycast.log`
** `/var/local/log/bycast-err.log`
** `/var/local/log/nms.log`
** `**/*commands.txt`


. Si no pudo identificar ningún problema con el nodo de administración, emita cualquiera de los siguientes comandos para determinar las direcciones IP de los tres nodos de almacenamiento que ejecutan el servicio ADC en su sitio.  Normalmente, estos son los primeros tres nodos de almacenamiento que se instalan en el sitio.
+
[listing]
----
# cat /etc/hosts
----
+
[listing]
----
# gpt-list-services adc
----
+
Los nodos de administración utilizan el servicio ADC durante el proceso de autenticación.

. Desde el nodo de administración, use ssh para iniciar sesión en cada uno de los nodos de almacenamiento de ADC, utilizando las direcciones IP que identificó.
. Ver el estado de todos los servicios que se ejecutan en el nodo de la red: `storagegrid-status`
+
Asegúrese de que los servicios idnt, acct, nginx y cassandra estén todos en ejecución.

. Repetir los pasos<<use_Lumberjack_to_collect_logs,Utilice a Lumberjack para recolectar troncos>> y<<review_logs,Revisar registros>> para revisar los registros en los nodos de almacenamiento.
. Si no puede resolver el problema, comuníquese con el soporte técnico.
+
Proporcione los registros que recopiló al soporte técnico. Consulte también link:../monitor/logs-files-reference.html["Referencia de archivos de registro"] .





== Problemas de interfaz de usuario

Es posible que la interfaz de usuario del Administrador de red o del Administrador de inquilinos no responda como se espera después de actualizar el software StorageGRID .

.Pasos
. Asegúrate de que estás usando unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
. Limpia el caché de tu navegador web.
+
Al borrar la memoria caché se eliminan los recursos obsoletos utilizados por la versión anterior del software StorageGRID y se permite que la interfaz de usuario vuelva a funcionar correctamente.  Para obtener instrucciones, consulte la documentación de su navegador web.


