---
permalink: ilm/viewing-storage-pool-details.html 
sidebar: sidebar 
keywords: storage pool, view details 
summary: Puede ver los detalles de un grupo de almacenamiento para determinar dónde se utiliza y ver qué nodos y grados de almacenamiento están incluidos. 
---
= Ver detalles del grupo de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver los detalles de un grupo de almacenamiento para determinar dónde se utiliza y ver qué nodos y grados de almacenamiento están incluidos.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tieneslink:../admin/admin-group-permissions.html["permisos de acceso específicos"] .


.Pasos
. Seleccione *ILM* > *Grupos de almacenamiento*.
+
La tabla de grupos de almacenamiento incluye la siguiente información para cada grupo de almacenamiento que incluye nodos de almacenamiento:

+
** *Nombre*: el nombre para mostrar único del grupo de almacenamiento.
** *Recuento de nodos*: la cantidad de nodos en el grupo de almacenamiento.
** *Uso de almacenamiento*: el porcentaje del espacio utilizable total que se ha utilizado para datos de objetos en este nodo.  Este valor no incluye metadatos del objeto.
** *Capacidad total*: el tamaño del grupo de almacenamiento, que equivale a la cantidad total de espacio utilizable para datos de objetos para todos los nodos del grupo de almacenamiento.
** *Uso de ILM*: cómo se utiliza actualmente el grupo de almacenamiento.  Es posible que un grupo de almacenamiento no se utilice o que se utilice en una o más reglas ILM, perfiles de codificación de borrado o ambos.


. Para ver los detalles de un grupo de almacenamiento específico, seleccione su nombre.
+
Aparece la página de detalles del grupo de almacenamiento.

. Consulte la pestaña *Nodos* para obtener información sobre los nodos de almacenamiento incluidos en el grupo de almacenamiento.
+
La tabla incluye la siguiente información para cada nodo:

+
** Nombre del nodo
** Nombre del sitio
** Grado de almacenamiento
** Uso de almacenamiento: el porcentaje del espacio total utilizable para los datos de objetos que se ha utilizado para el nodo de almacenamiento.
+

NOTE: El mismo valor de uso de almacenamiento (%) también se muestra en el gráfico Almacenamiento utilizado - Datos de objeto para cada nodo de almacenamiento (seleccione *NODOS* > *_Nodo de almacenamiento_* > *Almacenamiento*).



. Vea la pestaña *Uso de ILM* para determinar si el grupo de almacenamiento se está utilizando actualmente en alguna regla de ILM o perfil de codificación de borrado.
. Opcionalmente, vaya a la *página de reglas de ILM* para conocer y administrar las reglas que utilizan el grupo de almacenamiento.
+
Ver ellink:working-with-ilm-rules-and-ilm-policies.html["Instrucciones para trabajar con reglas ILM"] .


