---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: Los esquemas de codificación de borrado controlan cuántos fragmentos de datos y cuántos fragmentos de paridad se crean para cada objeto. 
---
= ¿Qué son los esquemas de codificación de borrado?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los esquemas de codificación de borrado controlan cuántos fragmentos de datos y cuántos fragmentos de paridad se crean para cada objeto.

Cuando crea o edita una regla ILM, selecciona un esquema de codificación de borrado disponible.  StorageGRID crea automáticamente esquemas de codificación de borrado en función de la cantidad de nodos de almacenamiento y sitios que conforman el grupo de almacenamiento que planea utilizar.



== Protección de datos

El sistema StorageGRID utiliza el algoritmo de codificación de borrado Reed-Solomon.  El algoritmo divide un objeto en `k` fragmentos de datos y cálculos `m` fragmentos de paridad.

El `k + m = n` Los fragmentos se encuentran dispersos `n` Nodos de almacenamiento para proporcionar protección de datos de la siguiente manera:

* Para recuperar o reparar un objeto, `k` Se necesitan fragmentos.
* Un objeto puede soportar hasta `m` fragmentos perdidos o corruptos.  Cuanto mayor sea el valor de `m` , mayor será la tolerancia al fallo.


La mejor protección de datos la proporciona el esquema de codificación de borrado con la mayor tolerancia a fallas de nodo o volumen dentro de un grupo de almacenamiento.



== Gastos generales de almacenamiento

La sobrecarga de almacenamiento de un esquema de codificación de borrado se calcula dividiendo el número de fragmentos de paridad(`m` ) por el número de fragmentos de datos(`k` ).  Puede utilizar la sobrecarga de almacenamiento para calcular cuánto espacio en disco requiere cada objeto con código de borrado:

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

Por ejemplo, si almacena un objeto de 10 MB utilizando el esquema 4+2 (que tiene una sobrecarga de almacenamiento del 50 %), el objeto consume 15 MB de almacenamiento en la red.  Si almacena el mismo objeto de 10 MB utilizando el esquema 6+2 (que tiene una sobrecarga de almacenamiento del 33 %), el objeto consume aproximadamente 13,3 MB.

Seleccione el esquema de codificación de borrado con el valor total más bajo de `k+m` que se ajuste a sus necesidades.  Los esquemas de codificación de borrado con un menor número de fragmentos son computacionalmente más eficientes porque:

* Se crean y distribuyen (o recuperan) menos fragmentos por objeto
* Muestran un mejor rendimiento porque el tamaño del fragmento es mayor
* Pueden requerir que se agreguen menos nodos en unlink:../expand/index.html["expansión cuando se requiere más almacenamiento"]




== Directrices para los pools de almacenamiento

Al seleccionar el grupo de almacenamiento que se utilizará para una regla que creará una copia con código de borrado, utilice las siguientes pautas para los grupos de almacenamiento:

* El grupo de almacenamiento debe incluir tres o más sitios, o exactamente un sitio.
+

NOTE: No se puede utilizar la codificación de borrado si el grupo de almacenamiento incluye dos sitios.

+
** <<Esquemas de codificación de borrado para grupos de almacenamiento que contienen tres o más sitios,Esquemas de codificación de borrado para grupos de almacenamiento que contienen tres o más sitios>>
** <<Esquemas de codificación de borrado para grupos de almacenamiento de un solo sitio,Esquemas de codificación de borrado para grupos de almacenamiento de un solo sitio>>


* No utilice un grupo de almacenamiento que incluya el sitio Todos los sitios.
* El grupo de almacenamiento debe incluir al menos `_k+m_ +1` Nodos de almacenamiento que pueden almacenar datos de objetos.
+

NOTE: Los nodos de almacenamiento se pueden configurar durante la instalación para que contengan solo metadatos de objetos y no datos de objetos. Para obtener más información, consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nodos de almacenamiento"] .

+
El número mínimo de nodos de almacenamiento requeridos es `k+m` .  Sin embargo, tener al menos un nodo de almacenamiento adicional puede ayudar a prevenir fallas de ingesta o retrasos en ILM si un nodo de almacenamiento requerido no está disponible temporalmente.





== Esquemas de codificación de borrado para grupos de almacenamiento que contienen tres o más sitios

La siguiente tabla describe los esquemas de codificación de borrado actualmente admitidos por StorageGRID para grupos de almacenamiento que incluyen tres o más sitios.  Todos estos esquemas brindan protección contra pérdida de sitio.  Se puede perder un sitio y el objeto seguirá siendo accesible.

Para los esquemas de codificación de borrado que brindan protección contra pérdida de sitio, la cantidad recomendada de nodos de almacenamiento en el grupo de almacenamiento excede `_k+m_ +1` porque cada sitio requiere un mínimo de tres nodos de almacenamiento.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Esquema de codificación de borrado (_k+m_) | Número mínimo de sitios implementados | Número recomendado de nodos de almacenamiento en cada sitio | Número total recomendado de nodos de almacenamiento | ¿Protección contra pérdida de sitio? | Gastos generales de almacenamiento 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
Sí
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
Sí
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
Sí
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
Sí
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
Sí
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
Sí
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
Sí
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
Sí
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
Sí
 a| 
71%

|===

NOTE: StorageGRID requiere un mínimo de tres nodos de almacenamiento por sitio.  Para utilizar el esquema 7+5, cada sitio requiere un mínimo de cuatro nodos de almacenamiento.  Se recomienda utilizar cinco nodos de almacenamiento por sitio.

Al seleccionar un esquema de codificación de borrado que proporcione protección del sitio, equilibre la importancia relativa de los siguientes factores:

* *Número de fragmentos*: el rendimiento y la flexibilidad de expansión generalmente son mejores cuando el número total de fragmentos es menor.
* *Tolerancia a fallos*: La tolerancia a fallos aumenta al tener más segmentos de paridad (es decir, cuando `m` tiene un valor más alto.)
* *Tráfico de red*: Al recuperarse de fallas, se utiliza un esquema con más fragmentos (es decir, un total más alto para `k+m` ) crea más tráfico de red.
* *Gastos generales de almacenamiento*: los esquemas con mayores gastos generales requieren más espacio de almacenamiento por objeto.


Por ejemplo, al decidir entre un esquema 4+2 y un esquema 6+3 (ambos tienen una sobrecarga de almacenamiento del 50 %), seleccione el esquema 6+3 si se requiere tolerancia a fallas adicional.  Seleccione el esquema 4+2 si los recursos de red están limitados.  Si todos los demás factores son iguales, seleccione 4+2 porque tiene un número total menor de fragmentos.


NOTE: Si no está seguro de qué esquema utilizar, seleccione 4+2 o 6+3, o comuníquese con el soporte técnico.



== Esquemas de codificación de borrado para grupos de almacenamiento de un solo sitio

Un grupo de almacenamiento de un solo sitio admite todos los esquemas de codificación de borrado definidos para tres o más sitios, siempre que el sitio tenga suficientes nodos de almacenamiento.

El número mínimo de nodos de almacenamiento requeridos es `k+m` , pero un grupo de almacenamiento con `k+m +1` Se recomiendan nodos de almacenamiento.  Por ejemplo, el esquema de codificación de borrado 2+1 requiere un grupo de almacenamiento con un mínimo de tres nodos de almacenamiento, pero se recomiendan cuatro nodos de almacenamiento.

[cols="1a,1a,1a,1a"]
|===
| Esquema de codificación de borrado (_k+m_) | Número mínimo de nodos de almacenamiento | Número recomendado de nodos de almacenamiento | Gastos generales de almacenamiento 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===