---
permalink: fabricpool/creating-tenant-account-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, tenant, SSO 
summary: Debe crear una cuenta de inquilino en Grid Manager para usar FabricPool . 
---
= Crear una cuenta de inquilino para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear una cuenta de inquilino en Grid Manager para usar FabricPool .

Las cuentas de inquilino permiten que las aplicaciones cliente almacenen y recuperen objetos en StorageGRID.  Cada cuenta de inquilino tiene su propio ID de cuenta, grupos y usuarios autorizados, depósitos y objetos.

Para obtener más detalles sobre esta tarea, consultelink:../admin/creating-tenant-account.html["Crear una cuenta de inquilino"] .  Para utilizar el asistente de configuración de FabricPool para completar esta tarea, vaya alink:use-fabricpool-setup-wizard-steps.html["Acceda y complete el asistente de configuración de FabricPool"] .

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tieneslink:../admin/admin-group-permissions.html["permisos de acceso específicos"] .


.Pasos
. Seleccione *INQUILINOS*.
. Seleccione *Crear*.
. Para los pasos de Ingresar detalles, ingrese la siguiente información.
+
[cols="1a,3a"]
|===
| Campo | Descripción 


 a| 
Nombre
 a| 
Un nombre para la cuenta del inquilino.  Los nombres de los inquilinos no necesitan ser únicos.  Cuando se crea la cuenta de inquilino, recibe un ID de cuenta numérico único.



 a| 
Descripción (opcional)
 a| 
Una descripción para ayudar a identificar al inquilino.



 a| 
Tipo de cliente
 a| 
Debe ser *S3* para FabricPool.



 a| 
Cuota de almacenamiento (opcional)
 a| 
Deje este campo en blanco para FabricPool.

|===
. Para el paso Seleccionar permisos:
+
.. No seleccione *Permitir servicios de plataforma*.
+
Los inquilinos de FabricPool normalmente no necesitan utilizar servicios de plataforma, como la replicación de CloudMirror.

.. Opcionalmente, seleccione *Usar fuente de identidad propia*.
.. No seleccione *Permitir selección S3*.
+
Los inquilinos de FabricPool normalmente no necesitan utilizar S3 Select.

.. Opcionalmente, seleccione *Usar conexión de federación de red* para permitir que el inquilino utilice unalink:../admin/grid-federation-overview.html["conexión de federación de red"] para clonación de cuentas y replicación entre redes.  Luego, seleccione la conexión de federación de red que desea utilizar.


. Para el paso Definir acceso raíz, especifique qué usuario tendrá el permiso de acceso raíz inicial para la cuenta de inquilino, en función de si su sistema StorageGRID utilizalink:../admin/using-identity-federation.html["federación de identidades"] ,link:../admin/configuring-sso.html["inicio de sesión único (SSO)"] , o ambos.
+
[cols="1a,2a"]
|===
| Opción | Haz esto 


 a| 
Si la federación de identidad no está habilitada
 a| 
Especifique la contraseña que se utilizará al iniciar sesión en el inquilino como usuario raíz local.



 a| 
Si la federación de identidad está habilitada
 a| 
.. Seleccione un grupo federado existente para tener permiso de acceso raíz para el inquilino.
.. Opcionalmente, especifique la contraseña que se utilizará al iniciar sesión en el inquilino como usuario raíz local.




 a| 
Si tanto la federación de identidad como el inicio de sesión único (SSO) están habilitados
 a| 
Seleccione un grupo federado existente para tener permiso de acceso raíz para el inquilino.  Ningún usuario local puede iniciar sesión.

|===
. Seleccione *Crear inquilino*.

