---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: 'Al configurar StorageGRID para su uso con FabricPool, puede crear opcionalmente uno o más grupos de alta disponibilidad (HA).  Un grupo de alta disponibilidad es una colección de nodos que contienen cada uno el servicio StorageGRID Load Balancer.  Un grupo de alta disponibilidad puede contener nodos de puerta de enlace, nodos de administración o ambos.' 
---
= Cree un grupo de alta disponibilidad (HA) para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar StorageGRID para su uso con FabricPool, puede crear opcionalmente uno o más grupos de alta disponibilidad (HA).  Un grupo de alta disponibilidad es una colección de nodos que contienen cada uno el servicio StorageGRID Load Balancer.  Un grupo de alta disponibilidad puede contener nodos de puerta de enlace, nodos de administración o ambos.

Puede utilizar un grupo HA para ayudar a mantener disponibles las conexiones de datos de FabricPool .  Un grupo de alta disponibilidad utiliza direcciones IP virtuales (VIP) para proporcionar acceso de alta disponibilidad al servicio Load Balancer.  Si la interfaz activa en el grupo HA falla, una interfaz de respaldo puede administrar la carga de trabajo con poco impacto en las operaciones de FabricPool .

Para obtener más detalles sobre esta tarea, consultelink:../admin/managing-high-availability-groups.html["Administrar grupos de alta disponibilidad"] .  Para utilizar el asistente de configuración de FabricPool para completar esta tarea, vaya alink:use-fabricpool-setup-wizard-steps.html["Acceda y complete el asistente de configuración de FabricPool"] .

.Antes de empezar
* Usted ha revisado ellink:best-practices-for-high-availability-groups.html["Mejores prácticas para grupos de alta disponibilidad"] .
* Ha iniciado sesión en Grid Manager mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tú tienes ellink:../admin/admin-group-permissions.html["Permiso de acceso root"] .
* Si planea utilizar una VLAN, habrá creado la interfaz VLAN. Ver link:../admin/configure-vlan-interfaces.html["Configurar interfaces VLAN"] .


.Pasos
. Seleccione *CONFIGURACIÓN* > *Red* > *Grupos de alta disponibilidad*.
. Seleccione *Crear*.
. Para el paso *Ingresar detalles*, complete los siguientes campos.
+
[cols="1a,2a"]
|===
| Campo | Descripción 


 a| 
Nombre del grupo HA
 a| 
Un nombre para mostrar único para este grupo HA.



 a| 
Descripción (opcional)
 a| 
La descripción de este grupo HA.

|===
. Para el paso *Agregar interfaces*, seleccione las interfaces de nodo que desea utilizar en este grupo de HA.
+
Utilice los encabezados de columna para ordenar las filas o ingrese un término de búsqueda para localizar interfaces más rápidamente.

+
Puede seleccionar uno o más nodos, pero solo puede seleccionar una interfaz para cada nodo.

. Para el paso *Priorizar interfaces*, determine la interfaz principal y cualquier interfaz de respaldo para este grupo de HA.
+
Arrastre filas para cambiar los valores en la columna *Orden de prioridad*.

+
La primera interfaz de la lista es la interfaz principal.  La interfaz principal es la interfaz activa a menos que ocurra una falla.

+
Si el grupo HA incluye más de una interfaz y la interfaz activa falla, las direcciones IP virtuales (VIP) se mueven a la primera interfaz de respaldo en el orden de prioridad.  Si esa interfaz falla, las direcciones VIP pasan a la siguiente interfaz de respaldo, y así sucesivamente.  Cuando se resuelven las fallas, las direcciones VIP vuelven a la interfaz de mayor prioridad disponible.

. Para el paso *Ingresar direcciones IP*, complete los siguientes campos.
+
[cols="1a,2a"]
|===
| Campo | Descripción 


 a| 
CIDR de subred
 a| 
La dirección de la subred VIP en notación CIDR: una dirección IPv4 seguida de una barra y la longitud de la subred (0-32).

La dirección de red no debe tener ningún bit de host configurado. Por ejemplo,  `192.16.0.0/22` .



 a| 
Dirección IP de la puerta de enlace (opcional)
 a| 
Opcional. Si las direcciones IP de ONTAP utilizadas para acceder a StorageGRID no están en la misma subred que las direcciones VIP de StorageGRID , ingrese la dirección IP de la puerta de enlace local VIP de StorageGRID .  La dirección IP de la puerta de enlace local debe estar dentro de la subred VIP.



 a| 
Dirección IP virtual
 a| 
Ingrese al menos una y no más de diez direcciones VIP para la interfaz activa en el grupo HA.  Todas las direcciones VIP deben estar dentro de la subred VIP.

Al menos una dirección debe ser IPv4.  Opcionalmente, puede especificar direcciones IPv4 e IPv6 adicionales.

|===
. Seleccione *Crear grupo HA* y luego seleccione *Finalizar*.

